# Preface {.unnumbered}

In 1844, a group of weavers from Rochdale in England set up a small cooperative store on Toad Lane. Now referred to as the Rochdale Pioneers, their practical response to the misery inflicted on the poor by the industrial revolution became a touchstone for a rapidly growing movement of working class people empowering themselves through cooperation and grassroots democracy.
What began as a multitude of local practical answers to the worsening crises of capitalist industrialisation in Britain, France, Germany and beyond soon became an international movement of economic democratisation that transformed the lives and communities of countless peoples around the world.
Credit unions, farmer, worker and consumer cooperatives grew into huge federations wielding significant economic power and which included women as equal voting members decades before women won the right to vote in national or local elections.
These cooperative organisations championed food safety and quality standards, fair prices, decent wages and working conditions and democratic management long before these ideas became part of mainstream conversation or legislation.

The modern cooperative movement that grew from these social innovations among the working classes in nineteenth century Britain and Europe is now a global movement encompassing around 12\% of the world's population. 
Represented by its own international organisation, the International Cooperative Alliance (ICA), the movement brings together a huge diversity of cooperative enterprises across almost all sectors of social and economic life.
As legal forms of organisation, cooperatives, credit unions and other types of mutual associations have become remarkably successful at providing economic stability for their members in the face of the recurring crises of global capitalism.
These successes, however, only partly reflect the original ambitions of the early cooperators, who dreamt of inspiring a complete transformation of society out of the chaos of contemporary capitalism and into a Utopian order of cooperation that would benefit the whole of humanity.
Now that the UN and other international organisations have begun to reflect on the legacy and future of cooperativism from the perspective of environmental sustainability and social development, those earlier dreams of systemic change have taken on a new significance.

The present crises of climate and ecosystem breakdown, worsening pollution and socio-economic inequality and the rapid loss of trust in politics and institutions have prompted many to seek to recover the radical values of cooperativism and reinterpret them, often with a post-capitalist slant.
To provide a coherent framing for these efforts, the idea of 'New Cooperativism' has come to be used to refer to cooperative projects which emphasise common good orientation, multistakeholder participation, a transformative stance against the status quo and a commitment to participatory democratic governance.
These so-called 'New Cooperatives' are emerging all over the world as a new kind of social enterprise aimed at creating fairer and more sustainable ways of meeting people's need for food, housing, energy, transportation, social and health care and to provide new contexts for community building and cultural renewal.

Among these essential sectors, food systems present perhaps the most complex and difficult contexts for change as they connect an intricate and global network of producers, processors, distributors, consumers, government ministries, research systems, multinational corporations, hospitality businesses, caterers and local retailers, among many other actors whose perceptions and practices are shaped by diverse and deep-rooted cultural traditions and sharply competing interests.
The need for change is also extremely urgent.
Contemporary industrialised food systems involve the extravagant use of non-renewable energy and toxic inputs manufactured from rapidly depleting fossil fuels to produce highly processed foods that cause multiple negative impacts on human health, all while polluting the environment, degrading ecosystems, driving pandemic risk from zoonotic spillover, and generating massive quantities of greenhouse gases.
Neither do farmers themselves derive much livelihood security from this arrangement but rather face a constant downward pressure on incomes that is made worse by the growing impacts of an unpredictable and increasingly volatile climate and market.
It is perhaps only from within the boardrooms of multinational food companies and agribusiness that the twentieth century approach to food and farming appears remotely defensible.
The only remaining justification for the status quo is the share prices of profit-driven companies and hedge funds engaged in controlling and manipulating the production and trade of food as a commodity or as the basis of financial derivatives and futures.

It seems unlikely that change will occur from the top down, or if it does, it is even less likely that such change will be for the benefit of the majority of farmers and consumers.
So the question is, as a growing grassroots movement for economic democracy and mutual aid, what contribution might 'New Cooperatives' make to transforming food systems from the bottom up?

This is a question I have been thinking and talking about for nearly 5 years.
By taking a deep dive into the past and present of the Hansalim Life Movement in South Korea -- one of the most successful and least known multistakeholder cooperatives in organic food and farming -- I want to suggest some possible answers.

The first reason for choosing to study Hansalim is that it seems to me to embody the same values and aspirations of the 'New Cooperatives' as well as displaying some other features not normally associated with examples of New Cooperativism that have so far been studied.
That makes it interesting as a case study from which to reflect on the ideas and initiatives that are associated with New Cooperativism in other contexts -- which currently are drawn mostly from Europe, North and South America.
The second reason is the size and scope of Hansalim as both a movement and a federation of diverse democratic organisations.
The fact that such a large cooperative enterprise has been created in the organic food sector in an advanced industrialised country by small scale producers and consumers working together is remarkable.
The final reason is the longevity of Hansalim.
The Hansalim Life Movement will be 40 years old in 2025 and its roots go back even further to the 1960s.
The ability for such a project not only to grow, but to resist the pressure of conforming to capitalist markets, degenerating, splitting or succumbing to demutualisation implies a certain degree of resilience and confirms that Hansalim is not just a niche experiment but a mature movement.
From the perspective of New Cooperativism, Hansalim represents a rare and previously unrecognised example of a mature large-scale New Cooperative in organic food; one that brings together producers and consumers in a way that is normally thought impossible or at least highly impractical.  
With this in mind, I applied for a Marie Skłodowska-Curie Global Fellowship in 2019 to lead a research project with the University of Sussex in partnership with Hansalim's Mosim and Salim Research Institute in Korea.

For four years, since moving to South Korea in 2020, I have been involved in research about and with Hansalim.
As a proof reader, I assisted the translation of the Hansalim Manifesto into English in 2021 at which point I also began my 3 year Marie Skłodowska-Curie Research Fellowship to investigate the Hansalim Life Movement.
As a researcher I am interested not only in the practicalities and organisational structure of Hansalim as a cooperative but also the history of the movement, the philosophy in which it is rooted and the experiences of the individual members of this unique community.
This book introduces the story of Hansalim, explains what it is today and describes Hansalim's fascinating journey from its roots in the pro-democracy movement in 1960s Korea to becoming a national Federation of Life Cooperatives.
The material for this book is drawn from interviews conducted between 2022-2024 and Korean language materials collected over the same period, including academic papers, books and reports published by Hansalim, and archived materials held by the Mosim and Salim Research Institute.

Although the writing process for this book began in the second year of my project, the amount of material and the complexity and richness of Hansalim as movement and federation of multiple organisations, each with their own histories, has meant that I still have a long way to go to complete it!
I have chosen to publish the book in serial form online (i.e. one chapter at a time as each chapter is completed).
My reason for doing this is that I want to make up for the current  lack of English language information about Hansalim as fast as possible.
I believe the story and experience of Hansalim will be of great interest to those in Europe seeking to transform food systems from the grassroots.
So in this 'first edition' I present the introduction and chapter 1 along with two appendices of materials translated from original blog posts by Hansalim that will be of special interest to farmers.
Together, this material is what I expect to be most useful for practitioners in Europe seeking a straightforward introduction to what Hansalim is.
The later chapters will include some more detailed history and explanation of the philosophy behind Hansalim as well as personal stories of Hansalim members.
Finally, I intend to write one or two chapters that draw out specific lessons for contexts beyond Korea.

# Acknowledgements

This project has received funding from the European Union's Horizon 2020 research and innovation programme under the Marie Skłodowska-Curie fellowship grant agreement No 892403 between September 2021 and August 2024.
The author was hosted for the duration of the fellowship by the Science Policy Research Unit, University of Sussex Business School and the Mosim and Salim Research Institute.

# Notes

Except for the names of cited authors and place names with pre-established spellings, this book follows the romanization system of South Korea known as the Revised Romanization system.
For the details of the romanization of korean see: https://www.korean.go.kr/front_eng/roman/roman_01.do