# Beginnings

On the 4th of December 1986, while the streets of Seoul were filled with protesters, police and tear gas, a consumer cooperative from the nearby city of Wonju opened a small rice store in Dongdaemun, one of Seoul's central market districts.
It was called 'Hansalim Nongsan' and it was set up by members of the so-called 'Wongju Group' to manage the direct sale of organic rice and other agricultural products to consumers in the capital city and beyond.
On the surface, it was an unremarkable event, especially given the mass protests sweeping the country which, just ... months later, brought about the transition from military dictatorship to the first democratically elected government in decades.
But if you knew the people doing it and if you heard their stories you would understand that it was an act of resistance as significant as the mass demonstrations that filled the streets around it.



It was also in Wonju that the various democratisation and cooperative movements began to connect across religious and ideological divides.



But the most significant influence on his philosophy and way of life was Haewol (Choi Sihyung), a nearly forgotten leader of an indigenous Korean religion called Donghak (now known as Cheondogyo or the Heavenly Way).

Donghak was founded in 1860 by Su-un (Choi Je-u) 




## Roots in Wonju

During the 1970s Wonju was the centre of the 'minjung movement' (common people's movement) \autocite{Kim2019-dd}

The Wonju Group were part of an alliance of pro-democracy movements among students, farmers, workers, intellectuals and religious groups which fought for democracy in Korea throughout the 1970s and 1980s, known collectively as the 'Minjung Movement' (common people's movement).

Calligrapher, Bishop, Poet and 

### Jang Il-soon - Calligrapher

Jang Il-soon was born in 1928 in the rural town of Wonju, not far from Seoul.
By the time of his birth, Korea had been under repressive Japanese colonial rule for nearly two decades and times were hard for everyone.
As relatively wealthy land-owners with multiple generations of ancestry in Wonju, his family saw it as their responsibility to support their poorer neighbours and ease their difficult lives under the occupation.
Jang Il-soon's grandfather had converted to Catholicism and demonstrated generosity and sincere respect for the poor that made a deep impression on his grandchildren.

It wasn't until 1945 that his homeland was finally liberated by allied forces only to be arbitrarily split in two and divided between the victors into North and South Korea.
Following the transition from the US military government of the South to an independent republic, Rhee Syngman was elected president almost unopposed.
He quickly enacted authoritarian laws and began to run the country as a police state.
In a frenzy of anti-communist crackdowns and suppression of political dissent, the regime imprisoned tens of thousands of suspected communists and put hundreds of thousands through official re-education.
His regime even massacred thousands of its own people in what is now known as the Jeju Uprising of 3 April 1948.
Amidst such difficult conditions between liberation and the outbreak of the Korean war, Jang Il-soon took on the role of a dissident intellectual and developed his interest in philosophy, studying in the department of aesthetics at Seoul National University.

What little stability remained was shattered when war broke out on the 25th of June 1950 and the whole peninsula was plunged into chaos.
In Wonju, just as all over the south, landowners were captured by the communist people's army and executed or taken to North Korea.
Jang Il-soon's family home was bombed and his family only escaped thanks to the kindness of the peasants who gave them shelter in their own homes and moved them secretly from house to house to avoid capture.
Jang's family, who had once supported their neighbours during the colonial era, now found themselves homeless and dependent upon the kindness of others.

The war left nearly 3 million dead, created hundreds of thousands of internal refugees and millions of families permanently separated \autocite{Kim2017-xf}.
Those who survived witnessed unspeakable horrors committed by both sides on their own country people in the name of ideology.
Jang Il-soon himself narrowly escaped being executed by a South Korean firing squad when they mistook him for a north Korean soldier because he had shaved his hair to save on water for washing.
When an officer saw him make the sign of the cross as he prepared for death, they realised he couldn't be a communist solider since he was Catholic.
Rather than execute him, they conscripted him as a labourer and took him with them to the front.
From there he was sent to assist at a prisoner of war camp where his ability to speak English made him useful to US soldiers interrogating North Korean prisoners.
What he experienced during that time confirmed in him what became a lifelong commitment to the peace movement.

As soon as he was discharged from the army, he returned home to Wonju and there he remained for the rest of his life.
His first passion was for education, so rather than return to Seoul National University, he persuaded his parents to support him to teach poor local children who otherwise would have no chance of an education.
He taught for a year without a salary at the local secondary school and when the teachers took over the school to manage it as a democratic organisation, he was elected principal.
The school was renamed Daesung School in honour of Daesung Academy which was a people's school (민족학교) founded by Ahn Chang-ho, one of the leading independence activists during the colonial era whose emphasis on education for the formation of character, cultural identity and "civic virtue" was to echo through Jang Il-soon's own life's work.

Rhee Syngman strengthened his hold on power following the war and amended the constitution to allow himself to remain the country's dictator for life.
Thus, he became the autocratic ruler of a third world country, stricken by poverty, division and corruption.
Harassed by police and anti-communist groups, Jang Il-soon continued teaching at the school and participated in the democracy movement from his home in Wonju.
In 1958 he stood in the national elections, speaking out against the Rhee regime and calling for peaceful reunification and progressive economic policies.
He never had a chance of winning in the face of state intimidation of opposition parties, but it was his way of taking a public stand against the autocratic government.

Frustration among students and other citizens boiled over in 1960 when Rhee won a further rigged election on the 15th March.
That same day, in the city of Masan, on the south-east coast, protests against the result were met with police violence who fired tear gas canisters directly into the crowds.
The death of high school student Kim Ju-yul, struck in the face by one of those canisters, and the subsequent attempt by Rhee to cover up the incident sparked further mass protests in Masan, Seoul and across the country forming a national movement calling for Rhee's resignation and for democratic elections.
On the 19th April, high school and university students who had marched to the Blue House for a peaceful protest were fired upon by police, killing 180 and wounding many more.
Martial law was declared to quell the demonstrations.
Despite the threat of violence, the demonstrations only increased and police and soldiers began refusing to attack the protesters, leaving Rhee with no choice but to resign.
This was the 'April Revolution' - referred to in Korea simply as 4.19 - which led to a short-lived period of parliamentary democracy.

On the 17th June 1960, a committee was formed to prepare for the founding of the Socialist Popular Party, led by the progressive Gujinbo Party, the Labour Party, and the Democratic Innovation Party, with the goal of rebuilding an innovative party. Seo Sang-il and Yoon Gil-joong were elected as cadres, and the party was founded on 24 November 1960. Some of the students who led the April Revolution were also involved. Jang Il-sun also participated as a promoter.

### Ji Hak-soon - Bishop

It would be good to include the content of the Second Vatican Council in the content of Bishop Ji Hak-Soon.
Bishop Ji Hak-Soon studied in Rome.
The core content is that the church should not stay in the traditional church but actively engage in social reform.
After the council, the contents of the council were translated from Japanese to Korean and shared. Held study gatherings in Wonju.
Shared with Jang Il-sun and key Wonju people, and subsequently created a lay council in the Wonju diocese. President of the first lay council was Jang Il-Soon.

After Ji Hak-soon finished his study in Rome he was influenced from the 2nd Vatican Council. (check Baek PhD and Jang Il-soon Biography).
Not just stay in church but go out to the people.
There was a gathering to translate the Vatican two documents into Korean even before it reached Japan.
Thats when they started to include lay people in the committees (like Jang Il-soon) whereas before it was just priests and deacons (ordained people).

Wonju Group and cultural centre (theatre).

### Kim Ji-ha - Poet

### Park Jae-il - Farmer

## The Great Flood

## The Gwangju Uprising

7 years earlier the authoritarian regime of Park Chung Hee that had seemed immovable for nearly two decades, suddenly ended with his assassination.
The democracy movement, that had been suppressed by Park, sprang back to life, as people rekindled hope for a transition to genuine democracy.
But the new government fell in a matter of weeks as the chief of defence General Chun Doo-hwan led a military insurrection on December 12th 1979 and declared martial law.

The immediate reaction by citizens has become known as the "Seoul Spring".
Waves of mass protests spread across the country as students and workers took to the streets to oppose the military's takeover and call for democracy.
The military's brutal response involved mass arrests, beatings, torture and killing of protesters.
Things quickly came to a head in the city of Gwangju in south Jeolla province, a hotbed of pro-democracy activism.

While mass protests in the city had been held peacefully with police cooperation during the previous days, in preparation for General Chun's final takeover of the government, paratroops and tanks had been sent to Gwangju to suppress the protests, beginning by arresting most of the leaders of Gwangju's democracy movement.
On May 18th, when students attempted to enter the city's Chonnam National University campus they were brutally beaten by the waiting paratroopers and turned away from the university gates.
This provoked spontaneous protests among students which spread across the city throughout the day, calling for an end to martial law and the removal of Chun Doo-hwan.
This time, they were met by violence from the riot police and confrontations escalated throughout the day as students fought back and the numbers of protesters steadily grew.
When the paratroopers began to chase down and to strip and beat the demonstrators and bystanders alike, the student protest became a popular revolt.

The next day it wasn't just hundreds of students on the streets but around four thousand citizens - high school students, shop owners, labourers, housewives, priests and teachers - came out to support the students and confront the police and paratroopers in front of Province Hall.
When the police fired teargas and the paratroopers charged the demonstrators, they responded by breaking up paving stones to throw and collected metal pipes and other implements to use as makeshift weapons.
Molotov cocktails, drums of oil and nearby vehicles were used to attack and drive back the troops.
Taxi drivers took on the role of ambulances to take the injured protesters to hospitals.
Buses, trucks and phone booths became barricades.

The clashes between citizens and military became more violent and the paratroopers used their batons, rifle buts and bayonets to attack the crowds and hunted people down as they fled down alleys and into nearby buildings.
Whoever they captured they stripped, beat and tortured, leaving many dead or with life changing injuries and taking many more students back to their camp as prisoners.
Even some of the riot police who tried to help the wounded, unaccustomed to the extreme violence perpetrated by the military forces, were themselves attacked by the paratroopers.

Over the next few days more than 200,000 demonstrators fought against the police and paratroopers across the city.
Convoys of over 100 taxis and some buses and trucks joined the demonstrators on the streets and some began to use vehicles as battering rams and fire bombs to attack the paratroopers blockades.
The streets were covered in burning cars, debris and the bodies of dead and injured protesters lying in pools of blood.
Citizen Militia began to capture vehicles, explosives, rifles and ammunition to strengthen their stand against government forces who had begun to use live ammunition on the crowds leading to several fatalities and provoking growing rage among the citizens.
Then the paratroopers deployed machine guns, automatic rifles and snipers to attack the citizens and military helicopters also opened fire on the crowds.
Despite their resort to lethal force, the paratroopers were overwhelmed by the scale of the uprising, and withdrew to the outskirts of the city where they prepared for a large-scale offensive with reinforcements from the army's 20th Division.

The demonstrators took control of Province Hall and other parts of the city center and organised a Citizen Settlement Committee to negotiate with the government forces.
Having withdrawn from the city centre, soldiers blockaded Gwangju and were ordered to use lethal force against any resistance.
Finally, after five days of blockade, in the middle of the night on the 27th May 1980 three special forces teams and a division of more than 3,000 soldiers moved on the city centre to recapture Province Hall and Gwangju Park in a battle that ended with 27 citizens and 2 soldiers dead and 295 citizens detained.

Over the course of the uprising, 20,000 trained soldiers were deployed to the city of 800,000.
The total number of casualties is not known, as the government acted quickly to cover up the incident and manipulate the data reported.
Conservative estimates are that over 200 of Gwangju's residents were killed by government forces and many more hundreds injured while the so-called 'ring leaders' were imprisoned and tortured.

Despite the immediate cover up, news of the massacre at Gwangju spread among democracy activists and students and helped to undermine the legitimacy of the Chun regime, becoming a rallying cry for the pro-democracy movement.
By 1985, it was clear that the memory of the Gwangju uprising and the Chun government's massacre of civilians was firmly fixed in the national psyche and each year following, the anniversary of the uprising was marked by increasing numbers of participants who commemorated the victim's sacrifice for democracy.

## A Change of Direction

### Haewol - Sage

### The Wonju Report

## Parallel Stories

### Gyeongnam

### Goesan

## Hansalim is Born

### Lee Soon-ro - Housewife

## The Life Movement Takes Off

### The Hansalim Gathering

### The Hansalim Manifesto

### Vision, Values and Practice


Thus it was in an atmosphere of growing resistance against authoritarian oppression, driven by the hope of democracy, that an eclectic group of farmers, housewives, artists and intellectuals from Wonju opened their store as the first step in launching an ambitious experiment in grassroots democracy.
Their vision was to create an alternative way of living that brought urban and rural communities together in mutual care for one another and shared responsibility for the natural world.
They weren't content to call for a transition to democratic government without addressing what they saw as the fundamentally anti-life worldview of industrial civilisation, whether capitalist or communist, democratic or authoritarian.
Neither were they prepared to accept that Marxism-inspired violent revolution was the route to liberation.
Instead, they were intent on building from the ground up, a democratic alternative based on what they called a 'worldview of life' and the expansion of the cooperative movement into all areas of social and economic life starting with the poorest and most marginalised in society.

Like Gwangju, the city of Wonju had also been a beacon of the democracy movement since the 1960s and many among the Wonju Group had  themselves joined the anti-dictatorship protest movements of those days and been imprisoned for their opposition to the Park regime.
Among them were a bishop, a calligrapher, several farmers, a singer songwriter, a poet Kim Ji-ha (poet).
They had become involved with cooperative and credit union movement in Wonju, led by Bishop Ji Hak-soon .....