# Beginnings

For Suun, the Heavenly Way can be found only through a particular way of knowing which he calls _buryeon giyeon_ (不然其然) which can be translated as "not so (buryeon), yet so (giyeon)". Kim and Yoon [@Kim2007-sv] explain this concept as follows:

> "According to Suun, we usually live in the phenomenal world of ordinary experience, which is _giyeon_. However, ultimately and in the deepest level of our being we live in the world of _buryeon_, which lies beyond the realm of the ordinary sense experience." [@Kim2007-sv, p. 72].

These and other ideas from Donghak were later taken up in the Hansalim Manifesto and form the core values of the Hansalim movement and the federation of cooperatives at its heart.

\subsection{Owenism and The Rochdale Pioneers}

While Korea was sliding into chaos and trying in vain to resist western, Chinese and Japanese colonial ambitions, England was in the midst of an entirely different but perhaps equally disruptive period of chaotic change.
The British Empire and its other European rivals had by now virtually wiped out the populations of the Americas, replaced them with enslaved Africans and begun exploiting their colonies to enrich the home nations and their capitalist entrepreneurs.
The mechanisation of ......

This in turn -  and industrialisation 


It was in this context that Robert Owen .....

Despite this repeated failures, Owenism lived on and .... Rochdale Pioneers.

A few decades earlier in Manchester, we meet Robert Owen, whose Utopian vision of an alternative society inspired the British socialist movement.
He 
Eventually these ideas prompted a small group of workers in a northern industrial town in 19th Century England to set up a cooperative society in 1844.
They became known as the 'Rochdale Pioneers' and are recognised around the world as the founders of British cooperativism.

\subsection{Danish Folk High Schools}

Taking a somewhat different perspective on things .... Grundtvig....

In Europe we encounter the grassroots Folk High Schools movement (Folkehøjskole) which, inspired by the ideas of Grundtvig, emerged in Denmark the late 19th and early 20th Century laying the pathway to Danish democracy and which spread to Germany, Switzerland, Austria and even as far as the United States and East Asia.

\subsection{The Antagonish Movement}

By the time America had become

From the American continent we meet the 1920-30s Antagonish movement in Canada and 

\subsection{Missionary Mobilisations}

witness the 20th Century mobilisation of Protestant and Catholic missionaries to East Asia.
Japan

\subsection{Korea under Japanese Colonialism}

\subsection{Post-war Struggle for Democracy}


when a new  movement emerged from  Catholic farmers, urban housewives, female workers, pro-democracy activists, educators and intellectuals 


development aid provided to Korea by Germany and others in the 1970s.

Wonju Life Movement
Founding of Hansalim

\subsection{Hansalim's Journey in a Democratising Korea}


While an impoverished scholar in 



There are several dates known to all Koreans simply by their numerical references: 3.1, 4.3, 5.18 and 6.10.
Like sacred symbols that hold memories too painful to be spoken aloud, they preserve the sense of an inexpressible debt owed to those who risked their lives to stand up against oppression and dictatorship.
In fact, all but one of these dates commemorates the bravery of students, many of whom were tortured and murdered for daring to resist the.

On the 1st of March 1919




3.1 (1919) March 1st Movement (Independence Movement)
4.3 Jeju Uprising 
5.18 (1980) Gwangju Uprising
6.10 (1987) Democracy Movement

\section{Co-operativism in Korea}\label{koreancooperativism:sec}

\section{The founding of the Hansalim Life Movement}\label{founding:sec}


Outline of Hansalim’s philosophy and its basis in the Korean indigenous religion of Donghak.
Outline influence of this philosophy on other cooperatives in Korea.
Brief description of Hansalim’s journey in creating one of the world’s largest organic food cooperatives.