### Jang Il-soon - Calligrapher

Jang Il-soon was born in 1928 in the rural town of Wonju, not far from Seoul.
By the time of his birth, Korea had been under repressive Japanese colonial rule for nearly two decades and times were hard for everyone.
As relatively wealthy land-owners with multiple generations of ancestry in Wonju, his family saw it as their responsibility to support their poorer neighbours and ease their difficult lives under the occupation.
Jang Il-soon's grandfather had converted to Catholicism and demonstrated generosity and sincere respect for the poor that made a deep impression on his grandchildren.

It wasn't until 1945 that his homeland was finally liberated by allied forces only to be arbitrarily split in two and divided between the victors into North and South Korea.
Following the transition from the US military government of the South to an independent republic, Rhee Syngman was elected president almost unopposed.
He quickly enacted authoritarian laws and began to run the country as a police state.
In a frenzy of anti-communist crackdowns and suppression of political dissent, the regime imprisoned tens of thousands of suspected communists and put hundreds of thousands through official re-education.
His regime even massacred thousands of its own people in what is now known as the Jeju Uprising of 3 April 1948.
Amidst such difficult conditions between liberation and the outbreak of the Korean war, Jang Il-soon took on the role of a dissident intellectual and developed his interest in philosophy, studying in the department of aesthetics at Seoul National University.

What little stability remained was shattered when war broke out on the 25th of June 1950 and the whole peninsula was plunged into chaos.
In Wonju, just as all over the south, landowners were captured by the communist people's army and executed or taken to North Korea.
Jang Il-soon's family home was bombed and his family only escaped thanks to the kindness of the peasants who gave them shelter in their own homes and moved them secretly from house to house to avoid capture.
Jang's family, who had once supported their neighbours during the colonial era, now found themselves homeless and dependent upon the kindness of others.

The war left nearly 3 million dead, created hundreds of thousands of internal refugees and millions of families permanently separated \autocite{Kim2017-xf}.
Those who survived witnessed unspeakable horrors committed by both sides on their own country people in the name of ideology.
Jang Il-soon himself narrowly escaped being executed by a South Korean firing squad when they mistook him for a north Korean soldier because he had shaved his hair to save on water for washing.
When an officer saw him make the sign of the cross as he prepared for death, they realised he couldn't be a communist solider since he was Catholic.
Rather than execute him, they conscripted him as a labourer and took him with them to the front.
From there he was sent to assist at a prisoner of war camp where his ability to speak English made him useful to US soldiers interrogating North Korean prisoners.
What he experienced during that time confirmed in him what became a lifelong commitment to the peace movement.

As soon as he was discharged from the army, he returned home to Wonju and there he remained for the rest of his life.
His first passion was for education, so rather than return to Seoul National University, he persuaded his parents to support him to teach poor local children who otherwise would have no chance of an education.
He taught for a year without a salary at the local secondary school and when the teachers took over the school to manage it as a democratic organisation, he was elected principal.
The school was renamed Daesung School in honour of Daesung Academy which was a people's school (민족학교) founded by Ahn Chang-ho, one of the leading independence activists during the colonial era whose emphasis on education for the formation of character, cultural identity and "civic virtue" was to echo through Jang Il-soon's own life's work.

Rhee Syngman strengthened his hold on power following the war and amended the constitution to allow himself to remain the country's dictator for life.
Thus, he became the autocratic ruler of a third world country, stricken by poverty, division and corruption.
Harassed by police and anti-communist groups, Jang Il-soon continued teaching at the school and participated in the democracy movement from his home in Wonju.
In 1958 he stood in the national elections, speaking out against the Rhee regime and calling for peaceful reunification and progressive economic policies.
He never had a chance of winning in the face of state intimidation of opposition parties, but it was his way of taking a public stand against the autocratic government.

Frustration among students and other citizens boiled over in 1960 when Rhee won a further rigged election on the 15th March.
That same day, in the city of Masan, on the south-east coast, protests against the result were met with police violence who fired tear gas canisters directly into the crowds.
The death of high school student Kim Ju-yul, struck in the face by one of those canisters, and the subsequent attempt by Rhee to cover up the incident sparked further mass protests in Masan, Seoul and across the country forming a national movement calling for Rhee's resignation and for democratic elections.
On the 19th April, high school and university students who had marched to the Blue House for a peaceful protest were fired upon by police, killing 180 and wounding many more.
Martial law was declared to quell the demonstrations.
Despite the threat of violence, the demonstrations only increased and police and soldiers began refusing to attack the protesters, leaving Rhee with no choice but to resign.
This was the 'April Revolution' - referred to in Korea simply as 4.19 - which led to a short-lived period of parliamentary democracy.

On the 17th June 1960, a committee was formed to prepare for the founding of the Socialist Popular Party, led by the progressive Gujinbo Party, the Labour Party, and the Democratic Innovation Party, with the goal of rebuilding an innovative party. Seo Sang-il and Yoon Gil-joong were elected as cadres, and the party was founded on 24 November 1960. Some of the students who led the April Revolution were also involved. Jang Il-sun also participated as a promoter.