<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>1&nbsp; What is Hansalim? – Hansalim: the universe in a bowl of rice</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/references.html" rel="next">
<link href="../intro.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2486e1f0a3ee9ee1fc393803a1361cdb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-af34e1d557ac5910fc8d786d44d80f7c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-RQ8H157TLG"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-RQ8H157TLG', { 'anonymize_ip': true});
</script>
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<link href="../site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">
<script src="../site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="../site_libs/plotly-binding-4.10.4/plotly.js"></script>
<script src="../site_libs/typedarray-0.1/typedarray.min.js"></script>
<script src="../site_libs/jquery-3.5.1/jquery.min.js"></script>
<link href="../site_libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet">
<script src="../site_libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<link href="../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="../site_libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/01_hansalim.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What is Hansalim?</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Hansalim: the universe in a bowl of rice</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01_hansalim.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What is Hansalim?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliography</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/01_farming_blog.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Hansalim Farming is Different</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/02_illustrated_farming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Illustrated Hansalim Farming Methods</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#a-movement-a-manifesto-a-business" id="toc-a-movement-a-manifesto-a-business" class="nav-link active" data-scroll-target="#a-movement-a-manifesto-a-business"><span class="header-section-number">1.1</span> A movement, a manifesto, a business</a></li>
  <li><a href="#built-on-a-relationship-of-mutual-care" id="toc-built-on-a-relationship-of-mutual-care" class="nav-link" data-scroll-target="#built-on-a-relationship-of-mutual-care"><span class="header-section-number">1.2</span> Built on a relationship of mutual care</a></li>
  <li><a href="#in-the-form-of-a-multistakeholder-cooperative" id="toc-in-the-form-of-a-multistakeholder-cooperative" class="nav-link" data-scroll-target="#in-the-form-of-a-multistakeholder-cooperative"><span class="header-section-number">1.3</span> In the form of a multistakeholder cooperative</a></li>
  <li><a href="#creating-an-alternative-economy" id="toc-creating-an-alternative-economy" class="nav-link" data-scroll-target="#creating-an-alternative-economy"><span class="header-section-number">1.4</span> Creating an alternative economy</a>
  <ul class="collapse">
  <li><a href="#a-system-designed-for-producers" id="toc-a-system-designed-for-producers" class="nav-link" data-scroll-target="#a-system-designed-for-producers">A system designed for producers</a></li>
  <li><a href="#a-different-kind-of-consumer-experience" id="toc-a-different-kind-of-consumer-experience" class="nav-link" data-scroll-target="#a-different-kind-of-consumer-experience">A different kind of consumer experience</a></li>
  <li><a href="#the-special-role-of-practitioners" id="toc-the-special-role-of-practitioners" class="nav-link" data-scroll-target="#the-special-role-of-practitioners">The special role of practitioners</a></li>
  </ul></li>
  <li><a href="#governed-through-deliberative-democracy" id="toc-governed-through-deliberative-democracy" class="nav-link" data-scroll-target="#governed-through-deliberative-democracy"><span class="header-section-number">1.5</span> Governed through deliberative democracy</a>
  <ul class="collapse">
  <li><a href="#subsidiarity" id="toc-subsidiarity" class="nav-link" data-scroll-target="#subsidiarity">Subsidiarity</a></li>
  <li><a href="#mutual-responsibilities" id="toc-mutual-responsibilities" class="nav-link" data-scroll-target="#mutual-responsibilities">Mutual responsibilities</a></li>
  <li><a href="#deliberation" id="toc-deliberation" class="nav-link" data-scroll-target="#deliberation">Deliberation</a></li>
  </ul></li>
  <li><a href="#rooted-in-a-history-of-struggle" id="toc-rooted-in-a-history-of-struggle" class="nav-link" data-scroll-target="#rooted-in-a-history-of-struggle"><span class="header-section-number">1.6</span> Rooted in a history of struggle</a>
  <ul class="collapse">
  <li><a href="#fighting-for-independence" id="toc-fighting-for-independence" class="nav-link" data-scroll-target="#fighting-for-independence">Fighting for independence</a></li>
  <li><a href="#fighting-for-democracy" id="toc-fighting-for-democracy" class="nav-link" data-scroll-target="#fighting-for-democracy">Fighting for democracy</a></li>
  <li><a href="#fighting-for-a-civilisation-of-life" id="toc-fighting-for-a-civilisation-of-life" class="nav-link" data-scroll-target="#fighting-for-a-civilisation-of-life">Fighting for a civilisation of Life</a></li>
  </ul></li>
  <li><a href="#on-a-tilting-unfinished-journey" id="toc-on-a-tilting-unfinished-journey" class="nav-link" data-scroll-target="#on-a-tilting-unfinished-journey"><span class="header-section-number">1.7</span> On a tilting unfinished journey</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">1.8</span> Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What is Hansalim?</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In 1986 pro-democracy protesters were out in the streets fighting with police and trying to escape tear gas.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Since seizing power in a military coup in 1961, General Park Chung-hee presided over 18 years of military rule. Following his assassination in 1979 and another coup, General Chun Doo-hwan installed himself as president, leading what was essentially a continuation of the military regime in the face of growing mass protests calling for democratic government.<span class="citation" data-cites="Hwang2021-dl"><a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></span></p>
<p>In the midst of such turmoil, a small group of farmers and activists opened a small rice store in the centre of Seoul. In light of the chaotic political situation, this was seen by their fellow pro-democracy activists as a betrayal. However, the creation of that first store, called Hansalim Nongsan, was actually a radical act of resistance and hope in the face of political uncertainty. The men and women who opened Hansalim Nongsan belonged to a small cooperative of producers and consumers in a city called Wonju, about an hour away from Seoul, and that store represented a first step in launching an ecological alternative movement that had been gathering support in Wonju and beyond since the late 1970s. It’s founders where known as the Wonju Group.</p>
<section id="a-movement-a-manifesto-a-business" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="a-movement-a-manifesto-a-business"><span class="header-section-number">1.1</span> A movement, a manifesto, a business</h2>
<p>The Wonju Group were a diverse collection of Catholic Farmers, urban housewives, pro-democracy activists, artists, poets and scholars who had been involved in the credit union movement in Wonju that was founded in the 1960s. They had witnessed the fundamentally destructive tendencies of capitalist and socialist industrialisation and they were looking for an alternative in the cooperative movement. However, they recognised that cooperatives were also vulnerable to the same fundamental mistake that lay at the heart of industrial civilization. That mistake was to assume a materialist, mechanistic view of the world which viewed humans and all life as replaceable parts in the machine of economic growth. It was this worldview, they argued, that gave rise to the characteristics of domination, alienation, separation and oppression in modern society.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Hansalim-Moim.jpeg" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="The Wonju Group with the Hansalim Gathering (1989)"><img src="../images/chapter_01/Hansalim-Moim.jpeg" class="img-fluid figure-img" alt="The Wonju Group with the Hansalim Gathering (1989)"></a></p>
<figcaption>The Wonju Group with the Hansalim Gathering (1989)</figcaption>
</figure>
</div>
<p>As an alternative, they proposed a worldview founded on the sacredness and interconnectedness of all life. The first version of this worldview or eco-philosophy was outlined in the Wonju Report in 1982. As the movement began to grow the Wonju Group set up the first Life Cooperative in Wonju in 1985 and the Hansalim Nongsan rice store a year later.<span class="citation" data-cites="Hansalim2017-qp"><a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></span> In this way, the Wonju Coop formally brought together organic farming and direct trade with the equal participation of consumers and producers.</p>
<div>

</div>
<div class="quarto-layout-panel" data-layout="[70,30]">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 70.0%;justify-content: flex-start;">
<p>Soon after, the Hansalim Community Consumers Union was set-up in Seoul with 70 members to trade directly with the Hansalim Producers Association that was set up with 70 farming households. Next, the Wonju Group hosted a year long process of study and discussion to develop the Hansalim Manifesto which was published in 1989 and which formally launched the Hansalim Life Movement. From this small beginning, the movement quickly expanded as other cooperatives and farming communities joined from across the country and consumer membership grew.</p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 30.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><a href="../images/chapter_01/Hansalim-Manifesto.jpeg" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="The Hansalim Manifesto, English version"><img src="../images/chapter_01/Hansalim-Manifesto.jpeg" class="img-fluid quarto-figure quarto-figure-left figure-img" alt="The Hansalim Manifesto, English version"></a></p>
</figure>
</div>
<figcaption>The Hansalim Manifesto, English version</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>By 1990 there were four Life Cooperatives with over 5,500 members and within just over another 10 years membership had grown to over 40,000. That is when things really began to take off and by 2008 there were 19 Life Cooperatives managing 84 stores for their 170,000 members. In 2023 Hansalim’s 27 Life Cooperatives and 15 Producer Federations handled annual sales of 485,066 million KRW (324.3 million euros) through 240 stores, an online store and a mobile app.<span class="citation" data-cites="Hansalim2024-zt"><a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></span> From these sales, 330,610 million KRW (221 million euros) were returned to the 136 producer communities. That is nearly 70%! So what kind of business model has Hansalim created that provides those returns to producers while covering the shared business operations and funding a whole range of movement activities from the remaining 30%? And what lies at the heart of this unusual way of doing business?</p>
<p>(Graph of growth)</p>
</section>
<section id="built-on-a-relationship-of-mutual-care" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="built-on-a-relationship-of-mutual-care"><span class="header-section-number">1.2</span> Built on a relationship of mutual care</h2>
<p>At its simplest, the Hansalim Life Movement is a relationship of mutual care and responsibility between rural and urban communities. The core of Hansalim’s approach is expressed in this phrase: “Let the producer take responsibility for sustaining the consumer’s life and the consumer for sustaining the producer’s livelihood”.<span class="citation" data-cites="Hansalim2021-tf"><a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></span> However, this mutual responsibility is about much more than simply direct sales as it also encompasses a shared commitment to protecting and restoring ecosystems and working for wider social and cultural change towards justice and peace.</p>
<p>This expansive goal is captured by the name itself: “Hansalim” (한살림). The first part of the word, ‘Han’ (한) contains two sets of paradoxical meanings. It expresses, firstly, a paradoxical double sense of being collectively one and individually one and, secondly, of spreading out as one and gathering in as one.<span class="citation" data-cites="Hansalim2021-cy"><a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></span> In ancient Korean philosophy ‘Han’ refers to the divine Spirit or life of the universe which permeates all things living and inanimate and integrates the universe into an evolving cosmos.</p>
<p>The word ‘Salim’ (살림) has two related meanings. The first is ‘housekeeping’ which implies parental care, homemaking, food preparation, hospitality. It is perhaps the most practical of all human activities and is the bedrock of human survival and flourishing. The second meaning develops from this practical sense the philosophical concept of ‘nurturing’ which has the connotation of saving and restoring, bringing back to life, vivifying.<span class="citation" data-cites="Yoon2004-dl"><a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></span></p>
<p>So we see that the word ‘Hansalim’ expresses a relationship and an action. It encompasses the goal of nurturing or reviving all things, that is bringing all into a flourishing shared life together. In fact, the word ‘Hansalim’ is often used as a verb as when members encourage each other by saying “let’s Hansalim!”</p>
<p>Among Hansalim members, the word “Salim” is used to express their purpose in all their activities. So the collective mission of Hansalim is summed up in four phrases that each incorporate this word Salim.</p>
<p>The first, ‘Nurturing Food’ (밥상살림 — bapsang-salim) refers to the goal of providing consumers with safe, healthy, eco-friendly food and other household goods and this defines the responsibility that producers adopt for the life of consumers. The word in Korean directly translates as nurturing the dining table and the significance of this is that it refers to the act of sharing a meal, not simply consuming food. Second, ‘Nurturing Agriculture’ (농업살림 — nongup-salim) refers to the goal of securing stable and sustainable livelihoods for producers and this defines the responsibility which consumers adopt for the livelihoods of producers. Third, ‘Nurturing Life’ (생명살림 — saengmyeong-salim) expresses the responsibility of care for others (human and non-human) which producers and consumers together share and which is worked out through outward focused activities such as promoting eco-friendly farming, environmental campaigning, education, social welfare projects, and inward contemplative and reflective practices. Finally, ‘Nurturing Community’ (지역살림 — jiyeok-salim), emphasises the need to strengthen local community resources and relationships and to reach out to neighbours in need.</p>
<p>So how are these values put into practice? I’m going to tackle this question from bottom up, first from the rural or producer perspective and then from the urban or consumer perspective before describing the alternative economic system that brings them together.</p>
</section>
<section id="in-the-form-of-a-multistakeholder-cooperative" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="in-the-form-of-a-multistakeholder-cooperative"><span class="header-section-number">1.3</span> In the form of a multistakeholder cooperative</h2>
<p>The producer community is the smallest level of organization in Hansalim. In these communities farming is done together by a group of family farms who partner with one another to plan and coordinate their production, share knowledge and labour, and manage shared facilities and equipment. To join Hansalim as a producer, you would join one of these communities and receive training in eco-friendly farming and Hansalim’s production and processing standards.</p>
<p>There are 136 producer communities which cultivate a total of 11,300 acres. In addition to the producer communities there are 110 processing units which process raw materials from Hansalim’s producers as well as seafood and other products from local organic and environmentally friendly sources.<span class="citation" data-cites="Hansalim2024-zt"><a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></span> The producer organizations are brought together into 15 regional federations with their own elected representatives which together form Hansalim’s National Producer Federation with their own elected president and employed staff. Many of these regional federations pool resources to run local distribution hubs with their own processing facilities and some have created complex systems to process and re-circulate farm wastes as inputs between multiple local farms.</p>
<p>(map of producer communities)</p>
<div>

</div>
<div class="quarto-layout-panel" data-layout-nrow="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Byeonsan-Farm.jpeg" class="lightbox" data-gallery="producers" title="Hansalim Producer Community in Byeonsan"><img src="../images/chapter_01/Byeonsan-Farm.jpeg" class="img-fluid figure-img" alt="Hansalim Producer Community in Byeonsan"></a></p>
<figcaption>Hansalim Producer Community in Byeonsan</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Byeonsan-Producer-Community.jpeg" class="lightbox" data-gallery="producers" title="Byeonsan Producer Community shared facilities"><img src="../images/chapter_01/Byeonsan-Producer-Community.jpeg" class="img-fluid figure-img" alt="Byeonsan Producer Community shared facilities"></a></p>
<figcaption>Byeonsan Producer Community shared facilities</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Jeju-Producer-Community.jpeg" class="lightbox" data-gallery="producers" title="Hansalim Producer Community in Jeju, head office"><img src="../images/chapter_01/Jeju-Producer-Community.jpeg" class="img-fluid figure-img" alt="Hansalim Producer Community in Jeju, head office"></a></p>
<figcaption>Hansalim Producer Community in Jeju, head office</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Asan-Distribution-Centre.jpeg" class="lightbox" data-gallery="producers" title="Hansalim Producer Community in Asan, distribution hub"><img src="../images/chapter_01/Asan-Distribution-Centre.jpeg" class="img-fluid figure-img" alt="Hansalim Producer Community in Asan, distribution hub"></a></p>
<figcaption>Hansalim Producer Community in Asan, distribution hub</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>When you join Hansalim as a consumer you become a member of your local Life Cooperative (one among 27 as of 2024). The word “Life” is significant because these cooperatives are not like the conventional consumer cooperatives that you would encounter in Europe or America. Their focus is not only responsible consumption but also seeking to live together in solidarity with one another and with producers and rural communities. Each Life Cooperative in Hansalim is a democratic autonomous organization formed by members to carry out collective activities, set-up and run Hansalim stores, organize charitable, cultural and educational activities and the joint activities between rural producers and urban consumers.</p>
<p>(map of Life Coops)</p>
<div>

</div>
<div class="quarto-layout-panel" data-layout-nrow="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Jeju-Hansalim-Office.jpeg" class="lightbox" data-gallery="consumers" title="Jeju Hansalim Life Coop office"><img src="../images/chapter_01/Jeju-Hansalim-Office.jpeg" class="img-fluid figure-img" alt="Jeju Hansalim Life Coop office"></a></p>
<figcaption>Jeju Hansalim Life Coop office</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Jeju-Hansalim-Kitchen.jpeg" class="lightbox" data-gallery="consumers" title="Jeju Hansalim community kitchen"><img src="../images/chapter_01/Jeju-Hansalim-Kitchen.jpeg" class="img-fluid figure-img" alt="Jeju Hansalim community kitchen"></a></p>
<figcaption>Jeju Hansalim community kitchen</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Jeju-Hansalim-Community-Garden.jpeg" class="lightbox" data-gallery="consumers" title="Jeju Hansalim community permaculture garden"><img src="../images/chapter_01/Jeju-Hansalim-Community-Garden.jpeg" class="img-fluid figure-img" alt="Jeju Hansalim community permaculture garden"></a></p>
<figcaption>Jeju Hansalim community permaculture garden</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Busan-Hansalim-Kitchen.jpg" class="lightbox" data-gallery="consumers" title="Busan Hansalim community kitchen"><img src="../images/chapter_01/Busan-Hansalim-Kitchen.jpg" class="img-fluid figure-img" alt="Busan Hansalim community kitchen"></a></p>
<figcaption>Busan Hansalim community kitchen</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>Together, the producer communities and federations and the Life Coops form a federation of cooperatives, associations and businesses linked together through a shared business federation and the Hansalim Federation with its support organisations including a research institute, charitable foundation, solar power coop, publishing house, training institute and peer-to-peer finance platform. So how does this business work?</p>
</section>
<section id="creating-an-alternative-economy" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="creating-an-alternative-economy"><span class="header-section-number">1.4</span> Creating an alternative economy</h2>
<p>In simple terms, the Hansalim business model can be described as a contract-based direct sales arrangement in which prices and quantities are agreed annually in advance by producers and consumers with support from Hansalim’s employees. However, it is also very flexible in ways that are designed to support the needs of producers.</p>
<section id="a-system-designed-for-producers" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="a-system-designed-for-producers">A system designed for producers</h3>
<p>There are four key features of Hansalim’s business model. Firstly: flexibility of production. Hansalim’s production system allows for a relatively wide range of production philosophies and techniques among member producers to ensure that producers have maximum autonomy. For example, one producer community might prefer a relatively simple style of organic farming with a small number of crops while another aspires to build a complex system of circulating agriculture with a large diversity of crops and livestock supported by recycling of farm wastes from one part of the system as inputs to others. Still others, especially fruit producers, might find it impossible to grow without a limited use of home made natural pesticides. A dogmatic insistence on a single farming philosophy would exclude many farmers who might be unable to follow a one-size-fits-all system in the face of local conditions or other resource constraints. Hansalim’s more flexible approach removes a significant barrier to entry for farmers who would otherwise need to spend a long time learning new techniques before starting to earn an income. This brings the added advantage that farmers who want to transition from conventional to organic farming can do so in a staged process while still making a living. However, it also creates a problem. How to maintain the trust of consumers when the diversity of production techniques is so wide?</p>
<p>This brings us to the second feature of Hansalim’s business model: simple and honest labeling. Transparency with consumer members is ensured through Hansalim’s own labelling system. Products are labelled under four main categories:</p>
<ol type="1">
<li>Organic (which would include conventional organic, permaculture and EM techniques);</li>
<li>Pesticide-free (when crop types and local conditions make it non-viable to exclude use of fertilizers);</li>
<li>Low pesticide (for certain fruit crops which would be prohibitively difficult to grow without a limited use of pesticides);</li>
<li>Domestic (for miscellaneous grains such as barley or black bean which are used as raw ingredients in some processed goods and feed for livestock).</li>
</ol>
<p>For all four categories Hansalim’s standards are stricter than the national safety standards and products are tested regularly for residues, contaminants and radiation as appropriate to protect trust between consumers and producers.</p>
<p>To complement the flexibility and transparency of production methods the third feature - flexibility of supply - enhances the autonomy of producers and provides some added resilience to the system. Hansalim producers are not locked-in to exclusive supply contracts but have the freedom to supply whatever proportion of their crop to Hansalim they wish while simultaneously supplying through other channels such as government purchasing schemes for school meals. This applies to each producer community and also to each member of each community. So one farmer might supply 30% of their produce to Hansalim through their community while selling the rest through local government procurement for school meals. Or a producer community might sell Hansalim branded grapes through the Hansalim Federation while selling grape juice through another market under their own brand.</p>
<p>Finally, for an additional level of flexibility, the contract-based system is supplemented by demand-based supply arrangements to allow greater flexibility for producers.</p>
<p>Taken together, these four features of Hansalim’s business model mean that, within and between producer communities the level of specialization or circular integration and the combination of sales channels are all decided by the producers themselves. This makes for an astonishingly diverse range of production operations each tailored to the local soil and climate conditions and preferences of producers themselves, while ensuring a stable guaranteed income to as many farmers as possible.</p>
<div>

</div>
<div class="quarto-layout-panel" data-layout-nrow="7">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Our-Seed-Farm-Rice-Hansalim.jpeg" class="lightbox" data-gallery="farms" title="The word ‘Hansalim’ written in life alongside a rice paddy on Our Seed Farm in Goesan"><img src="../images/chapter_01/Our-Seed-Farm-Rice-Hansalim.jpeg" class="img-fluid figure-img" alt="The word ‘Hansalim’ written in life alongside a rice paddy on Our Seed Farm in Goesan"></a></p>
<figcaption>The word ‘Hansalim’ written in life alongside a rice paddy on Our Seed Farm in Goesan</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Our-Seed-Farm-Rice-Terrace.jpeg" class="lightbox" data-gallery="farms" title="Rice terraces on Our Seed Farm in Goesan"><img src="../images/chapter_01/Our-Seed-Farm-Rice-Terrace.jpeg" class="img-fluid figure-img" alt="Rice terraces on Our Seed Farm in Goesan"></a></p>
<figcaption>Rice terraces on Our Seed Farm in Goesan</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Rice-Field.jpeg" class="lightbox" data-gallery="farms" title="A lowland rice paddy"><img src="../images/chapter_01/Rice-Field.jpeg" class="img-fluid figure-img" alt="A lowland rice paddy"></a></p>
<figcaption>A lowland rice paddy</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Paju-Rice-Planting.jpeg" class="lightbox" data-gallery="farms" title="Planting out rice seedlings with a Hansalim producer community in Paju"><img src="../images/chapter_01/Paju-Rice-Planting.jpeg" class="img-fluid figure-img" alt="Planting out rice seedlings with a Hansalim producer community in Paju"></a></p>
<figcaption>Planting out rice seedlings with a Hansalim producer community in Paju</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Our-Seed-Farm-Greenhouse-1.jpeg" class="lightbox" data-gallery="farms" title="Vinyl house (polytunnel greenhouse) crops at Our Seed Farm in Goesan"><img src="../images/chapter_01/Our-Seed-Farm-Greenhouse-1.jpeg" class="img-fluid figure-img" alt="Vinyl house (polytunnel greenhouse) crops at Our Seed Farm in Goesan"></a></p>
<figcaption>Vinyl house (polytunnel greenhouse) crops at Our Seed Farm in Goesan</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Okcheon-Grapes.jpeg" class="lightbox" data-gallery="farms" title="Grapes growing in a vinyl house at a Hansalim producer community in Okcheon"><img src="../images/chapter_01/Okcheon-Grapes.jpeg" class="img-fluid figure-img" alt="Grapes growing in a vinyl house at a Hansalim producer community in Okcheon"></a></p>
<figcaption>Grapes growing in a vinyl house at a Hansalim producer community in Okcheon</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Nunbisan-Vegetables.jpeg" class="lightbox" data-gallery="farms" title="A vegetable field at Nunbisan, a Hansalim producer community in Goesan"><img src="../images/chapter_01/Nunbisan-Vegetables.jpeg" class="img-fluid figure-img" alt="A vegetable field at Nunbisan, a Hansalim producer community in Goesan"></a></p>
<figcaption>A vegetable field at Nunbisan, a Hansalim producer community in Goesan</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Nunbisan-Oats.jpeg" class="lightbox" data-gallery="farms" title="A field of oats at Nunbisan grown for chicken feed and as an ingredient for making various types of Hansalim products that are processed on site"><img src="../images/chapter_01/Nunbisan-Oats.jpeg" class="img-fluid figure-img" alt="A field of oats at Nunbisan grown for chicken feed and as an ingredient for making various types of Hansalim products that are processed on site"></a></p>
<figcaption>A field of oats at Nunbisan grown for chicken feed and as an ingredient for making various types of Hansalim products that are processed on site</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Nunbisan-Homemade-Fertilizer.jpeg" class="lightbox" data-gallery="farms" title="Making home made organic fertilizer from Chicken faeces and crop waste on Nunbisan farm"><img src="../images/chapter_01/Nunbisan-Homemade-Fertilizer.jpeg" class="img-fluid figure-img" alt="Making home made organic fertilizer from Chicken faeces and crop waste on Nunbisan farm"></a></p>
<figcaption>Making home made organic fertilizer from Chicken faeces and crop waste on Nunbisan farm</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Nunbisan-Field-2.jpeg" class="lightbox" data-gallery="farms" title="A green manure cover crop at Nunbisan"><img src="../images/chapter_01/Nunbisan-Field-2.jpeg" class="img-fluid figure-img" alt="A green manure cover crop at Nunbisan"></a></p>
<figcaption>A green manure cover crop at Nunbisan</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Nunbisan-Chicken-Sheds-2.jpeg" class="lightbox" data-gallery="farms" title="Chicken sheds on Nunbisan farm"><img src="../images/chapter_01/Nunbisan-Chicken-Sheds-2.jpeg" class="img-fluid figure-img" alt="Chicken sheds on Nunbisan farm"></a></p>
<figcaption>Chicken sheds on Nunbisan farm</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Nunbisan-Chicken-Sheds-3.jpeg" class="lightbox" data-gallery="farms" title="Inside Nunbisan’s chicken sheds"><img src="../images/chapter_01/Nunbisan-Chicken-Sheds-3.jpeg" class="img-fluid figure-img" alt="Inside Nunbisan’s chicken sheds"></a></p>
<figcaption>Inside Nunbisan’s chicken sheds</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Mushrooms.jpeg" class="lightbox" data-gallery="farms" title="Growing mushrooms on a Hansalim farm"><img src="../images/chapter_01/Mushrooms.jpeg" class="img-fluid figure-img" alt="Growing mushrooms on a Hansalim farm"></a></p>
<figcaption>Growing mushrooms on a Hansalim farm</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Jeju-Orchard.jpeg" class="lightbox" data-gallery="farms" title="An orchard on a Hansalim farm on Jeju Island"><img src="../images/chapter_01/Jeju-Orchard.jpeg" class="img-fluid figure-img" alt="An orchard on a Hansalim farm on Jeju Island"></a></p>
<figcaption>An orchard on a Hansalim farm on Jeju Island</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Byeonsan-Field-1.jpeg" class="lightbox" data-gallery="farms" title="Lowland farming at the foot of a mountain in Byeonsan at the Sandle-pada Hansalim Producer Community"><img src="../images/chapter_01/Byeonsan-Field-1.jpeg" class="img-fluid figure-img" alt="Lowland farming at the foot of a mountain in Byeonsan at the Sandle-pada Hansalim Producer Community"></a></p>
<figcaption>Lowland farming at the foot of a mountain in Byeonsan at the Sandle-pada Hansalim Producer Community</figcaption>
</figure>
</div>
<p>These images show just a tiny snapshot of some of the different farming landscapes, crops and approaches which form Hansalim’s complex agricultural systems. The system of labelling helps provide a sense of order to this complexity for the sake of Hansalim’s consumer members and also facilitates the progression of Hansalim producers further away from conventional farming methods towards progressively more eco-friendly alternatives. Let’s look at the overall share of production according to production type, crop type and supply type. The following graph, <a href="#fig-productionflow" class="quarto-xref">Figure&nbsp;<span>1.1</span></a>, shows the flow of goods by tons.</p>
<div id="fig-productionflow" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-productionflow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell">
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item" id="htmlwidget-a57d67927950f5c203b2" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-a57d67927950f5c203b2">{"x":{"visdat":{"47613bd579e3":["function () ","plotlyVisDat"]},"cur_data":"47613bd579e3","attrs":{"47613bd579e3":{"orientation":"h","node":{"label":["Organic","Pesticide-free","Low-pesticide","Domestic","Staple grains","Misc grains","Roots and Tubers","Vegetables","Fruit","Contract","Demand"],"color":["darkgreen","green","lightgreen","aquamarine","brown","darkorange","yellow","green","red","darkgrey","lightgrey"],"pad":15,"thickness":20,"line":{"color":"black","width":0.5}},"link":{"source":[0,1,2,3,0,1,2,3,0,1,2,3,0,1,2,3,0,1,2,3,4,4,5,5,6,6,7,7,8,8],"target":[4,4,4,4,5,5,5,5,6,6,6,6,7,7,7,7,8,8,8,8,9,10,9,10,9,10,9,10,9,10],"value":[4930,509,0,0,661,783,0,1748,697,292,0,0,8336,2408,0,0,1393,498,2139,0,5439,0,271,2921,989,0,10090,654,3898,132]},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"sankey"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"","font":{"size":12},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"orientation":"h","node":{"label":["Organic","Pesticide-free","Low-pesticide","Domestic","Staple grains","Misc grains","Roots and Tubers","Vegetables","Fruit","Contract","Demand"],"color":["darkgreen","green","lightgreen","aquamarine","brown","darkorange","yellow","green","red","darkgrey","lightgrey"],"pad":15,"thickness":20,"line":{"color":"black","width":0.5}},"link":{"source":[0,1,2,3,0,1,2,3,0,1,2,3,0,1,2,3,0,1,2,3,4,4,5,5,6,6,7,7,8,8],"target":[4,4,4,4,5,5,5,5,6,6,6,6,7,7,7,7,8,8,8,8,9,10,9,10,9,10,9,10,9,10],"value":[4930,509,0,0,661,783,0,1748,697,292,0,0,8336,2408,0,0,1393,498,2139,0,5439,0,271,2921,989,0,10090,654,3898,132]},"type":"sankey","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-productionflow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.1: Flow of production quantities by type, crop and contract in 2023 (tons).
</figcaption>
</figure>
</div>
<p>On the left you can see the four labelled production types of <strong><em>organic</em></strong>, <strong><em>pesticide-free</em></strong>, <strong><em>low-pesticide</em></strong> and <strong><em>domestic</em></strong>. In the centre, the crop types are divided into <strong><em>vegetables</em></strong>, <strong><em>staple grains</em></strong>, <strong><em>roots and tubers</em></strong>, <strong><em>fruit</em></strong>, and <strong><em>miscellaneous grains</em></strong>. On the right, crop types are categorized into supply type as either <strong><em>contract-based</em></strong> or <strong><em>demand-based</em></strong> supply. <span>If you interact with the graph you can see the number of tons of each combination.</span> The majority of production is organic and this accounts for most of the vegetable cultivation, almost all staple grains and root and tubers. These crop types are almost entirely supplied on a contract-basis. Pesticide-free production accounts for some vegetable supply, a fraction of staple grains and some fruit crops. It is in fruit cultivation that higher proportion of crops are cultivated according to ‘low-pesticide’ standards. This is because many fruit crops are especially vulnerable to pests and would no be viable for producers without some use of non-synthetic pesticides. Miscellaneous grains are mostly produced under the domestic label and supplied on a demand-basis.</p>
<p>So what happens to the revenue from these sales? As I mentioned above, until recently, with margins well below 30%, Hansalim was able to return 73% or more of the product price to the producers. Now, following several years of rising costs and worsening impacts of climate change the margin has come under increasing pressure and currently stands at just over 31% which leaves almost 69% for producers. This table in <a href="#fig-margin" class="quarto-xref">Figure&nbsp;<span>1.2</span></a> shows the breakdown of what the margin covers.</p>
<div id="fig-margin" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-margin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Division</th>
<th data-quarto-table-cell-role="th">Rate</th>
<th data-quarto-table-cell-role="th">Subdivision</th>
<th data-quarto-table-cell-role="th">Rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td rowspan="2">Hansalim Federation</td>
<td rowspan="2">0.81%</td>
<td>Subscription fees</td>
<td>0.55%</td>
</tr>
<tr class="even">
<td>Service revenue</td>
<td>0.26%</td>
</tr>
<tr class="odd">
<td rowspan="3">Hansalim Business Federation</td>
<td rowspan="3">8.86%</td>
<td>Business share rate</td>
<td>8.61%</td>
</tr>
<tr class="even">
<td>Production support fund</td>
<td>0.165%</td>
</tr>
<tr class="odd">
<td>Price stabilization fund</td>
<td>0.085%</td>
</tr>
<tr class="even">
<td rowspan="2">Member Life Coops</td>
<td rowspan="2">21.7%</td>
<td>Regional margin rate</td>
<td>21.6%</td>
</tr>
<tr class="odd">
<td>Production stabilization fund</td>
<td>0.1%</td>
</tr>
<tr class="even">
<td>Gross margin rate (GPR)</td>
<td colspan="3">31.37%</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-margin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.2: The breakdown of Hansalim’s margin in 2023.
</figcaption>
</figure>
</div>
<p>That is virtually the reverse of conventional market distribution which usually takes a 50 - 70% margin. So what does this distribution of revenue look like from the point of view of the Life Coops, producers and the federal organisations? The following chart, <a href="#fig-valueflow" class="quarto-xref">Figure&nbsp;<span>1.3</span></a>, shows the flow of value (in euros) from the sales of goods (on the left) through each Life Coop (center) to the share of revenue provided to each category of organization (right).</p>
<div id="fig-valueflow" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-valueflow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell">
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item" id="htmlwidget-999fb5bc594f7ec32ae5" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-999fb5bc594f7ec32ae5">{"x":{"visdat":{"4761205efb8f":["function () ","plotlyVisDat"]},"cur_data":"4761205efb8f","attrs":{"4761205efb8f":{"orientation":"h","node":{"label":["Local Goods","Federation Goods","Seoul East","Seoul West","Seoul South","Seoul North","Gyeongin","Goyangpaju","Gyeonggi South","Suwon","Seongnam Yongin","Gyeonggi Southwest","Gyeonggi East","Wonju","Chuncheon","Gangwon Yeongdong","Cheongju","Daejeon","Cheonan Asan","Chungju Jaejeon","Jeonbuk","Gwangju","Jeolla South","Jeju","Gyeongbuk North","Ulsan","Gyeongnam","Dae-gu","Busan","Producer Share","Life Coop Share","Business Federation Share","Hansalim Federation Share"],"color":["darkgreen","lightgreen","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","darkblue","blue","lightblue","pink"],"pad":15,"thickness":20,"line":{"color":"black","width":0.5}},"link":{"source":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28],"target":[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32],"value":[697939.09499999997,713999.05499999993,580166.05499999993,449009.71499999997,0,525963.68999999994,329898.34499999997,271011.82500000001,967612.58999999997,148554.63,12714.134999999998,55540.695,31450.754999999997,125133.855,199411.16999999998,614293.46999999997,24089.939999999999,95690.595000000001,151900.45499999999,187366.19999999998,54202.364999999998,469753.82999999996,34796.580000000002,557414.44499999995,3279577.665,165952.91999999998,2809823.835,31763924.219999999,32099845.049999997,28919303.805,31245321.344999999,8706505.8149999995,17391598.349999998,16885709.609999999,7638518.4749999996,28703163.509999998,7138652.2199999997,6607335.21,4180273.7549999999,2782388.0699999998,6498930.4799999995,8147083.875,11351045.895,9116034.7949999999,2738892.3449999997,4372324.1099999994,4130755.5449999999,3646280.085,5582843.5949999997,2902837.77,2149357.98,11016463.395,5566114.4699999997,4488758.8199999994,22353596.145153001,22596792.654765002,20308438.932957001,21802637.804072998,5977283.1719159996,12351770.10753,11850936.641438998,5456274.3810749995,20463416.074793998,5052341.0926379999,4546075.8804089995,2913336.8350169999,1934767.604973,4559675.4545369996,5749351.9219499994,8273862.0022379998,6277310.5266479999,1955209.2573929999,3120628.6273889998,2982556.1994479997,2545683.397719,4200585.0540779997,2020080.119988,1911999.667347,10131071.242383,3951228.7468079994,5281727.5088129994,7044224.3393550003,7120604.1707849996,6401384.9596199989,6877669.8400199991,1889311.7618549999,3888110.9626799999,3735786.9262349997,1716368.0751,6438558.4137000004,1581323.8864499999,1436550.707865,919171.73564999993,610603.02502499998,1437421.9606949999,1811189.4247649999,2596478.6422049999,1983407.0674950001,615104.49797999999,981756.73060499993,937032.41866499989,803004.69164999994,1313413.6412249999,637466.65394999995,587369.61622500001,3102240.9100199998,1243858.6236299998,1583792.4361349999,2814283.6858919994,2844046.2714299997,2562250.3171229996,2768335.4711669995,771396.41520899988,1540895.6138099998,1496073.8714459999,676772.73688500002,2543100.2869859999,632484.58669199992,585409.89960599993,370372.254693,246519.58300199997,575805.24052799994,721831.63132499997,1005702.666297,807680.682837,242665.86176699997,387387.91614600003,365984.94128700002,323060.41553100001,494639.94251699996,257191.42642199996,190433.11702799998,976058.65679699986,493157.74204199994,397704.03145199997,249759.1446,252401.00801999998,227395.65029999998,245687.94473999998,68514.466019999993,136785.35597999999,132810.51587999999,60115.106939999998,225701.32451999999,21057.284219999998,52012.857119999993,32933.624640000002,21948.611999999997,51161.679239999998,64122.066959999996,89296.05425999999,71726.458019999991,21603.322859999997,34451.290860000001,32548.185599999997,28733.945099999997,43958.787179999992,22896.14964,16970.024399999998,86670.250800000009,43822.277519999996,35358.678599999999]},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"sankey"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"","font":{"size":12},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"orientation":"h","node":{"label":["Local Goods","Federation Goods","Seoul East","Seoul West","Seoul South","Seoul North","Gyeongin","Goyangpaju","Gyeonggi South","Suwon","Seongnam Yongin","Gyeonggi Southwest","Gyeonggi East","Wonju","Chuncheon","Gangwon Yeongdong","Cheongju","Daejeon","Cheonan Asan","Chungju Jaejeon","Jeonbuk","Gwangju","Jeolla South","Jeju","Gyeongbuk North","Ulsan","Gyeongnam","Dae-gu","Busan","Producer Share","Life Coop Share","Business Federation Share","Hansalim Federation Share"],"color":["darkgreen","lightgreen","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","darkblue","blue","lightblue","pink"],"pad":15,"thickness":20,"line":{"color":"black","width":0.5}},"link":{"source":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28],"target":[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32],"value":[697939.09499999997,713999.05499999993,580166.05499999993,449009.71499999997,0,525963.68999999994,329898.34499999997,271011.82500000001,967612.58999999997,148554.63,12714.134999999998,55540.695,31450.754999999997,125133.855,199411.16999999998,614293.46999999997,24089.939999999999,95690.595000000001,151900.45499999999,187366.19999999998,54202.364999999998,469753.82999999996,34796.580000000002,557414.44499999995,3279577.665,165952.91999999998,2809823.835,31763924.219999999,32099845.049999997,28919303.805,31245321.344999999,8706505.8149999995,17391598.349999998,16885709.609999999,7638518.4749999996,28703163.509999998,7138652.2199999997,6607335.21,4180273.7549999999,2782388.0699999998,6498930.4799999995,8147083.875,11351045.895,9116034.7949999999,2738892.3449999997,4372324.1099999994,4130755.5449999999,3646280.085,5582843.5949999997,2902837.77,2149357.98,11016463.395,5566114.4699999997,4488758.8199999994,22353596.145153001,22596792.654765002,20308438.932957001,21802637.804072998,5977283.1719159996,12351770.10753,11850936.641438998,5456274.3810749995,20463416.074793998,5052341.0926379999,4546075.8804089995,2913336.8350169999,1934767.604973,4559675.4545369996,5749351.9219499994,8273862.0022379998,6277310.5266479999,1955209.2573929999,3120628.6273889998,2982556.1994479997,2545683.397719,4200585.0540779997,2020080.119988,1911999.667347,10131071.242383,3951228.7468079994,5281727.5088129994,7044224.3393550003,7120604.1707849996,6401384.9596199989,6877669.8400199991,1889311.7618549999,3888110.9626799999,3735786.9262349997,1716368.0751,6438558.4137000004,1581323.8864499999,1436550.707865,919171.73564999993,610603.02502499998,1437421.9606949999,1811189.4247649999,2596478.6422049999,1983407.0674950001,615104.49797999999,981756.73060499993,937032.41866499989,803004.69164999994,1313413.6412249999,637466.65394999995,587369.61622500001,3102240.9100199998,1243858.6236299998,1583792.4361349999,2814283.6858919994,2844046.2714299997,2562250.3171229996,2768335.4711669995,771396.41520899988,1540895.6138099998,1496073.8714459999,676772.73688500002,2543100.2869859999,632484.58669199992,585409.89960599993,370372.254693,246519.58300199997,575805.24052799994,721831.63132499997,1005702.666297,807680.682837,242665.86176699997,387387.91614600003,365984.94128700002,323060.41553100001,494639.94251699996,257191.42642199996,190433.11702799998,976058.65679699986,493157.74204199994,397704.03145199997,249759.1446,252401.00801999998,227395.65029999998,245687.94473999998,68514.466019999993,136785.35597999999,132810.51587999999,60115.106939999998,225701.32451999999,21057.284219999998,52012.857119999993,32933.624640000002,21948.611999999997,51161.679239999998,64122.066959999996,89296.05425999999,71726.458019999991,21603.322859999997,34451.290860000001,32548.185599999997,28733.945099999997,43958.787179999992,22896.14964,16970.024399999998,86670.250800000009,43822.277519999996,35358.678599999999]},"type":"sankey","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-valueflow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.3: Flow of value from sales revenue through each Life Coop to other organizations (euros).
</figcaption>
</figure>
</div>
<p>You will notice that the vast majority of sales are of ‘federation goods’ which are those supplied through the business federation’s distribution channels. A much smaller percentage of sales are accounted for by so-called ‘local goods’ which are supplied independently from Hansalim’s central distribution system. The central column of the chart looks a bit messy, but the point is that the majority of sales are through shops managed by the Life Coops in Seoul and Gyeonggi (the province surrounding Seoul) which together form the largest and densest population centre in Korea. On the right hand side you can see that the share of revenue returned to producers is by far the largest, while the margin covers the budgets of the Life Coops and finally the Business Federation and the Hansalim Federation.</p>
<p>This distribution revenue is achieved through a combination of:</p>
<ol type="1">
<li>Recovered costs from distribution by removing the multiple opportunities from profit gauging by intermediaries;</li>
<li>Prices set to reflect the true costs of production; and</li>
<li>Economies of scope and scale achieved through shared business activities and collectively owned capital at local, regional and national levels.</li>
</ol>
<p>After providing for producers’ livelihoods, what then does the remaining 30% pay for?</p>
</section>
<section id="a-different-kind-of-consumer-experience" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="a-different-kind-of-consumer-experience">A different kind of consumer experience</h3>
<p>The largest portion (21.7%) goes to the Life Coops themselves to cover the costs of running stores, handling local distribution and their various educational, participation and engagement activities. Life Coops are autonomous member owned businesses which run the Hansalim stores in their local areas. They decide when and where to open new stores, how to manage them and how to organize local distribution options such as home delivery. Stores are usually run by an employed manager and the Life Coop’s Store Activists (consumer members who are trained and paid to staff the stores) and products are ordered through the Hansalim Business Federation and delivered from their national logistics centre.</p>
<div>

</div>
<div class="quarto-layout-panel" data-layout-nrow="3">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Yangju-store.jpeg" class="lightbox" data-gallery="stores" title="North Seoul Hansalim, Yangju Store (2024)"><img src="../images/chapter_01/Yangju-store.jpeg" class="img-fluid figure-img" alt="North Seoul Hansalim, Yangju Store (2024)"></a></p>
<figcaption>North Seoul Hansalim, Yangju Store (2024)</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Ssangmoon-Store.jpeg" class="lightbox" data-gallery="stores" title="North Seoul Hansalim, Ssangmoon Store with home delivery vehicle"><img src="../images/chapter_01/Ssangmoon-Store.jpeg" class="img-fluid figure-img" alt="North Seoul Hansalim, Ssangmoon Store with home delivery vehicle"></a></p>
<figcaption>North Seoul Hansalim, Ssangmoon Store with home delivery vehicle</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Hansalim-Store-Interior.jpeg" class="lightbox" data-gallery="stores" title="Inside a Hansalim Store"><img src="../images/chapter_01/Hansalim-Store-Interior.jpeg" class="img-fluid figure-img" alt="Inside a Hansalim Store"></a></p>
<figcaption>Inside a Hansalim Store</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Hansalim-Store-Interior-Wide.jpeg" class="lightbox" data-gallery="stores" title="A wide-angle view inside a Hansalim Store"><img src="../images/chapter_01/Hansalim-Store-Interior-Wide.jpeg" class="img-fluid figure-img" alt="A wide-angle view inside a Hansalim Store"></a></p>
<figcaption>A wide-angle view inside a Hansalim Store</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Hansalim-Jeju-Store-1.jpeg" class="lightbox" data-gallery="stores" title="Hansalim Store and Food Culture Center at Jeju head office"><img src="../images/chapter_01/Hansalim-Jeju-Store-1.jpeg" class="img-fluid figure-img" alt="Hansalim Store and Food Culture Center at Jeju head office"></a></p>
<figcaption>Hansalim Store and Food Culture Center at Jeju head office</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Hansalim-Jeju-Store-2.jpeg" class="lightbox" data-gallery="stores" title="Inside the store at the Jeju Hansalim head office"><img src="../images/chapter_01/Hansalim-Jeju-Store-2.jpeg" class="img-fluid figure-img" alt="Inside the store at the Jeju Hansalim head office"></a></p>
<figcaption>Inside the store at the Jeju Hansalim head office</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>In a Hansalim store you can buy virtually everything you need from food to household goods and even cosmetics. Almost all these products are made by Hansalim producers and processors with a few exceptions for some household items and a handful of fair trade products. Hansalim branded sales through the business federation are supplemented by local goods sourced by each store according to the decision of each Life Coop. What this means is that there is usually just one type of everything you need rather than multiple brands of the same product so the shop size is relatively small compared to a regular supermarket. Here are a few examples of the products that are available in my local Hansalim store.</p>
<div>

</div>
<div class="quarto-layout-panel" data-layout-nrow="7">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Rice.jpeg" class="lightbox" data-gallery="products" title="Hansalim Rice"><img src="../images/chapter_01/Products-Rice.jpeg" class="img-fluid figure-img" alt="Hansalim Rice"></a></p>
<figcaption>Hansalim Rice</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Sweet-Potatoes.jpeg" class="lightbox" data-gallery="products" title="Sweet potatoes"><img src="../images/chapter_01/Products-Sweet-Potatoes.jpeg" class="img-fluid figure-img" alt="Sweet potatoes"></a></p>
<figcaption>Sweet potatoes</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Fruit-Veg.jpeg" class="lightbox" data-gallery="products" title="Fruit and vegetables"><img src="../images/chapter_01/Products-Fruit-Veg.jpeg" class="img-fluid figure-img" alt="Fruit and vegetables"></a></p>
<figcaption>Fruit and vegetables</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Tofu-etc.jpeg" class="lightbox" data-gallery="products" title="Tofu and other ingredients for cooking"><img src="../images/chapter_01/Products-Tofu-etc.jpeg" class="img-fluid figure-img" alt="Tofu and other ingredients for cooking"></a></p>
<figcaption>Tofu and other ingredients for cooking</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Chilled-Goods.jpeg" class="lightbox" data-gallery="products" title="Dairy products and other chilled processed goods"><img src="../images/chapter_01/Products-Chilled-Goods.jpeg" class="img-fluid figure-img" alt="Dairy products and other chilled processed goods"></a></p>
<figcaption>Dairy products and other chilled processed goods</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Cereals.jpeg" class="lightbox" data-gallery="products" title="Breakfast cereals and flour etc."><img src="../images/chapter_01/Products-Cereals.jpeg" class="img-fluid figure-img" alt="Breakfast cereals and flour etc."></a></p>
<figcaption>Breakfast cereals and flour etc.</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Frozen-Meats.jpeg" class="lightbox" data-gallery="products" title="Frozen meats"><img src="../images/chapter_01/Products-Frozen-Meats.jpeg" class="img-fluid figure-img" alt="Frozen meats"></a></p>
<figcaption>Frozen meats</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Bottled.jpeg" class="lightbox" data-gallery="products" title="Bottled juice, preserves and other ingredients in jars"><img src="../images/chapter_01/Products-Bottled.jpeg" class="img-fluid figure-img" alt="Bottled juice, preserves and other ingredients in jars"></a></p>
<figcaption>Bottled juice, preserves and other ingredients in jars</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Kimchi-Cabbages.jpeg" class="lightbox" data-gallery="products" title="Cabbages for making Kimchi (these are distributed over a period of a week or two each November in time for ‘Kimjang’ when families and communities gather to make Kimchi together)"><img src="../images/chapter_01/Products-Kimchi-Cabbages.jpeg" class="img-fluid figure-img" alt="Cabbages for making Kimchi (these are distributed over a period of a week or two each November in time for ‘Kimjang’ when families and communities gather to make Kimchi together)"></a></p>
<figcaption>Cabbages for making Kimchi (these are distributed over a period of a week or two each November in time for ‘Kimjang’ when families and communities gather to make Kimchi together)</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Ready-Meals.jpeg" class="lightbox" data-gallery="products" title="Ready meals! Frozen foods."><img src="../images/chapter_01/Products-Ready-Meals.jpeg" class="img-fluid figure-img" alt="Ready meals! Frozen foods."></a></p>
<figcaption>Ready meals! Frozen foods.</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Rice-Wine.jpeg" class="lightbox" data-gallery="products" title="One of my favourites, traditionally made rice wine"><img src="../images/chapter_01/Products-Rice-Wine.jpeg" class="img-fluid figure-img" alt="One of my favourites, traditionally made rice wine"></a></p>
<figcaption>One of my favourites, traditionally made rice wine</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Cosmetics.jpeg" class="lightbox" data-gallery="products" title="You can even by cosmetics made by Hansalim with eco-friendly natural ingredients"><img src="../images/chapter_01/Products-Cosmetics.jpeg" class="img-fluid figure-img" alt="You can even by cosmetics made by Hansalim with eco-friendly natural ingredients"></a></p>
<figcaption>You can even by cosmetics made by Hansalim with eco-friendly natural ingredients</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Cleaning.jpeg" class="lightbox" data-gallery="products" title="Household cleaning products are also available including toilet paper and kitchen paper made in Hansalim’s Anseong logistics centre from recycled milk and drinks cartons"><img src="../images/chapter_01/Products-Cleaning.jpeg" class="img-fluid figure-img" alt="Household cleaning products are also available including toilet paper and kitchen paper made in Hansalim’s Anseong logistics centre from recycled milk and drinks cartons"></a></p>
<figcaption>Household cleaning products are also available including toilet paper and kitchen paper made in Hansalim’s Anseong logistics centre from recycled milk and drinks cartons</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Olive-Oil.jpeg" class="lightbox" data-gallery="quarto-lightbox-gallery-45" title="There are a small number of Fair Trade goods from select partners in other countries such as Olive Oil and chocolate"><img src="../images/chapter_01/Products-Olive-Oil.jpeg" class="img-fluid figure-img" alt="There are a small number of Fair Trade goods from select partners in other countries such as Olive Oil and chocolate"></a></p>
<figcaption>There are a small number of Fair Trade goods from select partners in other countries such as Olive Oil and chocolate</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>Hansalim stores also differ from a conventional supermarket in another way. They often provide the venue for member activities and encounters between consumers and producers facilitated by the Life Coop’s Organizing Activists (members who are trained and paid to organize opportunities for consumers and producers to meet each other and share food and other activities together). From the beginning of Hansalim, relationship building among consumers and between consumers and producers has been a top priority.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Hansalim-Store-Activity-Room.jpeg" class="lightbox" data-gallery="stores" title="An activity room inside a Hansalim Store showing the small kitchen, library and meeting space"><img src="../images/chapter_01/Hansalim-Store-Activity-Room.jpeg" class="img-fluid figure-img" alt="An activity room inside a Hansalim Store showing the small kitchen, library and meeting space"></a></p>
<figcaption>An activity room inside a Hansalim Store showing the small kitchen, library and meeting space</figcaption>
</figure>
</div>
<p>There are various ways consumers can build community together and participate in the livelihoods of producers. Neighbourhood meetings and small groups provide a context for consumer members to learn and build relationships through reading groups, cooking classes, social activities, and environmental activism etc. ‘Helping hands’ visits are organized by Activists to bring members to help producers with farming activities such as planting, weeding and harvest and to join in with traditional rural rituals and share meals together. Community work is also an important shared activity in which members and producers raise money for charitable causes, donate food to people in need and provide education and support to marginalized groups. Consumers often visit the producer communities for local festivals or just to see the farm, share a meal and get to know each other. Producers also visit stores to introduce their new products and many develop special relationships with particular Life Coops as well as participating in Hansalim conferences and multistakeholder committees.</p>
<div>

</div>
<div class="quarto-layout-panel" data-layout-nrow="6">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Activity-Farm-Visit-1.jpeg" class="lightbox" data-gallery="activities" title="A visit to Nunbisan farm by Life Coop members"><img src="../images/chapter_01/Activity-Farm-Visit-1.jpeg" class="img-fluid figure-img" alt="A visit to Nunbisan farm by Life Coop members"></a></p>
<figcaption>A visit to Nunbisan farm by Life Coop members</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Activity-Sharing-Meal.jpeg" class="lightbox" data-gallery="activities" title="Sharing a meal during the visit to Nunbisan"><img src="../images/chapter_01/Activity-Sharing-Meal.jpeg" class="img-fluid figure-img" alt="Sharing a meal during the visit to Nunbisan"></a></p>
<figcaption>Sharing a meal during the visit to Nunbisan</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Activity-Farm-Visit-2jpeg.jpeg" class="lightbox" data-gallery="activities" title="Life Coop members visiting the rice fields at Our Seed Farm"><img src="../images/chapter_01/Activity-Farm-Visit-2jpeg.jpeg" class="img-fluid figure-img" alt="Life Coop members visiting the rice fields at Our Seed Farm"></a></p>
<figcaption>Life Coop members visiting the rice fields at Our Seed Farm</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Activity-Rice-Planting.jpeg" class="lightbox" data-gallery="activities" title="Joining in with planting out rice seedlings on Hansalim farm in Paju"><img src="../images/chapter_01/Activity-Rice-Planting.jpeg" class="img-fluid figure-img" alt="Joining in with planting out rice seedlings on Hansalim farm in Paju"></a></p>
<figcaption>Joining in with planting out rice seedlings on Hansalim farm in Paju</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Activity-Farm-Ceremony-1.jpeg" class="lightbox" data-gallery="activities" title="A traditional ceremony showing respect to the land"><img src="../images/chapter_01/Activity-Farm-Ceremony-1.jpeg" class="img-fluid figure-img" alt="A traditional ceremony showing respect to the land"></a></p>
<figcaption>A traditional ceremony showing respect to the land</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Activity-Farm-Ceremony-2.jpeg" class="lightbox" data-gallery="activities" title="Sharing food together as part of the ceremony"><img src="../images/chapter_01/Activity-Farm-Ceremony-2.jpeg" class="img-fluid figure-img" alt="Sharing food together as part of the ceremony"></a></p>
<figcaption>Sharing food together as part of the ceremony</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Activity-Sharing-Stories.jpeg" class="lightbox" data-gallery="activities" title="Sharing stories after the ceremony and rice planting activity in Paju"><img src="../images/chapter_01/Activity-Sharing-Stories.jpeg" class="img-fluid figure-img" alt="Sharing stories after the ceremony and rice planting activity in Paju"></a></p>
<figcaption>Sharing stories after the ceremony and rice planting activity in Paju</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Activity-Helping-Hands.jpeg" class="lightbox" data-gallery="activities" title="A ‘helping hands’ activity at a Hansalim farm"><img src="../images/chapter_01/Activity-Helping-Hands.jpeg" class="img-fluid figure-img" alt="A ‘helping hands’ activity at a Hansalim farm"></a></p>
<figcaption>A ‘helping hands’ activity at a Hansalim farm</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Activity-Producer-Consumer-Conference.jpeg" class="lightbox" data-gallery="activities" title="Hansalim producers and consumer members participating in a conference organised by the Hansalim Food Life Education Centre"><img src="../images/chapter_01/Activity-Producer-Consumer-Conference.jpeg" class="img-fluid figure-img" alt="Hansalim producers and consumer members participating in a conference organised by the Hansalim Food Life Education Centre"></a></p>
<figcaption>Hansalim producers and consumer members participating in a conference organised by the Hansalim Food Life Education Centre</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Activity-Org-Activists_Gathering.jpeg" class="lightbox" data-gallery="activities" title="A gathering of North Seoul Hansalim Organisational Activists to share ideas and prepare for the year ahead"><img src="../images/chapter_01/Activity-Org-Activists_Gathering.jpeg" class="img-fluid figure-img" alt="A gathering of North Seoul Hansalim Organisational Activists to share ideas and prepare for the year ahead"></a></p>
<figcaption>A gathering of North Seoul Hansalim Organisational Activists to share ideas and prepare for the year ahead</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Activity-Charity-Sale.jpeg" class="lightbox" data-gallery="activities" title="A ‘yard sale’ to raise money for charity organised by Hansalim Activists"><img src="../images/chapter_01/Activity-Charity-Sale.jpeg" class="img-fluid figure-img" alt="A ‘yard sale’ to raise money for charity organised by Hansalim Activists"></a></p>
<figcaption>A ‘yard sale’ to raise money for charity organised by Hansalim Activists</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Activity-Forum.jpeg" class="lightbox" data-gallery="activities" title="A national research forum organised by Wonju Hansalim Life Coop"><img src="../images/chapter_01/Activity-Forum.jpeg" class="img-fluid figure-img" alt="A national research forum organised by Wonju Hansalim Life Coop"></a></p>
<figcaption>A national research forum organised by Wonju Hansalim Life Coop</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>Each of these activities are supported by funds allocated in the budgets of the Life Coops and the Hansalim Federation which ultimately come from their combined sales. The chart below, <a href="#fig-participation" class="quarto-xref">Figure&nbsp;<span>1.4</span></a>, gives you an idea of the amount of interaction between consumers and producers in the course of a single year. It shows the number of ‘person-visits’ categorized by each Life Coop and by the type of activity in 2023. <em>Exchange</em> refers to activities involving interaction between producers and consumers and <em>engagement</em> refers to activities among consumers themselves. You can see that there were around 59,000 encounters between individuals in 2023 that were directly facilitated by Hansalim’s member Life Coops. Although many of these are repeat visits of individuals (so the total number of people involved will be somewhat less) you still get a sense of the sheer scale of relationship building that is going on within Hansalim.</p>
<div id="fig-participation" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-participation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p><a href="../plots/Participation_2023.png" class="lightbox" data-gallery="diagrams" title="Figure&nbsp;1.4: Participation in 2023: engagement among consumers and exchanges between consumers and producers."><img src="../plots/Participation_2023.png" class="img-fluid figure-img"></a></p>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-participation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.4: Participation in 2023: engagement among consumers and exchanges between consumers and producers.
</figcaption>
</figure>
</div>
<p>In addition to selling to members and organizing member activities, Life Coops also engage with the wider community by running a whole range of educational activities and training, community kitchens, environmental campaigns and community building activities and some have also set up new cooperatives in solar power and in the care sector. On top of all these activities, the high point of Hansalim’s cultural life are the festivals which are held at national and local levels. For example, the Autumn festivals bring producers and consumers together for food, drinking and traditional games and dancing. They provide a special context for making friends and creating a sense of shared identity and camaraderie.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Festival-Dragon-Flags.jpeg" class="lightbox" data-gallery="festivals" title="Celebration Festival at Goesan"><img src="../images/chapter_01/Festival-Dragon-Flags.jpeg" class="img-fluid figure-img" alt="Celebration Festival at Goesan"></a></p>
<figcaption>Celebration Festival at Goesan</figcaption>
</figure>
</div>
<div>

</div>
<div class="quarto-layout-panel" data-layout-nrow="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Festival-Dancers.jpeg" class="lightbox" data-gallery="festivals" title="Dancing at the festival in Goesan"><img src="../images/chapter_01/Festival-Dancers.jpeg" class="img-fluid figure-img" alt="Dancing at the festival in Goesan"></a></p>
<figcaption>Dancing at the festival in Goesan</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Festival-Goesan-Dancers.jpeg" class="lightbox" data-gallery="festivals" title="Autumn harvest festival in Goesan (in the foreground is the rope used for the mass tug-of-war game!)"><img src="../images/chapter_01/Festival-Goesan-Dancers.jpeg" class="img-fluid figure-img" alt="Autumn harvest festival in Goesan (in the foreground is the rope used for the mass tug-of-war game!)"></a></p>
<figcaption>Autumn harvest festival in Goesan (in the foreground is the rope used for the mass tug-of-war game!)</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Festival-Goesan-Flag.jpeg" class="lightbox" data-gallery="festivals" title="Hansalim flag flying among the dancers at the Autumn festival"><img src="../images/chapter_01/Festival-Goesan-Flag.jpeg" class="img-fluid figure-img" alt="Hansalim flag flying among the dancers at the Autumn festival"></a></p>
<figcaption>Hansalim flag flying among the dancers at the Autumn festival</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Festival-Goesan-Rope.jpeg" class="lightbox" data-gallery="festivals" title="The being prepared for the giant tug-of-war game"><img src="../images/chapter_01/Festival-Goesan-Rope.jpeg" class="img-fluid figure-img" alt="The being prepared for the giant tug-of-war game"></a></p>
<figcaption>The being prepared for the giant tug-of-war game</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>For consumers and producers then, there is a lot of fun to be had as a member of a Hansalim community. This is a vitally important part of the rhythm of hard work broken up by fantastic celebrations and informal contexts for relaxation together. None of this would be possible, however, without the hard and often hidden work of the Practitioners.</p>
</section>
<section id="the-special-role-of-practitioners" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="the-special-role-of-practitioners">The special role of practitioners</h3>
<p>In Hansalim, employees are referred to as ‘practitioners.’ They are the people who make it possible to put the producer-consumer relationship into practice by running the businesses, coordinating movement activities and organizing the many processes that are required to keep each member organization running and working together as a federation. They are not only professionals in logistics, marketing, strategy etc. but they also act as mediators between consumer and producer members and their organizations. Whereas a manager in a corporate enterprise might be able to focus solely on negotiating financial dealings with clients and suppliers, Hansalim practitioners often find themselves also negotiating the complex conflicts in values and expectations between Hansalim members, making their role especially difficult and important.</p>
<p>The largest employer of practitioners within Hansalim is the Business Federation which takes the next largest share of revenue after the Life Coops (8.86%) to cover the costs of labour, logistics, promotion and marketing, product development etc. One of the most important asset managed by the business federation is the Anseong Logistics Centre.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Logistics-Anseong.jpeg" class="lightbox" data-gallery="quarto-lightbox-gallery-65" title="Hansalim’s Anseong logistics and processing centre"><img src="../images/chapter_01/Logistics-Anseong.jpeg" class="img-fluid figure-img" alt="Hansalim’s Anseong logistics and processing centre"></a></p>
<figcaption>Hansalim’s Anseong logistics and processing centre</figcaption>
</figure>
</div>
<p>Finally, the smallest share of the margin (0.81%) is used to fund the Hansalim Federation which organizes the national-level governance and policy-making processes, supports Hansalim’s educational, cultural, publishing, research and coordinates collaboration and solidarity activities with others in Korea and especially small-scale farmers abroad, and provides support to the member Life Coops.</p>
<p>In 2023 there were a total of 291 practitioners working in the member Life Coops, a further 235 working for the Business Federation and 40 at the Hansalim Federation. These were supplemented by 1,396 Activists working in the stores and to organize member activities (see <a href="#fig-federation" class="quarto-xref">Figure&nbsp;<span>1.5</span></a> below. Together with the 3,579 producers and processors they generate enough revenue to support themselves and the broader collective efforts of the Hansalim Life Movement to bring about social and cultural change towards a more sustainable way of living.</p>
<p>A report by Hansalim in 2020 estimated that, across the whole of Hansalim:</p>
<blockquote class="blockquote">
<p>“There are 489 practitioners, 1,544 activists, 238 executives, 337 others, and a total of 2,370 members nationwide who organise this vast membership into businesses and movements. Add to this the 2,192 primary producers and 1,241 processors, and you have 6,041 people (as of December 2019) supporting their families.”<span class="citation" data-cites="Hansalim2020-rw"><a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a></span></p>
</blockquote>
<p>With such a large and complex organisation, you might think that there must be some strong central authority controlling everything from the top down and making sure efficiency is maximised and operations meticulously coordinated. Happily (or perhaps sadly, depending on your point of view) that is not the case in Hansalim.</p>
</section>
</section>
<section id="governed-through-deliberative-democracy" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="governed-through-deliberative-democracy"><span class="header-section-number">1.5</span> Governed through deliberative democracy</h2>
<p>One of the most extraordinary features of Hansalim is the depth of their commitment to deliberative democracy and local autonomy. This emphasis on democracy has deep roots, but before we explore those in more detail it is worth having overview of how Hansalim fits together today as a federation of democratic organisations. The governance structure of Hansalim is based on the principles of subsidiarity, mutual responsibility and deliberation rather than top down command and control.</p>
<section id="subsidiarity" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="subsidiarity">Subsidiarity</h3>
<p>Below, <a href="#fig-federation" class="quarto-xref">Figure&nbsp;<span>1.5</span></a>, is a diagram of Hansalim’s various organizations as they existed in 2023 and how they related to each other, laid out in order of how authority is delegated from top to bottom. At the top are the individual members. The 890,000 Member households and the 3,579 Producers. They are the owners of Hansalim. Below you can see the Life Coops, Producer Organizations and the Support Organizations and in the box labelled ‘Member Organisations Autonomous Activities’ I have listed the numbers of people involved (as far as data is available). The word ‘Practitioner’ here is Hansalim’s term for employed staff member (as mentioned above). Remember that ‘Activists’ refers to consumer members paid to either organise producer-consumer activities or work in the stores. Between them, the member organisations elect a total of 212 delegates to the General Assembly of the Hansalim Federation (maximum two 1-year terms). The General Assembly elects a board of 36 directors including the chair of directors who holds the title of president (maximum two 2-year terms). The board appoints the executive directors of the Federation, the Business Federation and the support organizations but cannot interfere with the governance and management of the member Life Coops or producer organizations. The standing committees, conferences and steering committees are where deliberations take place over policy and strategy decisions and they operate at local and national level involving producers, members and practitioners.</p>
<div id="fig-federation" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-federation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p><a href="../diagrams/federation.png" class="lightbox" data-gallery="diagrams" title="Figure&nbsp;1.5: Hansalim’s many organisations and their relationships."><img src="../diagrams/federation.png" class="img-fluid figure-img"></a></p>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-federation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.5: Hansalim’s many organisations and their relationships.
</figcaption>
</figure>
</div>
<p>So you see that neither the Hansalim Federation nor the Business Federation are ‘apex’ organisations or ‘head offices’ but rather, they are supporting organisations whose purpose is to facilitate the successful business of the Life Coops and producer organisations while running the delegated shared movement activities and supporting the independent movement activities of member organisations.</p>
</section>
<section id="mutual-responsibilities" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="mutual-responsibilities">Mutual responsibilities</h3>
<p>The way the Hansalim Federation sees itself in relation to the other Hansalim organisations can be understood with the help of the following diagram, <a href="#fig-stakeholders" class="quarto-xref">Figure&nbsp;<span>1.6</span></a>, which was published in the Hansalim 2017 White Paper.<span class="citation" data-cites="Hansalim2017-qp"><a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a></span> I have reproduced it here with some minor modifications and translated it into English. With the Hansalim Federation at the centre each of the stakeholders are listed along with their mutual responsibilities in relation to the Federation. Hansalim’s stakeholders include five categories: Producers, Members (i.e.&nbsp;consumer members), Practitioners, Activists and the Local Community.</p>
<div id="fig-stakeholders" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stakeholders-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p><a href="../diagrams/stakeholders.png" class="lightbox" data-gallery="diagrams" title="Figure&nbsp;1.6: A map of Hansalim stakeholders and their responsibilities."><img src="../diagrams/stakeholders.png" class="img-fluid figure-img"></a></p>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stakeholders-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.6: A map of Hansalim stakeholders and their responsibilities.
</figcaption>
</figure>
</div>
<p>Along with Producers, the Members share the main responsibility for governance of the federation and their local associations and Life Coops. Members elect delegates to the General Assembly, participate in committees, respond to and carry out member surveys and also govern the business and movement activities of their own Life Coops. Members are also expected to consume responsibly and encouraged to participate in activities to support producers and help the local community. From the Federation they receive goods produced according to Hansalim standards and values as well as support (organisational and financial) for member engagement activities and member education.</p>
<p>Producers also elect delegates to the General Assembly, participate in the production consultation system and respond to and carry out producer surveys. Their responsibility to the federation is to produce goods according to Hansalim standards and values and in return the federation is tasked with ensuring that their livelihoods are sustainable.</p>
<p>The Practitioners’ main responsibility is for running the business activities of the member organisations and the shared business organisations (i.e.&nbsp;the Business Federation) but they also play a role in supporting the governance and movement activities. Although Practitioners are not directly represented in the General Assembly, the executive directors (a Practitioner role) sit on the board of directors at each level of organisation from member to federation respectively. The Workplace life council is the closest thing to a labour union in its role of representing the interests of Practitioners. The Federation’s responsibility to Practitioners is to support their training and performance and increase job satisfaction. However, the role of Practitioners has evolved over time and is becoming increasingly ambiguous. Originally, during Hansalim’s early days, their main role was to act as a bridge between producers and consumers while running the business activities. In the beginning people joined Hansalim as Practitioners to support their shared vision and often worked very long hours for low pay doing whatever was needed. Now, as Hansalim has grown larger, many of those who worked for Hansalim from the early days have taken on managerial positions while the hiring of new employees has become more formalized and specialized. As a consequence, the role of Practitioners as a bridge between consumers and producers has become weaker and the emphasis has shifted towards running business operations.</p>
<p>Activists were originally member volunteers whose role was to organize consumer activities and also act as a bridge with producers. After a while, it was decided that they should be financially compensated for their work and their roles should be more clearly specified. Now, Activists are members who have received training for specific roles and are paid a wage to work in the stores, receive phone orders and organize various activities for producers and members.</p>
<p>The Local Community is included as a stakeholder category as producers, members and activists seek to identify and take action on local needs. They work with local community organizations and representatives of such organizations are also invited to participate on various councils as appropriate. In fact, it is quite common for Hansalim members and producers to simultaneously hold official positions in Hansalim and other local grassroots organizations and social enterprises.</p>
<p>The organizational role of the Hansalim Federation in this structure is to support each of these different stakeholders to realize their own and Hansalim’s values in their various activities. A large part of this involves organising committees and meetings, collecting opinions from members and supporting the deliberative process among member organisations through training, research and timely communication of information about each area of business and activism.</p>
</section>
<section id="deliberation" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="deliberation">Deliberation</h3>
<p>The deliberative processes in Hansalim encompasses the grassroots groups and conferences and work their way through the various levels of organisation to the committees, boards of directors and general assemblies at local and national level. Formal meetings are required to follow the regulations in the articles of association and bylaws and are usually run according to an adapted set of rules from Robert’s Rules of Order by Henry Martyn Robert (1837-1923)<span class="citation" data-cites="Hansalim2020-rw"><a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a></span> and scrupulously minuted and reported. Opinions are also gathered through online forums, member surveys and organisation messaging boards. Finally, the auditing process provides an opportunity for independent monitoring and constructive criticism from people elected to the Supervisory Council.</p>
<p>At the heart of the deliberative process is the delegate system In each Life Coop where the number of members is large enough to make direct participation impractical, delegates are elected with the responsibility of reflecting the opinions of the wider membership through their participation in the General Assembly. Their core role is to ‘ensure that the wishes of members are properly and responsibly represented’.<span class="citation" data-cites="Hansalim2018-zz"><a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a></span> Thus, in addition to attending the General Assembly to vote on decisions and elect directors, they are expected to be the channel of communication between the board of directors and members. To fulfil this role they need to join in with member activities and gatherings, listen to the opinions of other members, build relationships of trust and participate in the regular briefing sessions in preparation for the General Assembly. The term of office for delegates is set by the articles of association of each Life Coop within a range of four years. As members of the General Assembly they have the authority to amend the articles of association, elect and remove officers (i.e.&nbsp;members of the board of directors and executive directors), approve financial reports and budget plans, approve the supervisory council reports and decide on refunds of invested contributions to members who withdraw or are expelled.</p>
<p>This is quite a heavy responsibility for an unpaid position and the success of the deliberative process depends upon the voluntary commitment of members willing to take up responsibility for democratic management of the cooperative. It also looks like a very inefficient system of management which requires excessive amounts of time and resources for the sake of a very slow decision making process. So how can we explain the persistence of Hansalim members with such a cumbersome system of governance? And does it bring any benefits that justify the continuing investment of time and energy?</p>
<p>A quick detour through history is in order to help understand the significance of democracy for Hansalim (see <a href="#fig-timeline" class="quarto-xref">Figure&nbsp;<span>1.7</span></a>).</p>
</section>
</section>
<section id="rooted-in-a-history-of-struggle" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="rooted-in-a-history-of-struggle"><span class="header-section-number">1.6</span> Rooted in a history of struggle</h2>
<p>For the Hansalim founders, democracy was not simply a suitable management structure but a fundamental way of life that had been tested and proved through decades of struggle against successive dictatorships. The role of cooperatives in the struggle for democracy in Korea went back to the pro-democracy movement of the 1960s and 70s (in which many of the Hansalim founders were involved<span class="citation" data-cites="Kim2019-dd"><a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a></span>) and inherited a long tradition of anti-state resistance from the pre-war independence movement (see <a href="#fig-timeline" class="quarto-xref">Figure&nbsp;<span>1.7</span></a>).</p>
<div id="fig-timeline" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-timeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p><a href="../diagrams/timeline.png" class="lightbox" data-gallery="diagrams" title="Figure&nbsp;1.7: Timeline of Korean history and evolution of the cooperative movement"><img src="../diagrams/timeline.png" class="img-fluid figure-img"></a></p>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-timeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.7: Timeline of Korean history and evolution of the cooperative movement
</figcaption>
</figure>
</div>
<section id="fighting-for-independence" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="fighting-for-independence">Fighting for independence</h3>
<p>The annexation of Korea by Japan in 1910 was the culmination of a long history of invasions and exploitation of the peninsula. It solidified Japan’s control over Korea and began a long period of oppression during which many of the freedoms of Korean citizens were restricted and the colonial government embarked on a project to destroy Korean cultural, linguistic, and national identity and to completely assimilate Korea through a wholesale re-education of the population through economic domination and their own colonial school system.<span class="citation" data-cites="Tsurumi1984-hq"><a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a></span> As part of this project, the colonial government also developed a national infrastructure of state-run agricultural and financial cooperatives to manage rural and industrial development and facilitate top-down control and decision making.<span class="citation" data-cites="Kim2017-xf"><a href="#fn15" class="footnote-ref" id="fnref15" role="doc-noteref"><sup>15</sup></a></span> The Korean resistance against the colonial government sought to apply alternative models of cooperativism inspired by grassroots movements from Europe and Japan as well as Korean traditional models of autonomous mutual self-help that had been already present in Korea since the precolonial era. These included reciprocal resource sharing associations called <em>Gye</em><span class="citation" data-cites="Kim2017-xf"><a href="#fn16" class="footnote-ref" id="fnref16" role="doc-noteref"><sup>16</sup></a></span>, cooperative labour associations called <em>Dure</em><span class="citation" data-cites="Lee2006-cw"><a href="#fn17" class="footnote-ref" id="fnref17" role="doc-noteref"><sup>17</sup></a></span>, mechanisms for voluntarily assisting those in need in the local community called <em>Pumasi</em><span class="citation" data-cites="Lee2020-ba"><a href="#fn18" class="footnote-ref" id="fnref18" role="doc-noteref"><sup>18</sup></a></span> and the tradition of <em>Kimjang</em>, the communal making and sharing of Kimchi.</p>
<p>Thus, under Japanese colonial rule, cooperatives in Korea evolved along two parallel pathways – <em>statist</em> and <em>grassroots</em> – and while statist cooperatives appeared to contradict the very principles of cooperativism – being extensions of the state bureaucracy and neither independent nor democratic – grassroots cooperatives developed in connection with Korean nationalist and socialist movements dedicated to Korean independence.<span class="citation" data-cites="Kim2017-xf"><a href="#fn19" class="footnote-ref" id="fnref19" role="doc-noteref"><sup>19</sup></a></span></p>
<p>After the Sino-Japanese War in 1937, most cooperatives were forcibly converted into rural promotion movements or dissolved due to the mobilisation for war and their leaders were arrested.<span class="citation" data-cites="Kim2022-im"><a href="#fn20" class="footnote-ref" id="fnref20" role="doc-noteref"><sup>20</sup></a></span> Following Korea’s liberation from Japan in 1945 the cooperative movement was further disrupted by the Korean war and the division of the peninsula.</p>
</section>
<section id="fighting-for-democracy" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="fighting-for-democracy">Fighting for democracy</h3>
<p>From the 1950s onwards, following the Korean war, grassroots cooperatives that had emerged as part of the anti-colonial independence movement in the 1920s and 30s began to re-form. At the same time the state adopted the colonial era apparatus of cooperatives created by the Japanese to control the rural and industrial economy. Park Chung-hee united the agricultural and financial cooperatives created by the colonial government to form the National Agricultural Cooperative Federation (NACF or Nonghyup) which now boasts of being one of the worlds’ largest agricultural cooperatives. Although it is called a cooperative, it functioned as a para-state organisation and was used as a bureaucratic tool of state control to drive through the green revolution in agriculture and to manipulate political support for the Park regime among the rural population.<span class="citation" data-cites="Burmeister2006-aa"><a href="#fn21" class="footnote-ref" id="fnref21" role="doc-noteref"><sup>21</sup></a></span></p>
<p>In contrast, closely connected to the emerging anti-Park democratisation movement, grassroots cooperatives started to spread again and to promote cooperative ideas throughout the country, establishing schools, consumer cooperatives, credit unions, and medical cooperatives to respond to the desperate need for affordable medical treatment for survivors of the war.<span class="citation" data-cites="Kim2017-xf"><a href="#fn22" class="footnote-ref" id="fnref22" role="doc-noteref"><sup>22</sup></a></span> The organic farming movement also began to spread through the influence of the Poolmoo school (now known as Poolmoowon) which established the first consumer cooperative in 1959 in South Chungcheong Province and, starting in 1975, developed the largest organic farming region in Korea. Through the 1970s and early 1980s, the pro-democracy Catholic Farmers Movement, Catholic Priests’ Association for Justice (CPAJ) and other Christian groups, credit unions and consumer cooperatives along with democratic movements among factory workers, peasant farmers, and students continued to increase in influence and spread throughout the country.</p>
<p>Among the leaders of this movement was the Catholic Bishop Ji Hak-soon, who became the first bishop of Wonju in 1965. He had left North Korea before the war to train as priest in Rome and, while there, he was deeply impacted by the spirit of the Vatican Two Council which urged the church to become more outward focused on the needs of local communities and to support ecumenical unity; to become a church run by and for the people, and for the poor and marginalised in particular.<span class="citation" data-cites="Kim2019-dh"><a href="#fn23" class="footnote-ref" id="fnref23" role="doc-noteref"><sup>23</sup></a></span></p>
<p>It was in Wonju, that Ji Hak-soon met Jang Il-soon who was to become one of his closest friends. Jang Il-soon was a native of Wonju and dropped out of Seoul National University (SNU) after the war to found Daeseong School in Wonju to provide a free education to local children. After a failed attempt to run for political office, he spent three years in prison between 1961 and 63, originally facing a death sentence, accused of being a communist. After his sentence was commuted and he was released the state put him under surveillance and prohibited him from public lecturing or writing. With no other options, he became a farmer and an artist, painting calligraphy which he gave away to everyone and anyone. Within the context of the church, Ji Hak-soon gave him the opportunity to teach again and, in 1967, he began training lay Catholic members to prepare for a transformation of the church into a self-reliant lay-centred organisation that supported a wider rural development movement of credit unions and cooperatives.<span class="citation" data-cites="Kim2019-dd"><a href="#fn24" class="footnote-ref" id="fnref24" role="doc-noteref"><sup>24</sup></a></span></p>
<p>With a population of just 100,000, Wonju diocese was an impoverished region of coal-mining and farming communities. The church was dependent upon foreign aid for its survival and the town itself was a cultural backwater with very few resources. As soon as Ji Hak-soon took office he and Jang Il-soon set up Wonju’s first credit union in 1966 and founded Jinkwang Middle School in 1967. Jang Il-soon began to organise training courses for cooperative and credit union members and established the Cooperative Education Institute in Jinkwang school to develop the cooperative movement beyond the Catholic Church.<span class="citation" data-cites="Kim2019-dh"><a href="#fn25" class="footnote-ref" id="fnref25" role="doc-noteref"><sup>25</sup></a></span> The school’s students and teachers also created the first school cooperative in Korea, Jinkwang Cooperative, to purchase books and equipment and run the canteen.</p>
<p>One of the teachers at the school was Park Jae-il. In 1969, after his after his release from prison for his involvement in the June 3rd Movement (protests against the military regime’s policy toward Japan) he moved to Wonju to join the Social Development Committee and the Catholic Farmers’ Association, led by Bishop Ji Hak-soon. He became a teacher at Jinkwang School and attended one of Jang Il-soon’s lectures after school one day. He was so captivated by the vision for reviving cooperation among the common people that he quit teaching to join the cooperative movement full time, taking up a key role in the Cooperative Education Institute. From that moment he became a lifelong student of Jang Il-soon and worked alongside him and Bishop Ji Hak-soon in the cooperative and rural development movement in Wonju. He would later become the president of the Catholic Farmers Association and then Hansalim’s first chair of directors.</p>
<p>In addition to promoting education Ji Hak-soon also built cultural spaces, hospitals and welfare facilities for the disabled. Among these projects, the most significant was the cultural centre which he built in front of Wonju Cathedral. Sponsored by religious organisations from Europe and the United States and dedicated on July 12th 1968, the Wonju Catholic Center was the first civic cultural centre of the Korean Catholic Church. The three story building – run by the diocese and staffed by young lay church members – included offices, meeting rooms, an exhibition hall, projection room, first-floor cafeteria, basement room and dormitories. It quickly became a popular meeting place for young people and a hive of creative activity, hosting performances by local musicians and exhibitions by local artists. The main hall was used to stage plays by Wonju’s Sanya Theatre Company directed by Jang Il-soon’s younger brother Jang Sang-soon and the basement room was the venue for DJs to play pop and classical music from a record collection which apparently exceeded even that of the local radio station!</p>
<p>Around the Bishop, Jang Il-soon, Park Jae-il and their friends, an informal network of pro-democracy and cooperative movement activists began to gather. The Wonju Group, as they were known, began to expand the cooperative movement beyond Wonju into Gangwon province and to forge links across religious and ideological divides. Both Jang Il-soon and Ji Hak-soon made a point of reaching out beyond the boundaries of the Catholic church to other religious groups, not only to other Christian dominations but also to Buddhists. Priests, pastors and monks would visit each others congregations to preach and meet regularly at restaurants to share meals and talk together. The Catholic Church in Wonju became a church not only for believers but for all people striving to build a better and more democratic society. Following the example of Jesus, they sought to serve those in need without distinction and to freely support all who worked for the good of the whole community.<a href="#fn26" class="footnote-ref" id="fnref26" role="doc-noteref"><sup>26</sup></a></p>
<p>Jang Il-soon saw the cooperative movement as a training ground for democracy for the whole community and a means of empowering people to become responsible citizens.<span class="citation" data-cites="Kim2019-dd"><a href="#fn27" class="footnote-ref" id="fnref27" role="doc-noteref"><sup>27</sup></a></span> He described it as a “movement for service to the masses, abandoning arrogance and radical elite consciousness.” and a “downward crawling movement.”<span class="citation" data-cites="Kim2019-dd"><a href="#fn28" class="footnote-ref" id="fnref28" role="doc-noteref"><sup>28</sup></a></span> In his lectures, Jang Il-soon reminded people of their own traditional culture of rural cooperation in Korea through Dure (farmers coops), Gye (village credit unions) and Pumasi (informal labour exchange). He referenced the 19th century history of cooperation among the British working class (the Rochdale Pioneers) and the credit union movements in France and Germany as examples of people finding ways to break free from corporate exploitation and live together on their own terms through mutual aid and self-reliance.<span class="citation" data-cites="Kim2019-dd"><a href="#fn29" class="footnote-ref" id="fnref29" role="doc-noteref"><sup>29</sup></a></span> He drew inspiration not only from Jesus’s teachings but also from Buddhist scriptures, Daoist and Confucian philosophy, Korean traditional spirituality and Ghandi’s example of non-violent resistance to enlarge people’s awareness of themselves and the world.</p>
<p>As a symbol of this broad and inclusive vision, the Wonju Catholic Centre became a hub for students and other pro-democracy activists and writers who gathered from Wonju and beyond to talk and drink late into the evenings in the cosy basement room. One of those young people was a poet named Kim Young-il who wrote under the pen name “Ji-ha” (芝河). Originally from Mokpo, Kim Ji-ha had moved as a child to Wonju with his parents. At Seoul National University he became active within the pro-democracy movement in Seoul and, when he returned to Wonju, he brought with him a cast of activists and artists who quickly joined forces with the growing cultural movement (minjung movement) in Wonju. Together they created yard plays (a form of traditional peasant theatre called madang-geuk, 마당극), mask-dances and plays for theatre. These plays raised the profile of Wonju among the wider national minjung movement and before long, Wonju was being called “the holy land of democratisation.”<span class="citation" data-cites="Kim2019-dd"><a href="#fn30" class="footnote-ref" id="fnref30" role="doc-noteref"><sup>30</sup></a></span></p>
<div>

</div>
<div class="quarto-layout-panel" data-layout-nrow="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Founders-Ji-Hak-soon.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-69" title="Ji Hak-soon (1921-1993) - Bishop of Wonju, founder of Wonju Credit Union and Cooperative Movements"><img src="../images/chapter_01/Founders-Ji-Hak-soon.jpg" class="img-fluid figure-img" alt="Ji Hak-soon (1921-1993) - Bishop of Wonju, founder of Wonju Credit Union and Cooperative Movements"></a></p>
<figcaption>Ji Hak-soon (1921-1993) - Bishop of Wonju, founder of Wonju Credit Union and Cooperative Movements</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Founders-Jang-Il-soon.jpeg" class="lightbox" data-gallery="quarto-lightbox-gallery-70" title="Jang Il-soon (1928-1994) - teacher, farmer, artist, Hansalim founder"><img src="../images/chapter_01/Founders-Jang-Il-soon.jpeg" class="img-fluid figure-img" alt="Jang Il-soon (1928-1994) - teacher, farmer, artist, Hansalim founder"></a></p>
<figcaption>Jang Il-soon (1928-1994) - teacher, farmer, artist, Hansalim founder</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Founders-Park-Jae-il.jpeg" class="lightbox" data-gallery="quarto-lightbox-gallery-71" title="Park Jae-il (1938-2010) - farmer, activist, Hansalim founder"><img src="../images/chapter_01/Founders-Park-Jae-il.jpeg" class="img-fluid figure-img" alt="Park Jae-il (1938-2010) - farmer, activist, Hansalim founder"></a></p>
<figcaption>Park Jae-il (1938-2010) - farmer, activist, Hansalim founder</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Founders-Kim-Ji-ha.jpeg" class="lightbox" data-gallery="quarto-lightbox-gallery-72" title="Kim Ji-ha (1941-2022) - Poet, activist, Hansalim founder"><img src="../images/chapter_01/Founders-Kim-Ji-ha.jpeg" class="img-fluid figure-img" alt="Kim Ji-ha (1941-2022) - Poet, activist, Hansalim founder"></a></p>
<figcaption>Kim Ji-ha (1941-2022) - Poet, activist, Hansalim founder</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>Together, with the Wonju Group, Jang Il-soon and Ji Hak-soon reorganised the church in the Wonju diocese into a network of self-governing self-supporting parishes and set up a program of education and training aimed at empowering the poor and marginalised to form self-sufficient self-governing communities across Gangwon province. Their vision was for a cooperative movement that was economically and politically independent from the authoritarian state and which promoted rural and urban development led by communities themselves.</p>
<p>However, just as things were starting to take off catastrophe hit. In 1972 the large-scale flooding of the Namhan River basin caused widespread devastation in Gangwon and surrounding provinces. In Wonju Diocese the floods damaged 50,000 buildings and displaced more than 140,000 people.<span class="citation" data-cites="Kim2019-dd"><a href="#fn31" class="footnote-ref" id="fnref31" role="doc-noteref"><sup>31</sup></a></span> Bishop Ji Hak-soon went to Germany to ask for funds from the catholic charities Miserere and Caritas to support rebuilding. With the money they provided (2.91 million marks or around $360,000) he set up a Disaster Countermeasures Project Committee to coordinate a long-term recovery project. However, instead of simply providing unconditional aid, as was normally done under such circumstances, the committee targeted their resources at supporting communities to become self-sufficient. Food and money were given as wages for productive work rebuilding communities, restoring farmland and developing new income sources for farmers such as setting up village craft workshops.</p>
<p>Young people from the Wonju Diocesan Youth Association who had been involved with the cooperative movement in Wonju were recruited to act as counsellors. This title of ‘counsellor’ was chosen intentionally to avoid the impression that they were responsible for leading or directing the disaster response. Instead, their role was to visit the affected villages, learn about their needs and provide advice and training to enable villagers to take leadership of the reconstruction and development process themselves. The requirements for receiving support for projects were that they were productive so as to provide a steady income, communal rather than individual and managed cooperatively by the villagers. The ultimate goal was to rebuild solidarity within and between village communities who had suffered years of exploitation under colonial and now military rule that had led to widespread mistrust among the rural population.</p>
<p>This was a particularly special time for Jang Il-soon. He began to see what he had been dreaming of for so many years take shape in reality in his own community. Hundreds of villages across three provinces participated, creating credit unions and cooperatives, restoring the culture of shared agricultural labour and managing their affairs democratically through village assemblies. Others saw what was happening too and the pattern of rural development through cooperation that began in Wonju spread across the country.<span class="citation" data-cites="Kim2019-dd"><a href="#fn32" class="footnote-ref" id="fnref32" role="doc-noteref"><sup>32</sup></a></span> But it was not to last long.</p>
</section>
<section id="fighting-for-a-civilisation-of-life" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="fighting-for-a-civilisation-of-life">Fighting for a civilisation of Life</h3>
<p>Although the Wonju movement made a significant and lasting contribution to rural development and democratisation<a href="#fn33" class="footnote-ref" id="fnref33" role="doc-noteref"><sup>33</sup></a>, it was carried out in resistance against the increasingly authoritarian Yusin regime under Park Chung-hee. Top-down state-led projects of agricultural industrialisation, rural improvement and political indoctrination through Nonghyup and the Saemaul Movement (New Village Movement) contributed to the ongoing suppression of the Wonju group’s activities. In a bid to achieve self-sufficiency in rice, the state adopted a new high yielding rice variety, Tongil rice, which was rapidly extended to farmers through a combination of incentives and coercion<span class="citation" data-cites="Burmeister1987-zt"><a href="#fn34" class="footnote-ref" id="fnref34" role="doc-noteref"><sup>34</sup></a></span>. It required heavy fertiliser and pesticide application to achieve its promised yields<span class="citation" data-cites="Hong2021-sc"><a href="#fn35" class="footnote-ref" id="fnref35" role="doc-noteref"><sup>35</sup></a></span> which were supplied exclusively through Nonghyup. These pesticides were highly toxic and little training was provided to farmers about how to minimise risk of exposure. Despite the undeniable improvement in rural incomes stimulated by the state-led green revolution, as the use of chemical pesticides rapidly increased through the 1970s many farmers became sick from pesticide poisoning, ecosystems became increasingly polluted and food safety concerns grew among consumers. Jang Il-soon and others in the Wonju Group began to recognise the dangers of too narrow a focus on productivity and profit sharing. Somehow, cooperation needed to be extended beyond humans to include the natural world in a symbiotic relationship.</p>
<p>Then, in 1974, in what seemed like retaliation against the Wonju Group, Bishop Ji Hak-soon and Kim Ji-ha were arrested, along with 253 others. Ji Hak-soon was court martialled under new emergency measures brought in by Park in reaction to growing unrest and pro-democracy protests among university students nationwide. His sentence was 15 years in prison on the charge of funding an anti-state group and masterminding a plot to overthrow the government.<span class="citation" data-cites="Kim2019-dd"><a href="#fn36" class="footnote-ref" id="fnref36" role="doc-noteref"><sup>36</sup></a></span> Kim Ji-ha was sentenced to death, commuted to life and released after 10 months only to be arrested again and his death sentences renewed. He spent 7 years in prison until he received a stay of execution.</p>
<p>Under pressure from the newly mobilised Catholic resistance and widespread anti-government protests, Park released Ji Hak-soon in 1975. But the government’s suppression of democratic movements intensified with new emergency measures and sweeping powers to control anyone who opposed him. During this difficult time, unable to engage directly in pro-democracy activism or the cooperative movement Jang Il-soon painted calligraphy, drew illustrations and wrote poetry, holding exhibitions to raise funds in support of others and communicate his resistance through art. In the years up to 1979 unrest and mass protests continued to spread until the shocking assassination of General Park by his own head of Central Intelligence, Kim Jae-gyu.</p>
<p>The democracy movement, that had been suppressed by Park, sprang back to life, as people rekindled hope for a transition to genuine democracy. But the new government fell in a matter of weeks as the chief of defence General Chun Doo-hwan led a military insurrection on December 12th 1979 and soon declared martial law.</p>
<p>The immediate reaction by citizens has become known as the “Seoul Spring”. Waves of mass protests spread across the country as students and workers took to the streets to oppose the military’s takeover and call for democracy. The military’s brutal response involved mass arrests, beatings, torture and killing of protesters. Things quickly came to a head in the city of Gwangju in south Jeolla province, a hotbed of pro-democracy activism.</p>
<p>While mass protests in the city had been held peacefully with police cooperation during the previous days, in preparation for General Chun’s final takeover of the government, paratroops and tanks had been sent to Gwangju to suppress the protests, beginning by arresting most of the leaders of Gwangju’s democracy movement. On May 18th, when students attempted to enter the city’s Chonnam National University campus they were brutally beaten by the waiting paratroopers and turned away from the university gates. This provoked spontaneous protests among students which spread across the city throughout the day, calling for an end to martial law and the removal of Chun Doo-hwan. This time, they were met by violence from the riot police and confrontations escalated throughout the day as students fought back and the numbers of protesters steadily grew. When the paratroopers began to chase down and to strip and beat the demonstrators and bystanders alike, the student protest became a popular revolt.</p>
<p>The next day it wasn’t just hundreds of students on the streets but around four thousand citizens - high school students, shop owners, labourers, housewives, priests and teachers - came out to support the students and confront the police and paratroopers in front of Province Hall. When the police fired tear gas and the paratroopers charged the demonstrators, they responded by breaking up paving stones to throw and collected metal pipes and other implements to use as makeshift weapons. Molotov cocktails, drums of oil and nearby vehicles were used to attack and drive back the troops. Taxi drivers took on the role of ambulances to take the injured protesters to hospitals. Buses, trucks and phone booths became barricades.</p>
<p>The clashes between citizens and military became more violent and the paratroopers used their batons, rifle buts and bayonets to attack the crowds and hunted people down as they fled down alleys and into nearby buildings. Whoever they captured they stripped, beat and tortured, leaving many dead or with life changing injuries and taking many more students back to their camp as prisoners. Even some of the riot police who tried to help the wounded, unaccustomed to the extreme violence perpetrated by the military forces, were themselves attacked by the paratroopers.</p>
<p>Over the next few days more than 200,000 demonstrators fought against the police and paratroopers across the city. Convoys of over 100 taxis and some buses and trucks joined the demonstrators on the streets and some began to use vehicles as battering rams and fire bombs to attack the paratroopers blockades. The streets were covered in burning cars, debris and the bodies of dead and injured protesters lying in pools of blood. Citizen Militia began to capture vehicles, explosives, rifles and ammunition to strengthen their stand against government forces who had begun to use live ammunition on the crowds leading to several fatalities and provoking growing rage among the citizens. Then the paratroopers deployed machine guns, automatic rifles and snipers to attack the citizens and military helicopters also opened fire on the crowds. Despite their resort to lethal force, the paratroopers were overwhelmed by the scale of the uprising, and withdrew to the outskirts of the city where they prepared for a large-scale offensive with reinforcements from the army’s 20th Division.</p>
<p>The demonstrators took control of Province Hall and other parts of the city center and organised a Citizen Settlement Committee to negotiate with the government forces. Having withdrawn from the city centre, soldiers blockaded Gwangju and were ordered to use lethal force against any resistance. Finally, after five days of blockade, in the middle of the night on the 27th May 1980 three special forces teams and a division of more than 3,000 soldiers moved on the city centre to recapture Province Hall and Gwangju Park in a battle that ended with 27 citizens and 2 soldiers dead and 295 citizens detained.</p>
<p>Over the course of the uprising, 20,000 trained soldiers were deployed to the city of 800,000. The total number of casualties is not known, as the government acted quickly to cover up the incident and manipulate the data reported. Conservative estimates are that over 200 of Gwangju’s residents were killed by government forces and many more hundreds injured while the so-called ‘ring leaders’ were imprisoned and tortured. Despite the immediate government cover up, news of the massacre at Gwangju spread among democracy activists and students and helped to undermine the legitimacy of the Chun regime, becoming a rallying cry for the pro-democracy movement.</p>
<p>The events in Gwangju were followed by rumours that the government was preparing to target other cities like Wonju which were also centres of pro-democracy activism. Deeply shocked and grieved by the news of Gwangju, and fearing for the people of his own city, Jang Il-soon went into hiding and urged everyone to keep quiet. His lack of action angered many in the democratisation movement and marked the beginning of a shift in his attitude towards forms of political resistance.</p>
<p>A few months after the Gwangju uprising and subsequent massacre, Kim Ji-ha was released from prison in December 1980. A lot had happened since his initial arrest and he had also had time to reflect himself on the experience of the Wonju Group. When he was reunited with Jang Il-soon they discovered they had both come to the same change of direction in their thinking.</p>
<p>Jang Il-soon described it in this way:</p>
<blockquote class="blockquote">
<p>“The Hansalim movement was something I had been thinking about for decades, and another was the consumer cooperative movement in the 70s (260), and as I continued the anti-dictatorship movement, I realized that I had to break out of the old Marxist paradigm, because it was not going to solve the problem, and it was going to continue the vicious circle. When I saw that they were spraying pesticides and fertilizers and trying to industrialize the city, I thought that the entire riverbed would be devastated. I told Mr.&nbsp;Park Jae-il, who was trying to start a rural movement in Wonju after the June 3 incident,”We should go in the direction of saving the farmland and food for the community.””<span class="citation" data-cites="Kim2019-dd"><a href="#fn37" class="footnote-ref" id="fnref37" role="doc-noteref"><sup>37</sup></a></span></p>
</blockquote>
<p>Since the mid-1970s, Jang Il-soon had been developing his philosophy and way of life around the teachings of Haewol (Choi Si-hyung), a virtually forgotten leader of an indigenous Korean religion called Donghak (sometimes written Tonghak and now known as Cheondogyo or the Heavenly Way). It was the ethical and cosmic vision of Donghak, and especially the practical spirituality of Haewol which became the foundation of the Hansalim movement as it emerged in Wonju through the 1980s.</p>
<p>Donghak was founded in 1860 by Su-un (Choi Je-u)<span class="citation" data-cites="Young2014-an"><a href="#fn38" class="footnote-ref" id="fnref38" role="doc-noteref"><sup>38</sup></a></span> at a time when Korean society was in turmoil under pressure from foreign interference, rapid economic change, a corrupt bureaucracy and a monarchy in the process of collapse.<span class="citation" data-cites="Seong2020-cv"><a href="#fn39" class="footnote-ref" id="fnref39" role="doc-noteref"><sup>39</sup></a></span> Su-un taught that all things bear Hanullim (divine life) within themselves and that ‘sagehood’ or unity with Hanullim was open to all regardless of education, class, gender or age simply through sincerely seeking and stilling ones own heart to listen. His message of equality, simple spirituality and reverence for the sacredness of all things, spread like wildfire among the peasantry and disillusioned middle classes alike. Fearing a revolution, the authorities quickly arrested him and executed him in 1864.</p>
<p>Su-un’s successor, Haewol expressed the Donghak teaching that ‘people are heaven’ in three practical rules: honour heaven (敬天), honour people (敬人), and honour all things (敬物). These three phrases express the idea of serving people as heaven and valuing the life of all natural things equally. Jang Il-soon revived Haewol’s teachings and sought, through Hansalim and the Life Movement, to implement them in the form a new kind of cooperative movement that unified humanity with one another and the cosmos in a symbiotic and spiritual relationship. He is quoted as saying:</p>
<blockquote class="blockquote">
<p>“Hae-wol, the second teacher of Donghak, said that if you know a bowl of rice, you know everything in the world, and Byeong-hee, Ui-am Son, also said that a bowl of rice is”born of a hundred people” (百夫所生), that is, it is made by the sweat of many peasants. He said that, but isn’t it true that it’s not just people who make it by sweating, but the heavens, the earth, and the whole world become an ensemble and move together as one, so that bowl of rice becomes a cosmic encounter? “If you go a step further, there is a saying in Haewol’s words,”Ichunsikcheon,” (以天食天) which means that heaven eats heaven. In Donghak, it is called innaecheon (people are heaven, 人乃天), and not only people are heaven, but every grain is heaven, every stone is heaven, every worm is heaven.”<span class="citation" data-cites="Kim2019-dd"><a href="#fn40" class="footnote-ref" id="fnref40" role="doc-noteref"><sup>40</sup></a></span></p>
</blockquote>
<p>This new direction was sharply at odds with the rest of the democratisation movement at the time which was becoming more explicitly revolutionary and militant in response to Chun Doo-hwan’s intensification of violent suppression. By 1985, it was clear that the memory of the Gwangju uprising and the Chun government’s massacre of civilians was firmly fixed in the national psyche and each year following, the anniversary of the uprising was marked by increasing numbers of participants who commemorated the victim’s sacrifice for democracy. Students began to resort to to self-immolation and public suicide as new forms of protest. Jang Il-soon was horrified by this self-destructive violence in protest against the regime and called instead for non-violent, passive resistance instead of violent struggle.</p>
<p>The new emphasis on the natural world as sacred and a spirituality that looked suspiciously more like shamanism or Buddhism than Catholicism must have been hard to accept for many of the devout Catholic members of the movement. It might seem odd then, that a movement led by Catholics and grounded in the Catholic church should come to embrace an apparently non-Christian philosophy. But on closer inspection, Donghak actually seems quite well placed to fit alongside Catholic social teaching by re-emphasising the sacredness of the nonhuman world. Jang Il-soon’s reinterpretation of Donghak ideas within his own life as a Catholic and his ability to bring them into synergy with Jesus’ teaching through his lectures must have gone a long way open the hearts of others. Finally, through a difficult year-long process of intensive discussion the Wonju Group came to an agreement on transitioning the cooperative movement in Wonju into a Life Movement rooted in Donghak philosophy.</p>
<p>The new direction was expressed in the Wonju Report in 1982 which was written on behalf of the group by Kim Ji-ha. The report criticised capitalist and socialist industrial models of civilisation as equally destructive and incapable of producing a fair and sustainable society and called for an alternative movement for the transformation of society centred on the concept of Life. Publication of the Wonju Report was followed by the organisation of training courses and lectures and a study tour in 1984 to cooperatives in Japan. In 1985 the Wonju Consumer Cooperative was created, with Park Jae-il as chairperson, to organise store-free direct trade with organic farming communities. The store in Seoul, Hansalim Nongsan, followed in 1986 and in 1987 the Hansalim Community Consumers’ Cooperative and the Hansalim Producers’ Association were founded. This led to the formation in 1988 of the Hansalim Community Consumers Alliance in Seoul with 70 members and the Hansalim Producers’ Council in Wonju with 70 farmers.</p>
<p>As the movement was gaining traction, the Wonju Group formed the Preparatory Group for the Hansalim Study Gathering which held five meetings to discuss and diagnose the problems in Korean society and consider how the Hansalim Movement should respond. These were followed by eleven study sessions and four discussion meetings to review contemporary social movements around the world, study various economic, philosophical and social theories, and survey Korea’s own cultural history of cooperation in search of the future direction for Hansalim. This process culminated in the publication of the Hansalim Manifesto in 1989 which set out the philosophical foundation of the movement and outlined the direction of it’s practical implementation.</p>
<p>One of the striking things about the Manifesto, aside from its fascinating philosophical and spiritual discussions, is its lack of prescriptions on methods and models of organisation. In fact, the cooperative model itself is never mentioned and appears only in the background as the most appropriate means available at the time for organising economic cooperation as part of the wider Life Movement. This lack of definition of organisational strategy set the scene for a continual evolution of forms and structures within Hansalim as circumstances changed, new approaches were tried out and succeeded or failed, and as learning and experience accumulated. As a consequence the subsequent development of Hansalim as a movement and organisation is extremely complex and diverse but the core principles of democratic autonomy and ecological responsibility run all the way through it as the hard-won fruits of decades of committed struggle and sacrifice.</p>
</section>
</section>
<section id="on-a-tilting-unfinished-journey" class="level2" data-number="1.7">
<h2 data-number="1.7" class="anchored" data-anchor-id="on-a-tilting-unfinished-journey"><span class="header-section-number">1.7</span> On a tilting unfinished journey</h2>
<p>The term used by the poet Kim Ji-ha to describe the evolutionary nature of a living movement such as Hansalim is “tilted balance” or a kind of dynamic (dis)equilibrium:</p>
<blockquote class="blockquote">
<p>“The philosophy of ‘tilted balance’, along with paradoxes, is crucial to understanding life. However, the term ‘tilted balance’ does not adequately describe the world of life. That is, the adjective ‘tilted’ and the noun ‘balance’, which denote states, do not capture the dynamism of the ever-changing world of life. The world of life is constantly tilting and tumbling rather than being in a stable balance.”<a href="#fn41" class="footnote-ref" id="fnref41" role="doc-noteref"><sup>41</sup></a></p>
</blockquote>
<p>Yoon, in his 2024 report about Hansalim’s evolving structure writes:</p>
<blockquote class="blockquote">
<p>“When choosing policies and institutions in Hansalim, we can present the ‘tilted balance’ in the”Hansalim Manifesto” as a decision-making principle that balances reality and ideals, associations and businesses.”<span class="citation" data-cites="Yoon2024-gs"><a href="#fn42" class="footnote-ref" id="fnref42" role="doc-noteref"><sup>42</sup></a></span></p>
</blockquote>
<p>Hansalim’s journey from a small movement of producers and consumers to a national federation has been far from smooth and simple. As successful as it has been, it was and still is fraught with struggles, controversies, failures and frustrations. One common phrase I heard from my interviewees in Hansalim is that “Hansalim looks beautiful from far away, but when you get closer you can see it is a lot more ugly.”</p>
<p>That ugliness is the reality of trying to work and live together with people whose backgrounds, perspectives and desires are so often radically different and even competing. It is the challenge of finding compromises that reflect a shared core of values while also trading off some of those values against others for the sake of a unity which is always and inevitably unsatisfactory. That is why, in addition to “moderation” - the virtue required to find the “middle way” - “discernment” is also key to maintaining this continually oscillating ‘tilted balance.’ Again, Kim Ji-ha explains this idea as a key aspect of the Confucian concept of the doctrine of the mean (中庸):</p>
<blockquote class="blockquote">
<p>“A more precise expression of this spirit is the term shijung (discernment - 时中), which appears in”The Doctrine of the Mean”, the second of the Four Books, written by Confucius’s grandson Zisi (子思). It means to strike a balance in an ever-changing situation. This kind of person is called a virtuous person. A person who is principled, but is also able to make judgements and adjust their behaviour according to the time and situation.”<a href="#fn43" class="footnote-ref" id="fnref43" role="doc-noteref"><sup>43</sup></a></p>
</blockquote>
<p>It is this principle, rather than any specific organisational model, that appears to define Hansalim’s journey and …</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div id="transformation">
<div>
<pre class="mermaid mermaid-js" data-label="transformation">gantt
    title Organisational Transformation
    dateFormat YYYY-MM-DD
    section National Organisation
        Hansalim Nongsan          :1986-12-01, 3y
        National Hansalim Council    :milestone, 1989-12-01
        Hansalim National Council   :milestone, 1996-02-01
        Hansalim National Gathering :milestone, 2001-03-01
        Hansalim Business Federation (logistics division functions) :2002-03-01, 9y
        Hansalim Corporation    :2004-02-01, 7y
        Hansalim Federation :2011-02-01, 13y
        Hansalim Business Federation (purchasing, logistics, external distribution)  :2019-01-01, 5y
    section Production Organisation
        Hansalim Producers Council :1988-11-01, 1y
        Hansalim Producers Committee    :1999-01-01, 1y
        Hansalim Agricultural Co. Ltd. (separate logistics division)    :2001-02-01, 1y
        Hansalim Producers Association (relaunch)   :2003-02-01, 8y
    section Regional Organisations (Seoul)
        Hansalim Nongsan    :1986-12-01, 2y
        Hansalim Communities Consumer Coop   :1988-04-01, 5y
        Hansalim Life Coop  :1993-02-01, 10y
        Hansalim Corporation    :1994-02-01, 7y
        Paju Life Coop  :2003-01-01, 20y
        Seoul Life Coop :2003-11-01, 20y
        Gyeonggi South Life Coop    :2005-11-01, 18y
        Seongnam Yongin Life Coop   :2006-11-01, 17y
    section Regional Organisations (non-Seoul)
        Wonju Union :1985-01-01, 3y
        Gyeongnam Union :1986-01-01, 5y
        Gwangju Hansalim  :1988-01-01, 36y
        Cheungju Hansalim   :1989-01-01, 35y
        Daegu Hansalim  :1989-01-01, 35y
        Wonju Hansalim  :1990-01-01, 34y
        Gyeongnam Hansalim  :1991-01-01, 33y
        Busan Hansalim  :2000-01-01, 24y
        Cheonan Asan    :2002-01-01, 22y
        Ulsan Hansalim  :2003-01-01, 21y
        Cheonan South   :2004-01-01, 20y
        Chungju Jaecheon    :2004-01-01, 20y
        Yeoju Icheon Gwangju    :2004-01-01, 20y
        Gwangju Life Coop   :2004-01-01, 20y
        Cheonbuk :2005-01-01, 19y
        Jeju    :2008-01-01, 16y
        Gyeongbuk North :2011-01-01, 13y
        Gyeonggi Southwest  :2012-01-01, 12y
    section Support Organisations
        Hansalim Gathering  :1989-10-01, 3y
        Mosim and Salim Research Institute  :2002-02-01, 22y
</pre>
</div>
</div>
</div>
</div>
</section>
<section id="conclusion" class="level2" data-number="1.8">
<h2 data-number="1.8" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">1.8</span> Conclusion</h2>
<p>For those in Europe and other regions of the world outside Korea, Hansalim can appear to be a uniquely Korean phenomenon. “Surely, it is only the collectivist culture of Korea that makes such a community possible. It could never succeed in our hyper-individualist western societies.” But you must not forget that the two strongest influences on contemporary Korean culture are Confucianism and American consumerism. The former provided the rationale for a strictly hierarchical and patriarchal culture that dominated Korean society for several hundred years before the latter collided head on with it during the post-war period, giving rise to a uniquely oppressive mixture of competitive consumerism and rigid conformism.</p>
<p>It was in this context that Hansalim emerged as a concrete expression of the desire felt among many at the time for a different kind of society built upon equality, mutual respect and care for other humans and the nonhuman world. I have a feeling that this same desire has not gone away, but only deepened, not only among Koreans but equally among contemporary people in Europe and beyond.</p>
<p>However, no matter how much you desire to create something like Hansalim, managing such a large organization (or rather, federation of organisations) without a dictatorial head office but in a deliberative and democratic way is very, very hard work. If you were in it for the money, you would not do it like this. But for every member of Hansalim I have spoken to so far, its not about money, but about being part of a community dedicated to caring for each other and to creating a peaceful and thriving future for the world. So as a reader from outside Korea who aspires to transform food systems, you need to keep in mind that Hansalim’s success is mingled with failures and disappointments and comes at the cost of a great deal of personal sacrifice, collective conflict and agonising, trial and error and lots and lots and lots of ….. meetings. Just look again at <a href="#fig-federation" class="quarto-xref">Figure&nbsp;<span>1.5</span></a> and notice the number of committee members in the column for Life Coops!</p>
<p>Having said all that, even if you are prepared for such a challenge, I do not think it is possible to simply transplant Hansalim’s model to other countries. It has its own history and unique context from which it emerged and it is not a static model but an evolving community in a continual process of change.</p>
<p>But what is perhaps much more useful than a blueprint, is Hansalim’s story and the myriad stories of the people who practice Hansalim (as a verb). These stories carry the values of Hansalim, the spirit and emotion of Hansalim people and the experience of countless challenges and success that they faced along the way. These stories, more than anything else, carry the seeds that could produce new fruit in other contexts, as long as there are those with the determination to cultivate them.</p>
<p>To hear some of these stories, I am afraid you will have to wait a little longer for the rest of the book to be written and published. I’ll do my best to finish it as soon as possible! Each new chapter will be published here as soon as it is written.</p>
<p>And of course, it is a story without an ending. Which means, in all likelihood, there are those among you reading this book who will end up playing a role in it one way or another.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Burmeister2006-aa" class="csl-entry" role="listitem">
Burmeister, Larry L. <span>“Agricultural Cooperative Development and Change: A Window on South Korea’s Agrarian Transformation.”</span> In <em>Transformations in Twentieth Century Korea</em>, edited by Yun-Shik Chang and Steven Hugh Lee, 78–100. Routledge Advances in Korean Studies. Routledge, 2006. <a href="https://library.oapen.org/bitstream/handle/20.500.12657/24070/1006062.pdf?sequence=1#page=78">https://library.oapen.org/bitstream/handle/20.500.12657/24070/1006062.pdf?sequence=1#page=78</a>.
</div>
<div id="ref-Burmeister1987-zt" class="csl-entry" role="listitem">
———. <span>“The South Korean Green Revolution: Induced or Directed Innovation?”</span> <em>Econ. Dev. Cult. Change</em> 35, no. 4 (July 1987): 767–90. <a href="https://doi.org/10.1086/451621">https://doi.org/10.1086/451621</a>.
</div>
<div id="ref-Hansalim2017-qp" class="csl-entry" role="listitem">
Hansalim. <span>“Because of You We Live: Hansalim <span>30th</span> Anniversary White Paper.”</span> Seoul, Korea: Hansalim; Hansalim, 2017.
</div>
<div id="ref-Hansalim2021-tf" class="csl-entry" role="listitem">
———. <span>“Hansalim Annual Report 2021.”</span> Seoul, Korea: Hansalim; Hansalim, 2021.
</div>
<div id="ref-Hansalim2024-zt" class="csl-entry" role="listitem">
———. <span>“Hansalim Federation <span>14th</span> General Assembly Resource Book.”</span> Seoul, Korea: Hansalim Cooperative Federation; Hansalim, 2024.
</div>
<div id="ref-Hansalim2021-cy" class="csl-entry" role="listitem">
———. <em>Hansalim Manifesto (English Version)</em>. Mosim; Salim Research Institute, 2021.
</div>
<div id="ref-Hansalim2020-rw" class="csl-entry" role="listitem">
———. <em>Hansalim Meetings Protocol</em> (version 2020.6). Mosim; Salim Research Institute, 2020.
</div>
<div id="ref-Hansalim2018-zz" class="csl-entry" role="listitem">
———. <span>“The Meaning and Role of Hansalim’s Delegates.”</span> Report of the Policy Planning Committee, 2018.
</div>
<div id="ref-Hong2021-sc" class="csl-entry" role="listitem">
Hong, Yooinn. <span>“Regionally Divergent Roles of the South Korean State in Adopting Improved Crop Varieties and Commercializing Agriculture (<span>1960–1980</span>): A Case Study of Areas in Jeju and Jeollanamdo.”</span> <em>Agric. Human Values</em> 38, no. 4 (December 2021): 1161–79. <a href="https://doi.org/10.1007/s10460-021-10232-y">https://doi.org/10.1007/s10460-021-10232-y</a>.
</div>
<div id="ref-Hwang2021-dl" class="csl-entry" role="listitem">
Hwang, Kyung Moon. <em>A History of Korea</em>. 3rd Edition. London, England: Red Globe Press, 2021.
</div>
<div id="ref-Kim2017-xf" class="csl-entry" role="listitem">
Kim, Hyung-Mi. <span>“The Experience of the Consumer Co-Operative Movement in Korea: Its Break Off and Rebirth, <span>1919–2010</span>.”</span> In <em>A Global History of Consumer Co-Operation Since 1850</em>, edited by Mary Hilson, Silke Neunsinger, and Greg Patmore, 353–78. Brill, 2017. <a href="https://doi.org/10.1163/9789004336551\_020">https://doi.org/10.1163/9789004336551\_020</a>.
</div>
<div id="ref-Kim2019-dd" class="csl-entry" role="listitem">
Kim, Sam-Woong. <em>Biography of Jang Il-Soon: The Beautiful Life of Muwidang</em>. Edited by Muwidang People. Seoul, Korea: Dure, 2019.
</div>
<div id="ref-Kim2019-dh" class="csl-entry" role="listitem">
Kim, So-Nam. <span>“Cooperative and Life Movements in Wonju.”</span> In <em>100 Years of the Korean Co-Operative Movement Vol. 1</em>, edited by Seong-Bu Kim, Kim Chang-jin, Kim Ki-tae, Kim Hyeong-mi, Pak Bong-hui, Yeom Chan-hui, Yi Kyeong-ran, Jeong Kyu-ho, Lim Chae-do, and Han Seong-hoon, 253–85. Seoul, Korea: Autumn Morning, 2019.
</div>
<div id="ref-Kim2022-im" class="csl-entry" role="listitem">
Kim, Yi-Kyung. <span>“The Formation and Development of the Korean Cooperative Movement Under Japanese Colonial Rule - Focus on Concepts, Participants, and Solidarity.”</span> PhD thesis, SUNGKYUNKWAN UNIVERSITY (성균관대학교 일반대학원), 2022. <a href="http://www.riss.kr/search/detail/DetailView.do?p_mat_type=be54d9b8bc7cdb09&amp;control_no=dc834242f8ef0680ffe0bdc3ef48d419">http://www.riss.kr/search/detail/DetailView.do?p_mat_type=be54d9b8bc7cdb09&amp;control_no=dc834242f8ef0680ffe0bdc3ef48d419</a>.
</div>
<div id="ref-Lee2006-cw" class="csl-entry" role="listitem">
Lee, E-Wha. <em>Korea’s Pastimes and Customs: A Social History</em>. Paramus, New Jersey: Homa &amp; Sekey Books, 2006.
</div>
<div id="ref-Lee2020-ba" class="csl-entry" role="listitem">
Lee, S. <span>“Role of Social and Solidarity Economy in Localizing the Sustainable Development Goals.”</span> <em>Int. J. Sustainable Dev. World Ecol.</em> 27, no. 1 (January 2020): 65–71. <a href="https://doi.org/10.1080/13504509.2019.1670274">https://doi.org/10.1080/13504509.2019.1670274</a>.
</div>
<div id="ref-Seong2020-cv" class="csl-entry" role="listitem">
Seong, Haeyoung. <span>“<span class="nocase">The basis for coexistence found from within: The mystic universality and ethicality of Donghak (東學, Eastern learning)</span>.”</span> <em>Religions</em> 11, no. 5 (May 2020): 265. <a href="https://doi.org/10.3390/rel11050265">https://doi.org/10.3390/rel11050265</a>.
</div>
<div id="ref-Tsurumi1984-hq" class="csl-entry" role="listitem">
Tsurumi, E Patricia. <span>“Colonial Education in Korea and Taiwan.”</span> In <em>The Japanese Colonial Empire, 1895-1945</em>, edited by Ramon H Myers and Mark R Peattie, 275–311. Princeton University Press, 1984. <a href="https://play.google.com/store/books/details?id=HWbcDwAAQBAJ">https://play.google.com/store/books/details?id=HWbcDwAAQBAJ</a>.
</div>
<div id="ref-Yoon2024-gs" class="csl-entry" role="listitem">
Yoon, Hyeong-Geun. <span>“History of the Evolution of the Hansalim Composite Organisation.”</span> Research Report. Seoul, Korea: Mosim; Salim Research Institute; Hansalim, 2024.
</div>
<div id="ref-Yoon2004-dl" class="csl-entry" role="listitem">
Yoon, Hyunggeun, ed. <em>Salim’s Words</em>. Mosim and Salim. Seoul: Mosim; Salim Research Institute, 2004.
</div>
<div id="ref-Young2014-an" class="csl-entry" role="listitem">
Young, Carl F. <em>Eastern Learning and the Heavenly Way: The Tonghak and Chondogyo Movements and the Twilight of Korean Independence</em>. University of Hawai’i Press., 2014. <a href="http://www.jstor.com/stable/j.ctt13x1k6b.2">http://www.jstor.com/stable/j.ctt13x1k6b.2</a>.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>https://www.koreaherald.com/view.php?ud=20230524000525<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p><a href="#ref-Hwang2021-dl" role="doc-biblioref">Kyung Moon Hwang, <em>A History of Korea</em>, 3rd Edition (London, England: Red Globe Press, 2021)</a>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p><a href="#ref-Hansalim2017-qp" role="doc-biblioref">Hansalim, <span>“Because of You We Live: Hansalim <span>30th</span> Anniversary White Paper”</span> (Seoul, Korea: Hansalim; Hansalim, 2017)</a>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p><a href="#ref-Hansalim2024-zt" role="doc-biblioref">Hansalim, <span>“Hansalim Federation <span>14th</span> General Assembly Resource Book”</span> (Seoul, Korea: Hansalim Cooperative Federation; Hansalim, 2024)</a>.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p><a href="#ref-Hansalim2021-tf" role="doc-biblioref">Hansalim, <span>“Hansalim Annual Report 2021”</span> (Seoul, Korea: Hansalim; Hansalim, 2021)</a>.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p><a href="#ref-Hansalim2021-cy" role="doc-biblioref">Hansalim, <em>Hansalim Manifesto (English Version)</em> (Mosim; Salim Research Institute, 2021)</a>.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p><a href="#ref-Yoon2004-dl" role="doc-biblioref">Hyunggeun Yoon, ed., <em>Salim’s Words</em>, Mosim and Salim (Seoul: Mosim; Salim Research Institute, 2004)</a>.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p><a href="#ref-Hansalim2024-zt" role="doc-biblioref">Hansalim, <span>“Hansalim Federation <span>14th</span> General Assembly Resource Book”</span></a>.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p><a href="#ref-Hansalim2020-rw" role="doc-biblioref">Hansalim, <em>Hansalim Meetings Protocol</em>, version 2020.6 (Mosim; Salim Research Institute, 2020)</a>.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p><a href="#ref-Hansalim2017-qp" role="doc-biblioref">Hansalim, <span>“Because of You We Live”</span></a>.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p><a href="#ref-Hansalim2020-rw" role="doc-biblioref">Hansalim, <em>Hansalim Meetings Protocol</em></a>.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p><a href="#ref-Hansalim2018-zz" role="doc-biblioref">Hansalim, <span>“The Meaning and Role of Hansalim’s Delegates”</span> (Report of the Policy Planning Committee, 2018)</a>.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p><a href="#ref-Kim2019-dd" role="doc-biblioref">Sam-Woong Kim, <em>Biography of Jang Il-Soon: The Beautiful Life of Muwidang</em>, ed. Muwidang People (Seoul, Korea: Dure, 2019)</a>.<a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn14"><p><a href="#ref-Tsurumi1984-hq" role="doc-biblioref">E Patricia Tsurumi, <span>“Colonial Education in Korea and Taiwan,”</span> in <em>The Japanese Colonial Empire, 1895-1945</em>, ed. Ramon H Myers and Mark R Peattie (Princeton University Press, 1984), 275–311, <span>https://play.google.com/store/books/details?id=HWbcDwAAQBAJ</span></a>.<a href="#fnref14" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn15"><p><a href="#ref-Kim2017-xf" role="doc-biblioref">Hyung-Mi Kim, <span>“The Experience of the Consumer Co-Operative Movement in Korea: Its Break Off and Rebirth, <span>1919–2010</span>,”</span> in <em>A Global History of Consumer Co-Operation Since 1850</em>, ed. Mary Hilson, Silke Neunsinger, and Greg Patmore (Brill, 2017), 353–78, <span>https://doi.org/10.1163/9789004336551\_020</span></a>.<a href="#fnref15" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn16"><p><a href="#ref-Kim2017-xf" role="doc-biblioref">Kim</a>.<a href="#fnref16" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn17"><p><a href="#ref-Lee2006-cw" role="doc-biblioref">E-Wha Lee, <em>Korea’s Pastimes and Customs: A Social History</em> (Paramus, New Jersey: Homa &amp; Sekey Books, 2006)</a>.<a href="#fnref17" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn18"><p><a href="#ref-Lee2020-ba" role="doc-biblioref">S Lee, <span>“Role of Social and Solidarity Economy in Localizing the Sustainable Development Goals,”</span> <em>Int. J. Sustainable Dev. World Ecol.</em> 27, no. 1 (January 2020): 65–71, <span>https://doi.org/10.1080/13504509.2019.1670274</span></a>.<a href="#fnref18" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn19"><p><a href="#ref-Kim2017-xf" role="doc-biblioref">Kim, <span>“The Experience of the Consumer Co-Operative Movement in Korea,”</span> 2017</a>.<a href="#fnref19" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn20"><p><a href="#ref-Kim2022-im" role="doc-biblioref">Yi-Kyung Kim, <span>“The Formation and Development of the Korean Cooperative Movement Under Japanese Colonial Rule - Focus on Concepts, Participants, and Solidarity”</span> (PhD thesis, SUNGKYUNKWAN UNIVERSITY (성균관대학교 일반대학원), 2022), <span>http://www.riss.kr/search/detail/DetailView.do?p_mat_type=be54d9b8bc7cdb09&amp;control_no=dc834242f8ef0680ffe0bdc3ef48d419</span></a>.<a href="#fnref20" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn21"><p><a href="#ref-Burmeister2006-aa" role="doc-biblioref">Larry L Burmeister, <span>“Agricultural Cooperative Development and Change: A Window on South Korea’s Agrarian Transformation,”</span> in <em>Transformations in Twentieth Century Korea</em>, ed. Yun-Shik Chang and Steven Hugh Lee, Routledge Advances in Korean Studies (Routledge, 2006), 78–100, <span>https://library.oapen.org/bitstream/handle/20.500.12657/24070/1006062.pdf?sequence=1#page=78</span></a>.<a href="#fnref21" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn22"><p><a href="#ref-Kim2017-xf" role="doc-biblioref">Kim, <span>“The Experience of the Consumer Co-Operative Movement in Korea,”</span> 2017</a>.<a href="#fnref22" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn23"><p><a href="#ref-Kim2019-dh" role="doc-biblioref">So-Nam Kim, <span>“Cooperative and Life Movements in Wonju,”</span> in <em>100 Years of the Korean Co-Operative Movement Vol. 1</em>, ed. Seong-Bu Kim et al. (Seoul, Korea: Autumn Morning, 2019), 253–85</a>.<a href="#fnref23" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn24"><p><a href="#ref-Kim2019-dd" role="doc-biblioref">Kim, <em>Biography of Jang Il-Soon</em>, 2019, 133</a>.<a href="#fnref24" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn25"><p><a href="#ref-Kim2019-dh" role="doc-biblioref">Kim, <span>“Cooperative and Life Movements in Wonju”</span></a>.<a href="#fnref25" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn26"><p>Personal communication from a relative of a Wonju Hansalim founder.<a href="#fnref26" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn27"><p><a href="#ref-Kim2019-dd" role="doc-biblioref">Kim, <em>Biography of Jang Il-Soon</em>, 2019, 152</a>.<a href="#fnref27" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn28"><p><a href="#ref-Kim2019-dd" role="doc-biblioref">Kim, 135</a>.<a href="#fnref28" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn29"><p><a href="#ref-Kim2019-dd" role="doc-biblioref">Kim, 136</a>.<a href="#fnref29" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn30"><p><a href="#ref-Kim2019-dd" role="doc-biblioref">Kim, 165</a>.<a href="#fnref30" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn31"><p><a href="#ref-Kim2019-dd" role="doc-biblioref">Kim, <em>Biography of Jang Il-Soon</em>, 2019</a>.<a href="#fnref31" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn32"><p><a href="#ref-Kim2019-dd" role="doc-biblioref">Kim</a>.<a href="#fnref32" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn33"><p>Currently, 150,000 people, or 44% of Wonju’s population of 360,000, are credit union members.<a href="#fnref33" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn34"><p><a href="#ref-Burmeister1987-zt" role="doc-biblioref">Larry L Burmeister, <span>“The South Korean Green Revolution: Induced or Directed Innovation?”</span> <em>Econ. Dev. Cult. Change</em> 35, no. 4 (July 1987): 767–90, <span>https://doi.org/10.1086/451621</span></a>.<a href="#fnref34" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn35"><p><a href="#ref-Hong2021-sc" role="doc-biblioref">Yooinn Hong, <span>“Regionally Divergent Roles of the South Korean State in Adopting Improved Crop Varieties and Commercializing Agriculture (<span>1960–1980</span>): A Case Study of Areas in Jeju and Jeollanamdo,”</span> <em>Agric. Human Values</em> 38, no. 4 (December 2021): 1161–79, <span>https://doi.org/10.1007/s10460-021-10232-y</span></a>.<a href="#fnref35" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn36"><p><a href="#ref-Kim2019-dd" role="doc-biblioref">Kim, <em>Biography of Jang Il-Soon</em>, 2019</a>.<a href="#fnref36" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn37"><p>Quoted in, <a href="#ref-Kim2019-dd" role="doc-biblioref">Kim, 260–61</a>, translation J. Dolley.<a href="#fnref37" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn38"><p><a href="#ref-Young2014-an" role="doc-biblioref">Carl F Young, <em>Eastern Learning and the Heavenly Way: The Tonghak and Chondogyo Movements and the Twilight of Korean Independence</em> (University of Hawai’i Press., 2014), <span>http://www.jstor.com/stable/j.ctt13x1k6b.2</span></a>.<a href="#fnref38" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn39"><p><a href="#ref-Seong2020-cv" role="doc-biblioref">Haeyoung Seong, <span>“<span class="nocase">The basis for coexistence found from within: The mystic universality and ethicality of Donghak (東學, Eastern learning)</span>,”</span> <em>Religions</em> 11, no. 5 (May 2020): 265, <span>https://doi.org/10.3390/rel11050265</span></a>.<a href="#fnref39" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn40"><p><a href="#ref-Kim2019-dd" role="doc-biblioref">Kim, <em>Biography of Jang Il-Soon</em>, 2019, 197–98</a>.<a href="#fnref40" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn41"><p>Kim Ji-ha, ‘On the Tilted Balance,’ The Complete Works of Kim Ji-ha, Volume 2, Practical Literature, 2002. Reproduced in: Yoon, Hyunggeun, ed.&nbsp;2004. Salim’s Words. Mosim and Salim, Book 3. Seoul: Mosim and Salim Research Institute. p.&nbsp;184-185. (Translation: J Dolley).<a href="#fnref41" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn42"><p><a href="#ref-Yoon2024-gs" role="doc-biblioref">Hyeong-Geun Yoon, <span>“History of the Evolution of the Hansalim Composite Organisation,”</span> Research Report (Seoul, Korea: Mosim; Salim Research Institute; Hansalim, 2024)</a>, translation by J. Dolley.<a href="#fnref42" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn43"><p>Kim Ji-ha, ‘On the Tilted Balance,’ The Complete Works of Kim Ji-ha, Volume 2, Practical Literature, 2002. Reproduced in: Yoon, Hyunggeun, ed.&nbsp;2004. Salim’s Words. Mosim and Salim, Book 3. Seoul: Mosim and Salim Research Institute. p.&nbsp;182. (Translation: J Dolley).<a href="#fnref43" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="JonathanDolley/book.livingtogether.xyz" data-repo-id="R_kgDONLJrgQ" data-category="General" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script>
<input type="hidden" id="giscus-base-theme" value="light">
<input type="hidden" id="giscus-alt-theme" value="dark">
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../intro.html" class="pagination-link" aria-label="Introduction">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Introduction</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/references.html" class="pagination-link" aria-label="Bibliography">
        <span class="nav-page-text">Bibliography</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2024 Jonathan Dolley</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://livingtogether.xyz">
<p>livingtogether.xyz</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/JonathanDolley/book.livingtogether.xyz">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>