<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>1&nbsp; What is Hansalim? – Hansalim: the universe in a bowl of rice.</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/02_fromwhence.html" rel="next">
<link href="../intro.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2486e1f0a3ee9ee1fc393803a1361cdb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-af34e1d557ac5910fc8d786d44d80f7c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="../site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">
<script src="../site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="../site_libs/plotly-binding-4.10.4/plotly.js"></script>
<script src="../site_libs/typedarray-0.1/typedarray.min.js"></script>
<script src="../site_libs/jquery-3.5.1/jquery.min.js"></script>
<link href="../site_libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet">
<script src="../site_libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<link href="../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="../site_libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/01_whatisit.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What is Hansalim?</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Hansalim: the universe in a bowl of rice.</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01_whatisit.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What is Hansalim?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02_fromwhence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Beginnings</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/01_farming_blog.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Hansalim Farming is Different</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/02_illustrated_farming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Illustrated Hansalim Farming Methods</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#a-movement-a-manifesto-a-business" id="toc-a-movement-a-manifesto-a-business" class="nav-link active" data-scroll-target="#a-movement-a-manifesto-a-business"><span class="header-section-number">1.1</span> A movement, a manifesto, a business</a></li>
  <li><a href="#built-on-a-relationship-of-mutual-care" id="toc-built-on-a-relationship-of-mutual-care" class="nav-link" data-scroll-target="#built-on-a-relationship-of-mutual-care"><span class="header-section-number">1.2</span> Built on a relationship of mutual care</a></li>
  <li><a href="#in-the-form-of-a-multistakeholder-cooperative" id="toc-in-the-form-of-a-multistakeholder-cooperative" class="nav-link" data-scroll-target="#in-the-form-of-a-multistakeholder-cooperative"><span class="header-section-number">1.3</span> In the form of a multistakeholder cooperative</a></li>
  <li><a href="#creating-an-alternative-economy" id="toc-creating-an-alternative-economy" class="nav-link" data-scroll-target="#creating-an-alternative-economy"><span class="header-section-number">1.4</span> Creating an alternative economy</a>
  <ul class="collapse">
  <li><a href="#a-system-designed-for-producers" id="toc-a-system-designed-for-producers" class="nav-link" data-scroll-target="#a-system-designed-for-producers">A system designed for producers</a></li>
  <li><a href="#a-different-kind-of-consumer-experience" id="toc-a-different-kind-of-consumer-experience" class="nav-link" data-scroll-target="#a-different-kind-of-consumer-experience">A different kind of consumer experience</a></li>
  <li><a href="#the-special-role-of-practitioners" id="toc-the-special-role-of-practitioners" class="nav-link" data-scroll-target="#the-special-role-of-practitioners">The special role of practitioners</a></li>
  </ul></li>
  <li><a href="#governed-through-deliberative-democracy" id="toc-governed-through-deliberative-democracy" class="nav-link" data-scroll-target="#governed-through-deliberative-democracy"><span class="header-section-number">1.5</span> Governed through deliberative democracy</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">1.6</span> Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What is Hansalim?</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In 1986 pro-democracy protesters were out in the streets fighting with police and trying to escape tear gas.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Since seizing power in a military coup in 1961, General Park Chung-hee presided over 18 years of military rule. Following his assassination in 1979 and another coup, General Chun Doo-hwan installed himself as president, leading what was essentially a continuation of the military regime in the face of growing mass protests calling for democratic government.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>In the midst of such turmoil, a small group of farmers and housewives opened a small rice store in the centre of Seoul. In light of the chaotic political situation, this looked like a foolish and insignificant action. However, the creation of that first store, called Hansalim Nongsan, was actually a radical act of resistance and hope in the face of political uncertainty. The men and women who opened Hansalim Nongsan belonged to a small cooperative of producers and consumers in a city called Wonju, about an hour away from Seoul, and that store represented a first step in launching an ecological alternative movement that had been gathering support in Wonju and beyond since the late 1970s. It’s founders where known as the Wonju Group.</p>
<section id="a-movement-a-manifesto-a-business" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="a-movement-a-manifesto-a-business"><span class="header-section-number">1.1</span> A movement, a manifesto, a business</h2>
<p>The Wonju Group were a diverse collection of Catholic Farmers, urban housewives, pro-democracy activists, artists, poets and scholars who had been involved in the credit union movement in Wonju that was founded in the 1960s. They had witnessed the fundamentally destructive tendencies of capitalist and socialist industrialisation and they were looking for an alternative in the cooperative movement. However, they recognised that cooperatives were also vulnerable to the same fundamental mistake that lay at the heart of industrial civilization. That mistake was to assume a materialist, mechanistic view of the world which viewed humans and all life as replaceable parts in the machine of economic growth. It was this worldview, they argued, that gave rise to the characteristics of domination, alienation, separation and oppression in modern society.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Hansalim-Moim.jpeg" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="The Wonju Group with the Hansalim Gathering (1989)"><img src="../images/chapter_01/Hansalim-Moim.jpeg" class="img-fluid figure-img" alt="The Wonju Group with the Hansalim Gathering (1989)"></a></p>
<figcaption>The Wonju Group with the Hansalim Gathering (1989)</figcaption>
</figure>
</div>
<p>As an alternative, they proposed a worldview founded on the sacredness and interconnectedness of all life. The first version of this worldview or eco-philosophy was outlined in the Wonju Report in 1982. As the movement began to grow the Wonju Group set up the first Life Cooperative in Wonju in 1985 and the Hansalim Nongsan rice store a year later.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> In this way, the Wonju Coop formally brought together organic farming and direct trade with the equal participation of consumers and producers. Soon after, the Hansalim Community Consumers Union was set-up in Seoul with 70 members to trade directly with the Hansalim Producers Association that was set up with 70 farming households. Next, the Wonju Group hosted a year long process of study and discussion to develop the Hansalim Manifesto which was published in 1989 and which formally launched the Hansalim Life Movement.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Hansalim-Manifesto.jpeg" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="The Hansalim Manifesto, English version"><img src="../images/chapter_01/Hansalim-Manifesto.jpeg" class="img-fluid figure-img" alt="The Hansalim Manifesto, English version"></a></p>
<figcaption>The Hansalim Manifesto, English version</figcaption>
</figure>
</div>
<p>From this small beginning, the movement quickly expanded as other cooperatives and farming communities joined from across the country and consumer membership grew. By 1990 there were four Life Cooperatives with over 5,500 members and within just over another 10 years membership had grown to over 40,000. That is when things really began to take off and by 2008 there were 19 Life Cooperatives managing 84 stores for their 170,000 members. In 2023 Hansalim’s 27 Life Cooperatives and 15 Producer Federations handled annual sales of 485,066 million KRW (324.3 million euros) through 240 stores, an online store and a mobile app.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> From these sales, 330,610 million KRW (221 million euros) were returned to the 136 producer communities. That is nearly 70%! So what kind of business model has Hansalim created that provides those returns to producers while covering the shared business operations and funding a whole range of movement activities from the remaining 30%? And what lies at the heart of this unusual way of doing business?</p>
<p>(Graph of growth)</p>
</section>
<section id="built-on-a-relationship-of-mutual-care" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="built-on-a-relationship-of-mutual-care"><span class="header-section-number">1.2</span> Built on a relationship of mutual care</h2>
<p>At its simplest, the Hansalim Life Movement is a relationship of mutual care and responsibility between rural and urban communities. The core of Hansalim’s approach is expressed in this phrase: “Let the producer take responsibility for sustaining the consumer’s life and the consumer for sustaining the producer’s livelihood”.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> However, this mutual responsibility is about much more than simply direct sales as it also encompasses a shared commitment to protecting and restoring ecosystems and working for wider social and cultural change towards justice and peace.</p>
<p>This expansive goal is captured by the name itself: “Hansalim” (한살림).</p>
<p>The first part of the word, ‘Han’ (한) contains two sets of paradoxical meanings. It expresses, firstly, a paradoxical double sense of being collectively one and individually one and, secondly, of spreading out as one and gathering in as one.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> In ancient Korean philosophy ‘Han’ refers to the divine Spirit or life of the universe which permeates all things living and inanimate and integrates the universe into an evolving cosmos.</p>
<p>The word ‘Salim’ (살림) has two related meanings. The first is ‘housekeeping’ which implies parental care, homemaking, food preparation, hospitality. It is perhaps the most practical of all human activities and is the bedrock of human survival and flourishing. The second meaning develops from this practical sense the philosophical concept of ‘nurturing’ which has the connotation of saving and restoring, bringing back to life, vivifying.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></p>
<p>So we see that the word ‘Hansalim’ expresses a relationship and an action. It encompasses the goal of nurturing or reviving all things, that is bringing all into a flourishing shared life together. In fact, the word ‘Hansalim’ is often used as a verb as when members encourage each other by saying “let’s Hansalim!”</p>
<p>Among Hansalim members, the word “Salim” is used to express their purpose in all their activities. So the collective mission of Hansalim is summed up in four phrases that each incorporate this word Salim.</p>
<p>The first, ‘Nurturing Food’ (밥상살림 — bapsang-salim) refers to the goal of providing consumers with safe, healthy, eco-friendly food and other household goods and this defines the responsibility that producers adopt for the life of consumers. The word in Korean directly translates as nurturing the dining table and the significance of this is that it refers to the act of sharing a meal, not simply consuming food. Second, ‘Nurturing Agriculture’ (농업살림 — nongup-salim) refers to the goal of securing stable and sustainable livelihoods for producers and this defines the responsibility which consumers adopt for the livelihoods of producers. Third, ‘Nurturing Life’ (생명살림 — saengmyeong-salim) expresses the responsibility of care for others (human and non-human) which producers and consumers together share and which is worked out through outward focused activities such as promoting eco-friendly farming, environmental campaigning, education, social welfare projects, and inward contemplative and reflective practices. Finally, ‘Nurturing Community’ (지역살림 — jiyeok-salim), emphasises the need to strengthen local community resources and relationships and to reach out to neighbours in need.</p>
<p>So how these values put into practice? I’m going to tackle this question from bottom up, first from the rural or producer perspective and then from the urban or consumer perspective before describing the alternative economic system that brings them together.</p>
</section>
<section id="in-the-form-of-a-multistakeholder-cooperative" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="in-the-form-of-a-multistakeholder-cooperative"><span class="header-section-number">1.3</span> In the form of a multistakeholder cooperative</h2>
<p>The producer community is the smallest level of organization in Hansalim. In these communities farming is done together by a group of family farms who partner with one another to plan and coordinate their production, share knowledge and labour, and manage shared facilities and equipment. To join Hansalim as a producer, you would join one of these communities and receive training in eco-friendly farming and Hansalim’s production and processing standards.</p>
<p>There are 136 producer communities which cultivate a total of 11,300 acres. In addition to the producer communities there are 110 processing units which process raw materials from Hansalim’s producers as well as seafood and other products from local organic and environmentally friendly sources.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> The producer organizations are brought together into 15 regional federations with their own elected representatives which together form Hansalim’s National Producer Federation with their own elected president and employed staff. Many of these regional federations pool resources to run local distribution hubs with their own processing facilities and some have created complex systems to process and re-circulate farm wastes as inputs between multiple local farms.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Byeonsan-Farm.jpeg" class="lightbox" data-gallery="producers" title="Hansalim Producer Community in Byeonsan"><img src="../images/chapter_01/Byeonsan-Farm.jpeg" class="img-fluid figure-img" alt="Hansalim Producer Community in Byeonsan"></a></p>
<figcaption>Hansalim Producer Community in Byeonsan</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Byeonsan-Producer-Community.jpeg" class="lightbox" data-gallery="producers" title="Byeonsan Producer Community shared facilities"><img src="../images/chapter_01/Byeonsan-Producer-Community.jpeg" class="img-fluid figure-img" alt="Byeonsan Producer Community shared facilities"></a></p>
<figcaption>Byeonsan Producer Community shared facilities</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Jeju-Producer-Community.jpeg" class="lightbox" data-gallery="producers" title="Hansalim Producer Community in Jeju, head office"><img src="../images/chapter_01/Jeju-Producer-Community.jpeg" class="img-fluid figure-img" alt="Hansalim Producer Community in Jeju, head office"></a></p>
<figcaption>Hansalim Producer Community in Jeju, head office</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Asan-Distribution-Centre.jpeg" class="lightbox" data-gallery="producers" title="Hansalim Producer Community in Asan, distribution hub"><img src="../images/chapter_01/Asan-Distribution-Centre.jpeg" class="img-fluid figure-img" alt="Hansalim Producer Community in Asan, distribution hub"></a></p>
<figcaption>Hansalim Producer Community in Asan, distribution hub</figcaption>
</figure>
</div>
<p>When you join Hansalim as a consumer you become a member of your local Life Cooperative (one among 27 as of 2024). The word “Life” is significant because these cooperatives are not like the conventional consumer cooperatives that you would encounter in Europe or America. Their focus is not only responsible consumption but also seeking to live together in solidarity with one another and with producers and rural communities. Each Life Cooperative in Hansalim is a democratic autonomous organization formed by members to carry out collective activities, set-up and run Hansalim stores, organize charitable, cultural and educational activities and the joint activities between rural producers and urban consumers.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Jeju-Hansalim-Office.jpeg" class="lightbox" data-gallery="consumers" title="Jeju Hansalim Life Coop office"><img src="../images/chapter_01/Jeju-Hansalim-Office.jpeg" class="img-fluid figure-img" alt="Jeju Hansalim Life Coop office"></a></p>
<figcaption>Jeju Hansalim Life Coop office</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Jeju-Hansalim-Kitchen.jpeg" class="lightbox" data-gallery="consumers" title="Jeju Hansalim community kitchen"><img src="../images/chapter_01/Jeju-Hansalim-Kitchen.jpeg" class="img-fluid figure-img" alt="Jeju Hansalim community kitchen"></a></p>
<figcaption>Jeju Hansalim community kitchen</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Jeju-Hansalim-Community-Garden.jpeg" class="lightbox" data-gallery="consumers" title="Jeju Hansalim community permaculture garden"><img src="../images/chapter_01/Jeju-Hansalim-Community-Garden.jpeg" class="img-fluid figure-img" alt="Jeju Hansalim community permaculture garden"></a></p>
<figcaption>Jeju Hansalim community permaculture garden</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Busan-Hansalim-Kitchen.jpg" class="lightbox" data-gallery="consumers" title="Busan Hansalim community kitchen"><img src="../images/chapter_01/Busan-Hansalim-Kitchen.jpg" class="img-fluid figure-img" alt="Busan Hansalim community kitchen"></a></p>
<figcaption>Busan Hansalim community kitchen</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Busan-Hansalim-Office.jpg" class="lightbox" data-gallery="consumers" title="Busan Hansalim Life Coop office"><img src="../images/chapter_01/Busan-Hansalim-Office.jpg" class="img-fluid figure-img" alt="Busan Hansalim Life Coop office"></a></p>
<figcaption>Busan Hansalim Life Coop office</figcaption>
</figure>
</div>
<p>Together, the producer communities and federations and the Life Coops form a federation of cooperatives, associations and businesses linked together through a shared business federation and the Hansalim Federation with its support organisations including a research institute, charitable foundation, solar power coop, publishing house, training institute and peer-to-peer finance platform. So how does this business work?</p>
</section>
<section id="creating-an-alternative-economy" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="creating-an-alternative-economy"><span class="header-section-number">1.4</span> Creating an alternative economy</h2>
<p>In simple terms, the Hansalim business model can be described as a contract-based direct sales arrangement in which prices and quantities are agreed annually in advance by producers and consumers with support from Hansalim’s professional staff. However, it is also very flexible in ways that are designed to support the needs of producers.</p>
<section id="a-system-designed-for-producers" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="a-system-designed-for-producers">A system designed for producers</h3>
<p>There are four key features of Hansalim’s business model. Firstly: flexibility of production. Hansalim’s production system allows for a relatively wide range of production philosophies and techniques among member producers to ensure that producers have maximum autonomy. For example, one producer community might prefer a relatively simple style of organic farming with a small number of crops while another aspires to build a complex system of circulating agriculture with a large diversity of crops and livestock supported by recycling of farm wastes from one part of the system as inputs to others. Still others, especially fruit producers, might find it impossible to grow without a limited use of safe pesticides. A dogmatic insistence on a single farming philosophy would exclude many farmers who might be unable to follow a one-size-fits-all system in the face of local conditions or other resource constraints. Hansalim’s more flexible approach removes a significant barrier to entry for farmers who would otherwise need to spend a long time learning new techniques before starting to earn an income. This brings the added advantage that farmers who want to transition from conventional to organic farming can do so in a staged process while still making a living. However, it also creates a problem. How to maintain the trust of consumers when the diversity of production techniques is so wide?</p>
<p>This brings us to the second feature of Hansalim’s business model: simple and honest labeling. Transparency with consumer members is ensured through Hansalim’s own labelling system. Products are labelled under four main categories:</p>
<ol type="1">
<li>Organic (which would include conventional organic, permaculture and EM techniques);</li>
<li>Pesticide-free (when crop types and local conditions make it non-viable to exclude use of fertilizers);</li>
<li>Low pesticide (for certain fruit crops which would be prohibitively difficult to grow without a limited use of pesticides);</li>
<li>Domestic (for miscellaneous grains such as wheat or barley which are used as raw ingredients in some processed goods).</li>
</ol>
<p>For all four categories Hansalim’s standards are stricter than the national safety standards and products are tested regularly for residues, contaminants and radiation as appropriate to protect trust between consumers and producers.</p>
<p>To complement the flexibility and transparency of production methods the third feature - flexibility of supply - enhances the autonomy of producers and provides some added resilience to the system. Hansalim producers are not locked-in to exclusive supply contracts but have the freedom to supply whatever proportion of their crop to Hansalim they wish while simultaneously supplying through other channels such as government purchasing schemes for school meals. This applies to each producer community and also to each member of each community. So one farmer might supply 30% of their produce to Hansalim through their community while selling the rest through local government procurement for school meals. Or a producer community might sell Hansalim branded grapes through the Hansalim Federation while selling grape juice through another market under their own brand.</p>
<p>Finally, for an additional level of flexibility, the contract-based system is supplemented by demand-based supply arrangements to allow greater flexibility for producers.</p>
<p>Taken together, these four features of Hansalim’s business model mean that, within and between producer communities the level of specialization or circular integration and the combination of sales channels are all decided by the producers themselves. This makes for an astonishingly diverse range of production operations each tailored to the local soil and climate conditions and preferences of producers themselves, while ensuring a stable guaranteed income to as many farmers as possible.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Our-Seed-Farm-Rice-Hansalim.jpeg" class="lightbox" data-gallery="farms" title="The word ‘Hansalim’ written in life alongside a rice paddy on Our Seed Farm in Goesan"><img src="../images/chapter_01/Our-Seed-Farm-Rice-Hansalim.jpeg" class="img-fluid figure-img" alt="The word ‘Hansalim’ written in life alongside a rice paddy on Our Seed Farm in Goesan"></a></p>
<figcaption>The word ‘Hansalim’ written in life alongside a rice paddy on Our Seed Farm in Goesan</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Our-Seed-Farm-Rice-Terrace.jpeg" class="lightbox" data-gallery="farms" title="Rice terraces on Our Seed Farm in Goesan"><img src="../images/chapter_01/Our-Seed-Farm-Rice-Terrace.jpeg" class="img-fluid figure-img" alt="Rice terraces on Our Seed Farm in Goesan"></a></p>
<figcaption>Rice terraces on Our Seed Farm in Goesan</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Rice-Field.jpeg" class="lightbox" data-gallery="farms" title="A lowland rice paddy"><img src="../images/chapter_01/Rice-Field.jpeg" class="img-fluid figure-img" alt="A lowland rice paddy"></a></p>
<figcaption>A lowland rice paddy</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Paju-Rice-Planting.jpeg" class="lightbox" data-gallery="farms" title="Planting out rice seedlings with a Hansalim producer community in Paju"><img src="../images/chapter_01/Paju-Rice-Planting.jpeg" class="img-fluid figure-img" alt="Planting out rice seedlings with a Hansalim producer community in Paju"></a></p>
<figcaption>Planting out rice seedlings with a Hansalim producer community in Paju</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Our-Seed-Farm-Greenhouse-1.jpeg" class="lightbox" data-gallery="farms" title="Vinyl house (polytunnel greenhouse) crops at Our Seed Farm in Goesan"><img src="../images/chapter_01/Our-Seed-Farm-Greenhouse-1.jpeg" class="img-fluid figure-img" alt="Vinyl house (polytunnel greenhouse) crops at Our Seed Farm in Goesan"></a></p>
<figcaption>Vinyl house (polytunnel greenhouse) crops at Our Seed Farm in Goesan</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Okcheon-Grapes.jpeg" class="lightbox" data-gallery="farms" title="Grapes growing in a vinyl house at a Hansalim producer community in Okcheon"><img src="../images/chapter_01/Okcheon-Grapes.jpeg" class="img-fluid figure-img" alt="Grapes growing in a vinyl house at a Hansalim producer community in Okcheon"></a></p>
<figcaption>Grapes growing in a vinyl house at a Hansalim producer community in Okcheon</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Nunbisan-Vegetables.jpeg" class="lightbox" data-gallery="farms" title="A vegetable field at Nunbisan, a Hansalim producer community in Goesan"><img src="../images/chapter_01/Nunbisan-Vegetables.jpeg" class="img-fluid figure-img" alt="A vegetable field at Nunbisan, a Hansalim producer community in Goesan"></a></p>
<figcaption>A vegetable field at Nunbisan, a Hansalim producer community in Goesan</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Nunbisan-Oats.jpeg" class="lightbox" data-gallery="farms" title="A field of oats at Nunbisan grown for chicken feed and as an ingredient for making various types of Hansalim products that are processed on site"><img src="../images/chapter_01/Nunbisan-Oats.jpeg" class="img-fluid figure-img" alt="A field of oats at Nunbisan grown for chicken feed and as an ingredient for making various types of Hansalim products that are processed on site"></a></p>
<figcaption>A field of oats at Nunbisan grown for chicken feed and as an ingredient for making various types of Hansalim products that are processed on site</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Nunbisan-Homemade-Fertilizer.jpeg" class="lightbox" data-gallery="farms" title="Making home made organic fertilizer from Chicken faeces and crop waste on Nunbisan farm"><img src="../images/chapter_01/Nunbisan-Homemade-Fertilizer.jpeg" class="img-fluid figure-img" alt="Making home made organic fertilizer from Chicken faeces and crop waste on Nunbisan farm"></a></p>
<figcaption>Making home made organic fertilizer from Chicken faeces and crop waste on Nunbisan farm</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Nunbisan-Field-2.jpeg" class="lightbox" data-gallery="farms" title="A green manure cover crop at Nunbisan"><img src="../images/chapter_01/Nunbisan-Field-2.jpeg" class="img-fluid figure-img" alt="A green manure cover crop at Nunbisan"></a></p>
<figcaption>A green manure cover crop at Nunbisan</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Nunbisan-Chicken-Sheds-2.jpeg" class="lightbox" data-gallery="farms" title="Chicken sheds on Nunbisan farm"><img src="../images/chapter_01/Nunbisan-Chicken-Sheds-2.jpeg" class="img-fluid figure-img" alt="Chicken sheds on Nunbisan farm"></a></p>
<figcaption>Chicken sheds on Nunbisan farm</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Nunbisan-Chicken-Sheds-3.jpeg" class="lightbox" data-gallery="farms" title="Inside Nunbisan’s chicken sheds"><img src="../images/chapter_01/Nunbisan-Chicken-Sheds-3.jpeg" class="img-fluid figure-img" alt="Inside Nunbisan’s chicken sheds"></a></p>
<figcaption>Inside Nunbisan’s chicken sheds</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Mushrooms.jpeg" class="lightbox" data-gallery="farms" title="Growing mushrooms on a Hansalim farm"><img src="../images/chapter_01/Mushrooms.jpeg" class="img-fluid figure-img" alt="Growing mushrooms on a Hansalim farm"></a></p>
<figcaption>Growing mushrooms on a Hansalim farm</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Jeju-Orchard.jpeg" class="lightbox" data-gallery="farms" title="An orchard on a Hansalim farm on Jeju Island"><img src="../images/chapter_01/Jeju-Orchard.jpeg" class="img-fluid figure-img" alt="An orchard on a Hansalim farm on Jeju Island"></a></p>
<figcaption>An orchard on a Hansalim farm on Jeju Island</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Byeonsan-Field-1.jpeg" class="lightbox" data-gallery="farms" title="Lowland farming at the foot of a mountain in Byeonsan at the Sandle-pada Hansalim Producer Community"><img src="../images/chapter_01/Byeonsan-Field-1.jpeg" class="img-fluid figure-img" alt="Lowland farming at the foot of a mountain in Byeonsan at the Sandle-pada Hansalim Producer Community"></a></p>
<figcaption>Lowland farming at the foot of a mountain in Byeonsan at the Sandle-pada Hansalim Producer Community</figcaption>
</figure>
</div>
<p>These images show just a tiny snapshot of some of the different farming landscapes, crops and approaches which form Hansalim’s complex agricultural systems. The system of labelling helps provide a sense of order to this complexity for the sake of Hansalim’s consumer members and also facilitates the progression of Hansalim producers further away from conventional farming methods towards progressively more eco-friendly alternatives. Let’s look at the overall share of production according to production type, crop type and supply type. The following graph shows the flow of goods by tons.</p>
<div class="cell">
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item" id="htmlwidget-0d6731581b2cd819ddb6" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-0d6731581b2cd819ddb6">{"x":{"visdat":{"47613bd579e3":["function () ","plotlyVisDat"]},"cur_data":"47613bd579e3","attrs":{"47613bd579e3":{"orientation":"h","node":{"label":["Organic","Pesticide-free","Low-pesticide","Domestic","Staple grains","Misc grains","Roots and Tubers","Vegetables","Fruit","Contract","Demand"],"color":["darkgreen","green","lightgreen","aquamarine","brown","darkorange","yellow","green","red","darkgrey","lightgrey"],"pad":15,"thickness":20,"line":{"color":"black","width":0.5}},"link":{"source":[0,1,2,3,0,1,2,3,0,1,2,3,0,1,2,3,0,1,2,3,4,4,5,5,6,6,7,7,8,8],"target":[4,4,4,4,5,5,5,5,6,6,6,6,7,7,7,7,8,8,8,8,9,10,9,10,9,10,9,10,9,10],"value":[4930,509,0,0,661,783,0,1748,697,292,0,0,8336,2408,0,0,1393,498,2139,0,5439,0,271,2921,989,0,10090,654,3898,132]},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"sankey"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"","font":{"size":12},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"orientation":"h","node":{"label":["Organic","Pesticide-free","Low-pesticide","Domestic","Staple grains","Misc grains","Roots and Tubers","Vegetables","Fruit","Contract","Demand"],"color":["darkgreen","green","lightgreen","aquamarine","brown","darkorange","yellow","green","red","darkgrey","lightgrey"],"pad":15,"thickness":20,"line":{"color":"black","width":0.5}},"link":{"source":[0,1,2,3,0,1,2,3,0,1,2,3,0,1,2,3,0,1,2,3,4,4,5,5,6,6,7,7,8,8],"target":[4,4,4,4,5,5,5,5,6,6,6,6,7,7,7,7,8,8,8,8,9,10,9,10,9,10,9,10,9,10],"value":[4930,509,0,0,661,783,0,1748,697,292,0,0,8336,2408,0,0,1393,498,2139,0,5439,0,271,2921,989,0,10090,654,3898,132]},"type":"sankey","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>Figure 1. Flow of production quantities by type, crop and contract in 2023 (tons)</p>
</div>
</div>
<p>On the left you can see the four labelled production types of <strong><em>organic</em></strong>, <strong><em>pesticide-free</em></strong>, <strong><em>low-pesticide</em></strong> and <strong><em>domestic</em></strong>. In the centre, the crop types are divided into <strong><em>vegetables</em></strong>, <strong><em>staple grains</em></strong>, <strong><em>roots and tubers</em></strong>, <strong><em>fruit</em></strong>, and <strong><em>miscellaneous grains</em></strong>. On the right, crop types are categorized into supply type as either <strong><em>contract-based</em></strong> or <strong><em>demand-based</em></strong> supply. If you interact with the graph you can see the number of tons of each combination. The majority of production is organic and this accounts for most of the vegetable cultivation, almost all staple grains and root and tubers. These crop types are almost entirely supplied on a contract-basis. Pesticide-free production accounts for some vegetable supply, a fraction of staple grains and some fruit crops. It is in fruit cultivation that higher proportion of crops are cultivated according to ‘low-pesticide’ standards. This is because many fruit crops are especially vulnerable to pests and would no be viable for producers without some use of non-synthetic pesticides. Miscellaneous grains are mostly produced under the domestic label and supplied on a demand-basis.</p>
<p>So what happens to the revenue from these sales? As I mentioned above, until recently, with margins well below 30%, Hansalim was able to return 73% or more of the product price to the producers. Now, following several years of rising costs and worsening impacts of climate change the margin has come under increasing pressure and currently stands at just over 31% which leaves almost 69% for producers. This table shows the breakdown of what the margin covers.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Division</th>
<th>Rate</th>
<th>Subdivision</th>
<th>Rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Hansalim Federation</td>
<td>0.81%</td>
<td>Subscription fees<br>Service revenue</td>
<td>0.55%<br>0.26%</td>
</tr>
<tr class="even">
<td>Hansalim Business Federation</td>
<td>8.86%</td>
<td>Business share rate<br>Production Support Fund<br>Price Stabilisation Fund</td>
<td>8.61%<br>0.165%<br>0.085%</td>
</tr>
<tr class="odd">
<td>Member Life Coops</td>
<td>21.70%</td>
<td>Regional Margin Rate <br>Production Stabilisation Fund</td>
<td>21.60%<br>0.10%</td>
</tr>
<tr class="even">
<td>Gross margin rate (GPR)</td>
<td>31.37%</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>That is virtually the reverse of conventional market distribution which usually takes a 50 - 70% margin. So what does this distribution of revenue look like from the point of view of the Life Coops, producers and the federal organisations? The following chart shows the flow of value (in euros) from the sales of goods (on the left) through each Life Coop (center) to the share of revenue provided to each category of organization (right).</p>
<div class="cell">
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item" id="htmlwidget-0bb48a422eeb71333c3e" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-0bb48a422eeb71333c3e">{"x":{"visdat":{"4761205efb8f":["function () ","plotlyVisDat"]},"cur_data":"4761205efb8f","attrs":{"4761205efb8f":{"orientation":"h","node":{"label":["Local Goods","Federation Goods","Seoul East","Seoul West","Seoul South","Seoul North","Gyeongin","Goyangpaju","Gyeonggi South","Suwon","Seongnam Yongin","Gyeonggi Southwest","Gyeonggi East","Wonju","Chuncheon","Gangwon Yeongdong","Cheongju","Daejeon","Cheonan Asan","Chungju Jaejeon","Jeonbuk","Gwangju","Jeolla South","Jeju","Gyeongbuk North","Ulsan","Gyeongnam","Dae-gu","Busan","Producer Share","Life Coop Share","Business Federation Share","Hansalim Federation Share"],"color":["darkgreen","lightgreen","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","darkblue","blue","lightblue","pink"],"pad":15,"thickness":20,"line":{"color":"black","width":0.5}},"link":{"source":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28],"target":[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32],"value":[697939.09499999997,713999.05499999993,580166.05499999993,449009.71499999997,0,525963.68999999994,329898.34499999997,271011.82500000001,967612.58999999997,148554.63,12714.134999999998,55540.695,31450.754999999997,125133.855,199411.16999999998,614293.46999999997,24089.939999999999,95690.595000000001,151900.45499999999,187366.19999999998,54202.364999999998,469753.82999999996,34796.580000000002,557414.44499999995,3279577.665,165952.91999999998,2809823.835,31763924.219999999,32099845.049999997,28919303.805,31245321.344999999,8706505.8149999995,17391598.349999998,16885709.609999999,7638518.4749999996,28703163.509999998,7138652.2199999997,6607335.21,4180273.7549999999,2782388.0699999998,6498930.4799999995,8147083.875,11351045.895,9116034.7949999999,2738892.3449999997,4372324.1099999994,4130755.5449999999,3646280.085,5582843.5949999997,2902837.77,2149357.98,11016463.395,5566114.4699999997,4488758.8199999994,22353596.145153001,22596792.654765002,20308438.932957001,21802637.804072998,5977283.1719159996,12351770.10753,11850936.641438998,5456274.3810749995,20463416.074793998,5052341.0926379999,4546075.8804089995,2913336.8350169999,1934767.604973,4559675.4545369996,5749351.9219499994,8273862.0022379998,6277310.5266479999,1955209.2573929999,3120628.6273889998,2982556.1994479997,2545683.397719,4200585.0540779997,2020080.119988,1911999.667347,10131071.242383,3951228.7468079994,5281727.5088129994,7044224.3393550003,7120604.1707849996,6401384.9596199989,6877669.8400199991,1889311.7618549999,3888110.9626799999,3735786.9262349997,1716368.0751,6438558.4137000004,1581323.8864499999,1436550.707865,919171.73564999993,610603.02502499998,1437421.9606949999,1811189.4247649999,2596478.6422049999,1983407.0674950001,615104.49797999999,981756.73060499993,937032.41866499989,803004.69164999994,1313413.6412249999,637466.65394999995,587369.61622500001,3102240.9100199998,1243858.6236299998,1583792.4361349999,2814283.6858919994,2844046.2714299997,2562250.3171229996,2768335.4711669995,771396.41520899988,1540895.6138099998,1496073.8714459999,676772.73688500002,2543100.2869859999,632484.58669199992,585409.89960599993,370372.254693,246519.58300199997,575805.24052799994,721831.63132499997,1005702.666297,807680.682837,242665.86176699997,387387.91614600003,365984.94128700002,323060.41553100001,494639.94251699996,257191.42642199996,190433.11702799998,976058.65679699986,493157.74204199994,397704.03145199997,249759.1446,252401.00801999998,227395.65029999998,245687.94473999998,68514.466019999993,136785.35597999999,132810.51587999999,60115.106939999998,225701.32451999999,21057.284219999998,52012.857119999993,32933.624640000002,21948.611999999997,51161.679239999998,64122.066959999996,89296.05425999999,71726.458019999991,21603.322859999997,34451.290860000001,32548.185599999997,28733.945099999997,43958.787179999992,22896.14964,16970.024399999998,86670.250800000009,43822.277519999996,35358.678599999999]},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"sankey"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"","font":{"size":12},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"orientation":"h","node":{"label":["Local Goods","Federation Goods","Seoul East","Seoul West","Seoul South","Seoul North","Gyeongin","Goyangpaju","Gyeonggi South","Suwon","Seongnam Yongin","Gyeonggi Southwest","Gyeonggi East","Wonju","Chuncheon","Gangwon Yeongdong","Cheongju","Daejeon","Cheonan Asan","Chungju Jaejeon","Jeonbuk","Gwangju","Jeolla South","Jeju","Gyeongbuk North","Ulsan","Gyeongnam","Dae-gu","Busan","Producer Share","Life Coop Share","Business Federation Share","Hansalim Federation Share"],"color":["darkgreen","lightgreen","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","darkblue","blue","lightblue","pink"],"pad":15,"thickness":20,"line":{"color":"black","width":0.5}},"link":{"source":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28],"target":[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32],"value":[697939.09499999997,713999.05499999993,580166.05499999993,449009.71499999997,0,525963.68999999994,329898.34499999997,271011.82500000001,967612.58999999997,148554.63,12714.134999999998,55540.695,31450.754999999997,125133.855,199411.16999999998,614293.46999999997,24089.939999999999,95690.595000000001,151900.45499999999,187366.19999999998,54202.364999999998,469753.82999999996,34796.580000000002,557414.44499999995,3279577.665,165952.91999999998,2809823.835,31763924.219999999,32099845.049999997,28919303.805,31245321.344999999,8706505.8149999995,17391598.349999998,16885709.609999999,7638518.4749999996,28703163.509999998,7138652.2199999997,6607335.21,4180273.7549999999,2782388.0699999998,6498930.4799999995,8147083.875,11351045.895,9116034.7949999999,2738892.3449999997,4372324.1099999994,4130755.5449999999,3646280.085,5582843.5949999997,2902837.77,2149357.98,11016463.395,5566114.4699999997,4488758.8199999994,22353596.145153001,22596792.654765002,20308438.932957001,21802637.804072998,5977283.1719159996,12351770.10753,11850936.641438998,5456274.3810749995,20463416.074793998,5052341.0926379999,4546075.8804089995,2913336.8350169999,1934767.604973,4559675.4545369996,5749351.9219499994,8273862.0022379998,6277310.5266479999,1955209.2573929999,3120628.6273889998,2982556.1994479997,2545683.397719,4200585.0540779997,2020080.119988,1911999.667347,10131071.242383,3951228.7468079994,5281727.5088129994,7044224.3393550003,7120604.1707849996,6401384.9596199989,6877669.8400199991,1889311.7618549999,3888110.9626799999,3735786.9262349997,1716368.0751,6438558.4137000004,1581323.8864499999,1436550.707865,919171.73564999993,610603.02502499998,1437421.9606949999,1811189.4247649999,2596478.6422049999,1983407.0674950001,615104.49797999999,981756.73060499993,937032.41866499989,803004.69164999994,1313413.6412249999,637466.65394999995,587369.61622500001,3102240.9100199998,1243858.6236299998,1583792.4361349999,2814283.6858919994,2844046.2714299997,2562250.3171229996,2768335.4711669995,771396.41520899988,1540895.6138099998,1496073.8714459999,676772.73688500002,2543100.2869859999,632484.58669199992,585409.89960599993,370372.254693,246519.58300199997,575805.24052799994,721831.63132499997,1005702.666297,807680.682837,242665.86176699997,387387.91614600003,365984.94128700002,323060.41553100001,494639.94251699996,257191.42642199996,190433.11702799998,976058.65679699986,493157.74204199994,397704.03145199997,249759.1446,252401.00801999998,227395.65029999998,245687.94473999998,68514.466019999993,136785.35597999999,132810.51587999999,60115.106939999998,225701.32451999999,21057.284219999998,52012.857119999993,32933.624640000002,21948.611999999997,51161.679239999998,64122.066959999996,89296.05425999999,71726.458019999991,21603.322859999997,34451.290860000001,32548.185599999997,28733.945099999997,43958.787179999992,22896.14964,16970.024399999998,86670.250800000009,43822.277519999996,35358.678599999999]},"type":"sankey","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>Figure 2. Flow of value from sales revenue through each Life Coop to other organizations (euros)</p>
</div>
</div>
<p>You will notice that the vast majority of sales are of ‘federation goods’ which are those supplied through the business federation’s distribution channels. A much smaller percentage of sales are accounted for by so-called ‘local goods’ which are supplied independently from Hansalim’s central distribution system. The central column of the chart looks a bit messy, but the point is that the majority of sales are through shops managed by the Life Coops in Seoul and Gyeonggi (the province surrounding Seoul) which together form the largest and densest population centre in Korea. On the right hand side you can see that the share of revenue returned to producers is by far the largest, while the margin covers the budgets of the Life Coops and finally the Business Federation and the Hansalim Federation.</p>
<p>This distribution revenue is achieved through a combination of:</p>
<ol type="1">
<li>Recovered costs from distribution by removing the multiple opportunities from profit gauging by intermediaries;</li>
<li>Prices set to reflect the true costs of production; and</li>
<li>Economies of scope and scale achieved through shared business activities and collectively owned capital at local, regional and national levels.</li>
</ol>
<p>After providing for producers’ livelihoods, what then does the remaining 30% pay for?</p>
</section>
<section id="a-different-kind-of-consumer-experience" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="a-different-kind-of-consumer-experience">A different kind of consumer experience</h3>
<p>The largest portion (21.7%) goes to the Life Coops themselves to cover the costs of running stores, handling local distribution and their various educational, participation and engagement activities. Life Coops are autonomous member owned businesses which run the Hansalim stores in their local areas. They decide when and where to open new stores, how to manage them and how to organize local distribution options such as home delivery. Stores are usually run by an employed manager and the Life Coop’s Store Activists (consumer members who are trained and paid to staff the stores) and products are ordered through the Hansalim Business Federation and delivered from their national logistics centre.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Yangju-store.jpeg" class="lightbox" data-gallery="stores" title="North Seoul Hansalim, Yangju Store (2024)"><img src="../images/chapter_01/Yangju-store.jpeg" class="img-fluid figure-img" alt="North Seoul Hansalim, Yangju Store (2024)"></a></p>
<figcaption>North Seoul Hansalim, Yangju Store (2024)</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Ssangmoon-Store.jpeg" class="lightbox" data-gallery="stores" title="North Seoul Hansalim, Ssangmoon Store with home delivery vehicle"><img src="../images/chapter_01/Ssangmoon-Store.jpeg" class="img-fluid figure-img" alt="North Seoul Hansalim, Ssangmoon Store with home delivery vehicle"></a></p>
<figcaption>North Seoul Hansalim, Ssangmoon Store with home delivery vehicle</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Hansalim-Store-Interior.jpeg" class="lightbox" data-gallery="stores" title="Inside a Hansalim Store"><img src="../images/chapter_01/Hansalim-Store-Interior.jpeg" class="img-fluid figure-img" alt="Inside a Hansalim Store"></a></p>
<figcaption>Inside a Hansalim Store</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Hansalim-Store-Interior-Wide.jpeg" class="lightbox" data-gallery="stores" title="A wide-angle view inside a Hansalim Store"><img src="../images/chapter_01/Hansalim-Store-Interior-Wide.jpeg" class="img-fluid figure-img" alt="A wide-angle view inside a Hansalim Store"></a></p>
<figcaption>A wide-angle view inside a Hansalim Store</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Hansalim-Jeju-Store.JPG" class="lightbox" data-gallery="stores" title="Inside the store at the Jeju Hansalim head office"><img src="../images/chapter_01/Hansalim-Jeju-Store.JPG" class="img-fluid figure-img" alt="Inside the store at the Jeju Hansalim head office"></a></p>
<figcaption>Inside the store at the Jeju Hansalim head office</figcaption>
</figure>
</div>
<p>In a Hansalim store you can buy virtually everything you need from food to household goods and even cosmetics. Almost all these products are made by Hansalim producers and processors with a few exceptions for some household items and a handful of fair trade products. Hansalim branded sales through the business federation are supplemented by local goods sourced by each store according to the decision of each Life Coop. What this means is that there is usually just one type of everything you need rather than multiple brands of the same product so the shop size is relatively small compared to a regular supermarket. Here are a few examples of the products that are available in my local Hansalim store.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Rice.jpeg" class="lightbox" data-gallery="products" title="Hansalim Rice"><img src="../images/chapter_01/Products-Rice.jpeg" class="img-fluid figure-img" alt="Hansalim Rice"></a></p>
<figcaption>Hansalim Rice</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Fruit-Veg.jpeg" class="lightbox" data-gallery="products" title="Fruit and vegetables"><img src="../images/chapter_01/Products-Fruit-Veg.jpeg" class="img-fluid figure-img" alt="Fruit and vegetables"></a></p>
<figcaption>Fruit and vegetables</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Sweet-Potatoes.jpeg" class="lightbox" data-gallery="products" title="Sweet potatoes"><img src="../images/chapter_01/Products-Sweet-Potatoes.jpeg" class="img-fluid figure-img" alt="Sweet potatoes"></a></p>
<figcaption>Sweet potatoes</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Tofu-etc.jpeg" class="lightbox" data-gallery="products" title="Tofu and other ingredients for cooking"><img src="../images/chapter_01/Products-Tofu-etc.jpeg" class="img-fluid figure-img" alt="Tofu and other ingredients for cooking"></a></p>
<figcaption>Tofu and other ingredients for cooking</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Frozen-Meats.jpeg" class="lightbox" data-gallery="products" title="Frozen meats"><img src="../images/chapter_01/Products-Frozen-Meats.jpeg" class="img-fluid figure-img" alt="Frozen meats"></a></p>
<figcaption>Frozen meats</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Chilled-Goods.jpeg" class="lightbox" data-gallery="products" title="Dairy products and other chilled processed goods"><img src="../images/chapter_01/Products-Chilled-Goods.jpeg" class="img-fluid figure-img" alt="Dairy products and other chilled processed goods"></a></p>
<figcaption>Dairy products and other chilled processed goods</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Cereals.jpeg" class="lightbox" data-gallery="products" title="Breakfast cereals and flour etc."><img src="../images/chapter_01/Products-Cereals.jpeg" class="img-fluid figure-img" alt="Breakfast cereals and flour etc."></a></p>
<figcaption>Breakfast cereals and flour etc.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Bottled.jpeg" class="lightbox" data-gallery="products" title="Bottled juice, preserves and other ingredients in jars"><img src="../images/chapter_01/Products-Bottled.jpeg" class="img-fluid figure-img" alt="Bottled juice, preserves and other ingredients in jars"></a></p>
<figcaption>Bottled juice, preserves and other ingredients in jars</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Kimchi-Cabbages.jpeg" class="lightbox" data-gallery="products" title="Cabbages for making Kimchi (these are distributed over a period of a week or two each November in time for ‘Kimjang’ when families and communities gather to make Kimchi together)"><img src="../images/chapter_01/Products-Kimchi-Cabbages.jpeg" class="img-fluid figure-img" alt="Cabbages for making Kimchi (these are distributed over a period of a week or two each November in time for ‘Kimjang’ when families and communities gather to make Kimchi together)"></a></p>
<figcaption>Cabbages for making Kimchi (these are distributed over a period of a week or two each November in time for ‘Kimjang’ when families and communities gather to make Kimchi together)</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Ready-Meals.jpeg" class="lightbox" data-gallery="products" title="Ready meals! Frozen foods."><img src="../images/chapter_01/Products-Ready-Meals.jpeg" class="img-fluid figure-img" alt="Ready meals! Frozen foods."></a></p>
<figcaption>Ready meals! Frozen foods.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Rice-Wine.jpeg" class="lightbox" data-gallery="products" title="One of my favourites, traditionally made rice wine"><img src="../images/chapter_01/Products-Rice-Wine.jpeg" class="img-fluid figure-img" alt="One of my favourites, traditionally made rice wine"></a></p>
<figcaption>One of my favourites, traditionally made rice wine</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Cosmetics.jpeg" class="lightbox" data-gallery="products" title="You can even by cosmetics made by Hansalim with eco-friendly natural ingredients"><img src="../images/chapter_01/Products-Cosmetics.jpeg" class="img-fluid figure-img" alt="You can even by cosmetics made by Hansalim with eco-friendly natural ingredients"></a></p>
<figcaption>You can even by cosmetics made by Hansalim with eco-friendly natural ingredients</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Products-Cleaning.jpeg" class="lightbox" data-gallery="products" title="Household cleaning products are also available including toilet paper and kitchen paper made in Hansalim’s Anseong logistics centre from recycled milk and drinks cartons"><img src="../images/chapter_01/Products-Cleaning.jpeg" class="img-fluid figure-img" alt="Household cleaning products are also available including toilet paper and kitchen paper made in Hansalim’s Anseong logistics centre from recycled milk and drinks cartons"></a></p>
<figcaption>Household cleaning products are also available including toilet paper and kitchen paper made in Hansalim’s Anseong logistics centre from recycled milk and drinks cartons</figcaption>
</figure>
</div>
<p>Hansalim stores also differ from a conventional supermarket in another way. They often provide the venue for member activities and encounters between consumers and producers facilitated by the Life Coop’s Organizing Activists (members who are trained and paid to organize opportunities for consumers and producers to meet each other and share food and other activities together). From the beginning of Hansalim, relationship building among consumers and between consumers and producers has been a top priority.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Hansalim-Store-Activity-Room.jpeg" class="lightbox" data-gallery="stores" title="An activity room inside a Hansalim Store showing the small kitchen, library and meeting space"><img src="../images/chapter_01/Hansalim-Store-Activity-Room.jpeg" class="img-fluid figure-img" alt="An activity room inside a Hansalim Store showing the small kitchen, library and meeting space"></a></p>
<figcaption>An activity room inside a Hansalim Store showing the small kitchen, library and meeting space</figcaption>
</figure>
</div>
<p>There are various ways consumers can build community together and participate in the livelihoods of producers. Neighbourhood meetings and small groups provide a context for consumer members to learn and build relationships through reading groups, cooking classes, social activities, and environmental activism etc. ‘Helping hands’ visits are organized by Activists to bring members to help producers with farming activities such as planting, weeding and harvest and to join in with traditional rural rituals and share meals together. Community work is also an important shared activity in which members and producers raise money for charitable causes, donate food to people in need and provide education and support to marginalized groups. Consumers often visit the producer communities for local festivals or just to see the farm, share a meal and get to know each other. Producers also visit stores to introduce their new products and many develop special relationships with particular Life Coops as well as participating in Hansalim conferences and multistakeholder committees.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Activity-Farm-Visit-1.jpeg" class="lightbox" data-gallery="activities" title="A visit to Nunbisan farm by Life Coop members"><img src="../images/chapter_01/Activity-Farm-Visit-1.jpeg" class="img-fluid figure-img" alt="A visit to Nunbisan farm by Life Coop members"></a></p>
<figcaption>A visit to Nunbisan farm by Life Coop members</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Activity-Sharing-Meal.jpeg" class="lightbox" data-gallery="activities" title="Sharing a meal during the visit to Nunbisan"><img src="../images/chapter_01/Activity-Sharing-Meal.jpeg" class="img-fluid figure-img" alt="Sharing a meal during the visit to Nunbisan"></a></p>
<figcaption>Sharing a meal during the visit to Nunbisan</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Activity-Farm-Visit-2jpeg.jpeg" class="lightbox" data-gallery="activities" title="Life Coop members visiting the rice fields at Our Seed Farm"><img src="../images/chapter_01/Activity-Farm-Visit-2jpeg.jpeg" class="img-fluid figure-img" alt="Life Coop members visiting the rice fields at Our Seed Farm"></a></p>
<figcaption>Life Coop members visiting the rice fields at Our Seed Farm</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Activity-Rice-Planting.jpeg" class="lightbox" data-gallery="activities" title="Joining in with planting out rice seedlings on Hansalim farm in Paju"><img src="../images/chapter_01/Activity-Rice-Planting.jpeg" class="img-fluid figure-img" alt="Joining in with planting out rice seedlings on Hansalim farm in Paju"></a></p>
<figcaption>Joining in with planting out rice seedlings on Hansalim farm in Paju</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Activity-Farm-Ceremony-1.jpeg" class="lightbox" data-gallery="activities" title="A traditional ceremony showing respect to the land"><img src="../images/chapter_01/Activity-Farm-Ceremony-1.jpeg" class="img-fluid figure-img" alt="A traditional ceremony showing respect to the land"></a></p>
<figcaption>A traditional ceremony showing respect to the land</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Activity-Farm-Ceremony-2.jpeg" class="lightbox" data-gallery="activities" title="Sharing food together as part of the ceremony"><img src="../images/chapter_01/Activity-Farm-Ceremony-2.jpeg" class="img-fluid figure-img" alt="Sharing food together as part of the ceremony"></a></p>
<figcaption>Sharing food together as part of the ceremony</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Activity-Sharing-Stories.jpeg" class="lightbox" data-gallery="activities" title="Sharing stories after the ceremony and rice planting activity in Paju"><img src="../images/chapter_01/Activity-Sharing-Stories.jpeg" class="img-fluid figure-img" alt="Sharing stories after the ceremony and rice planting activity in Paju"></a></p>
<figcaption>Sharing stories after the ceremony and rice planting activity in Paju</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Activity-Helping-Hands.jpeg" class="lightbox" data-gallery="activities" title="A ‘helping hands’ activity at a Hansalim farm"><img src="../images/chapter_01/Activity-Helping-Hands.jpeg" class="img-fluid figure-img" alt="A ‘helping hands’ activity at a Hansalim farm"></a></p>
<figcaption>A ‘helping hands’ activity at a Hansalim farm</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Activity-Producer-Consumer-Conference.jpeg" class="lightbox" data-gallery="activities" title="Hansalim producers and consumer members participating in a conference organised by the Hansalim Food Life Education Centre"><img src="../images/chapter_01/Activity-Producer-Consumer-Conference.jpeg" class="img-fluid figure-img" alt="Hansalim producers and consumer members participating in a conference organised by the Hansalim Food Life Education Centre"></a></p>
<figcaption>Hansalim producers and consumer members participating in a conference organised by the Hansalim Food Life Education Centre</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Activity-Org-Activists_Gathering.jpeg" class="lightbox" data-gallery="activities" title="A gathering of North Seoul Hansalim Organisational Activists to share ideas and prepare for the year ahead"><img src="../images/chapter_01/Activity-Org-Activists_Gathering.jpeg" class="img-fluid figure-img" alt="A gathering of North Seoul Hansalim Organisational Activists to share ideas and prepare for the year ahead"></a></p>
<figcaption>A gathering of North Seoul Hansalim Organisational Activists to share ideas and prepare for the year ahead</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Activity-Charity-Sale.jpeg" class="lightbox" data-gallery="activities" title="A ‘yard sale’ to raise money for charity organised by Hansalim Activists"><img src="../images/chapter_01/Activity-Charity-Sale.jpeg" class="img-fluid figure-img" alt="A ‘yard sale’ to raise money for charity organised by Hansalim Activists"></a></p>
<figcaption>A ‘yard sale’ to raise money for charity organised by Hansalim Activists</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Activity-Forum.jpeg" class="lightbox" data-gallery="activities" title="A national research forum organised by Wonju Hansalim Life Coop"><img src="../images/chapter_01/Activity-Forum.jpeg" class="img-fluid figure-img" alt="A national research forum organised by Wonju Hansalim Life Coop"></a></p>
<figcaption>A national research forum organised by Wonju Hansalim Life Coop</figcaption>
</figure>
</div>
<p>Each of these activities are supported by funds allocated in the budgets of the Life Coops and the Hansalim Federation which ultimately come from their combined sales. The chart below gives you an idea of the amount of interaction between consumers and producers in the course of a single year. It shows the number of ‘person-visits’ categorized by each Life Coop and by the type of activity in 2023. <em>Exchange</em> refers to activities involving interaction between producers and consumers and <em>engagement</em> refers to activities among consumers themselves. You can see that there were around 59,000 encounters between individuals in 2023 that were directly facilitated by Hansalim’s member Life Coops. Although many of these are repeat visits of individuals (so the total number of people involved will be somewhat less) you still get a sense of the sheer scale of relationship building that is going on within Hansalim.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../plots/Participation_2023.png" class="lightbox" data-gallery="diagrams" title="Participation in 2023: engagement among consumers and exchanges between consumers and producers"><img src="../plots/Participation_2023.png" class="img-fluid figure-img" alt="Participation in 2023: engagement among consumers and exchanges between consumers and producers"></a></p>
<figcaption>Participation in 2023: engagement among consumers and exchanges between consumers and producers</figcaption>
</figure>
</div>
<p>In addition to selling to members and organizing member activities, Life Coops also engage with the wider community by running a whole range of educational activities and training, community kitchens, environmental campaigns and community building activities and some have also set up new cooperatives in solar power and in the care sector. On top of all these activities, the high point of Hansalim’s cultural life are the festivals which are held at national and local levels. For example, the Autumn festivals bring producers and consumers together for food, drinking and traditional games and dancing. They provide a special context for making friends and creating a sense of shared identity and camaraderie.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Festival-Dragon-Flags.jpeg" class="lightbox" data-gallery="festivals" title="Celebration Festival at Goesan"><img src="../images/chapter_01/Festival-Dragon-Flags.jpeg" class="img-fluid figure-img" alt="Celebration Festival at Goesan"></a></p>
<figcaption>Celebration Festival at Goesan</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Festival-Dancers.jpeg" class="lightbox" data-gallery="festivals" title="Dancing at the festival in Goesan"><img src="../images/chapter_01/Festival-Dancers.jpeg" class="img-fluid figure-img" alt="Dancing at the festival in Goesan"></a></p>
<figcaption>Dancing at the festival in Goesan</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Festival-Goesan-Dancers.jpeg" class="lightbox" data-gallery="festivals" title="Autumn harvest festival in Goesan (in the foreground is the rope used for the mass tug-of-war game!)"><img src="../images/chapter_01/Festival-Goesan-Dancers.jpeg" class="img-fluid figure-img" alt="Autumn harvest festival in Goesan (in the foreground is the rope used for the mass tug-of-war game!)"></a></p>
<figcaption>Autumn harvest festival in Goesan (in the foreground is the rope used for the mass tug-of-war game!)</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Festival-Goesan-Flag.jpeg" class="lightbox" data-gallery="festivals" title="Hansalim flag flying among the dancers at the Autumn festival"><img src="../images/chapter_01/Festival-Goesan-Flag.jpeg" class="img-fluid figure-img" alt="Hansalim flag flying among the dancers at the Autumn festival"></a></p>
<figcaption>Hansalim flag flying among the dancers at the Autumn festival</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Festival-Goesan-Rope.jpeg" class="lightbox" data-gallery="festivals" title="The being prepared for the giant tug-of-war game"><img src="../images/chapter_01/Festival-Goesan-Rope.jpeg" class="img-fluid figure-img" alt="The being prepared for the giant tug-of-war game"></a></p>
<figcaption>The being prepared for the giant tug-of-war game</figcaption>
</figure>
</div>
<p>For consumers and producers then, there is a lot of fun to be had as a member of a Hansalim community. This is a vitally important part of the rhythm of hard work broken up by fantastic celebrations and informal contexts for relaxation together. None of this would be possible, however, without the hard and often hidden work of the Practitioners.</p>
</section>
<section id="the-special-role-of-practitioners" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="the-special-role-of-practitioners">The special role of practitioners</h3>
<p>In Hansalim, employees are referred to as ‘practitioners.’ They are the people who make it possible to put the producer-consumer relationship into practice by running the businesses, coordinating movement activities and organizing the many processes that are required to keep each member organization running and working together as a federation. They are not only professionals in logistics, marketing, strategy etc. but they also act as mediators between consumer and producer members and their organizations. Whereas a manager in a corporate enterprise might be able to focus solely on negotiating financial dealings with clients and suppliers, Hansalim practitioners often find themselves also negotiating the complex conflicts in values and expectations between Hansalim members, making their role especially difficult and important.</p>
<p>The largest employer of practitioners within Hansalim is the Business Federation which takes the next largest share of revenue after the Life Coops (8.86%) to cover the costs of labour, logistics, promotion and marketing, product development etc. One of the most important asset managed by the business federation is the Anseong Logistics Centre.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/chapter_01/Logistics-Anseong.jpeg" class="lightbox" data-gallery="quarto-lightbox-gallery-64" title="Hansalim’s Anseong logistics and processing centre"><img src="../images/chapter_01/Logistics-Anseong.jpeg" class="img-fluid figure-img" alt="Hansalim’s Anseong logistics and processing centre"></a></p>
<figcaption>Hansalim’s Anseong logistics and processing centre</figcaption>
</figure>
</div>
<p>Finally, the smallest share of the margin (0.81%) is used to fund the Hansalim Federation which organizes the national-level governance and policy-making processes, supports Hansalim’s educational, cultural, publishing, research and charitable activities, coordinates collaboration and solidarity activities with others in Korea and abroad, and provides support to the member Life Coops.</p>
<p>In 2023 there were a total of 291 practitioners working in the member Life Coops, a further 235 working for the Business Federation and 40 at the Hansalim Federation. These were supplemented by 1,396 Activists working in the stores and to organize member activities. Together with the 3,579 producers and processors they generate enough revenue to support themselves and the broader collective efforts of the Hansalim Life Movement to bring about social and cultural change towards a more sustainable way of living.</p>
<p>With such a large and complex organisation, you might think that there must be some strong central authority controlling everything from the top down and making sure efficiency is maximised and operations meticulously coordinated. Happily (or perhaps sadly, depending on your point of view) that is not the case in Hansalim.</p>
</section>
</section>
<section id="governed-through-deliberative-democracy" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="governed-through-deliberative-democracy"><span class="header-section-number">1.5</span> Governed through deliberative democracy</h2>
<p>Below is a diagram of Hansalim’s various organizations and how they relate to each other, laid out in order of how authority is delegated from top to bottom. At the top are the individual members. The 890,000 Cooperator households and the 3,579 Producers. They are the owners of Hansalim. Below you can see the Life Coops, Producer Organizations and the Support Organizations and in the box labelled ‘Member Organisations Autonomous Activities’ I have listed the numbers of people involved. The word ‘Practitioner’ here is Hansalim’s term for employed staff member (as mentioned above). Remember that ‘Activists’ refers to consumer members paid to either organise producer-consumer activities or work in the stores. Between them, the member organisations elect a total of 212 delegates to the General Assembly of the Hansalim Federation (maximum two 1-year terms). The General Assembly elects a board of 36 directors including the chair of directors who holds the title of president (maximum two 2-year terms). The board appoints the executive directors of the Federation, the Business Federation and the support organizations but cannot interfere with the governance and management of the member Life Coops or producer organizations. The standing committees, conferences and steering committees are were deliberations take place over policy and strategy decisions and they operate at local and national level involving producers, consumers and employees.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../diagrams/federation.png" class="lightbox" data-gallery="diagrams" title="Federation"><img src="../diagrams/federation.png" class="img-fluid figure-img" alt="Federation"></a></p>
<figcaption>Federation</figcaption>
</figure>
</div>
<p>So you see that neither the Hansalim Federation nor the Business Federation are ‘apex’ organisations or ‘head offices’ but rather, they are supporting organisations whose purpose is to facilitate the successful business of the Life Coops and producer organisations while running the delegated shared movement activities and supporting the independent movement activities of member organisations. The way the Hansalim Federation sees itself in relation to the other Hansalim organisations can be understood with the help of the following diagram which was published in the Hansalim 2017 White Paper. I have reproduced it here with some minor modifications and translated it into English.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../diagrams/stakeholders.png" class="lightbox" data-gallery="diagrams" title="label"><img src="../diagrams/stakeholders.png" class="img-fluid figure-img" alt="label"></a></p>
<figcaption>label</figcaption>
</figure>
</div>
<p>Hansalim’s stakeholders include five categories: Producers, Cooperators (i.e.&nbsp;consumer members), Practitioners, Activists and the Local Community. Along with Producers, the Cooperators share the main responsibility for governance of the federation and their local associations and Life Coops. Cooperators are also expected to consume responsibly and participate in activities to support producers and help the local community.</p>
<p>The original role of Practitioners was to act as a bridge between producers and consumers while running the business activities. In the beginning people joined Hansalim as Practitioners to support their shared vision and often worked very long hours for low pay doing whatever was needed. Now, as Hansalim has grown larger, many of those who worked for Hansalim from the early days have taken on managerial positions while the hiring of new employees has become more formalized and specialized. As a consequence, the role of Practitioners as bridge between consumers and producers has become weaker and the emphasis has shifted towards running business operations.</p>
<p>Activists were originally member volunteers whose role was to organize consumer activities and also act as a bridge with producers. After a while, it was decided that they should be financially compensated for their work and their roles should be more clearly specified. Now, Activists are members who have received training for specific roles and are paid a small amount of compensation to work in the stores, receive phone orders and organize various activities for producers and members.</p>
<p>The Local Community is included as a stakeholder category as producers, members and activists seek to identify and take action on local needs. They work with local community organizations and representatives of such organizations are also invited to participate on various councils as appropriate. In fact, it is quite common for Hansalim members and producers to simultaneously hold official positions in Hansalim and other local grassroots organizations and social enterprises.</p>
<p>The organizational role of Hansalim in this structure is to support each of these different stakeholders to realize their own and Hansalim’s values in their various activities.</p>
</section>
<section id="conclusion" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">1.6</span> Conclusion</h2>
<p>For those in Europe and other regions of the world outside Korea, Hansalim can appear to be a uniquely Korean phenomenon. “Surely, it is only the collectivist culture of Korea that makes such a community possible. It could never succeed in our hyper-individualist western societies.” But you must not forget that the two strongest influences on contemporary Korean culture are Confucianism and American consumerism. The former provided the rationale for a strictly hierarchical and patriarchal culture that dominated Korean society for several hundred years before the latter collided head on with it during the post-war period, giving rise to a uniquely oppressive mixture of competitive consumerism and rigid conformism.</p>
<p>It was in this context that Hansalim emerged as a concrete expression of the desire felt among many at the time for a different kind of society built upon equality, mutual respect and care for other humans and the nonhuman world. I have a feeling that this same desire has not gone away, but only deepened, not only among Koreans but equally among contemporary people in Europe and beyond.</p>
<p>However, no matter how much you desire to create something like Hansalim, managing such a large organization (or rather, federation of organisations) without a dictatorial head office but in a deliberative and democratic way is very, very hard work. If you were in it for the money, you would not do it like this. But for every member of Hansalim I have spoken to so far, its not about money, but about being part of a community dedicated to caring for each other and to creating a peaceful and thriving future for the world. So as a reader from outside Korea who aspires to transform food systems, you need to keep in mind that Hansalim’s success is mingled with failures and disappointments and comes at the cost of a great deal of personal sacrifice, collective conflict and agonising, trial and error and lots and lots and lots of ….. meetings.</p>
<p>Assuming you are prepared for such a challenge, it is nevertheless not possible to simply transplant Hansalim’s model to other countries. It has its own history and unique context from which it emerged and it is not a static model but an evolving community in a continual process of change. But what is perhaps much more useful than a blueprint, is Hansalim’s story and the myriad stories of the people who practice Hansalim (as a verb). These stories carry the values of Hansalim, the spirit and emotion of Hansalim people and the experience of countless challenges and success that they faced along the way. These stories, more than anything else, carry the seeds that could produce new fruit in other contexts, as long as there are those with the determination to cultivate them.</p>
<p>To hear some of these stories, I am afraid you will have to wait a little longer for the rest of the book to be written and published. I’ll do my best to finish it as soon as possible! Each new chapter will be published here as soon as it is written.</p>
<p>And of course, it is a story without an ending. Which means, in all likelihood, there are those among you reading this book who will end up playing a role in it one way or another.</p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>https://www.koreaherald.com/view.php?ud=20230524000525<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Hwang, Kyung Moon. 2021. A History of Korea. 3rd Edition. London, England: Red Globe Press.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Hansalim. 2017. “Because of you we live: Hansalim 30th Anniversary White Paper.” Seoul, Korea: Hansalim.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Hansalim. 2024. “Hansalim Federation 14th General Assembly Resource Book.” 14. Seoul, Korea: Hansalim Cooperative Federation.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>see for example Hansalim. 2021. “Hansalim Annual Report 2021.” Seoul, Korea: Hansalim.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Hansalim. 2021. Hansalim Manifesto (English Version). Mosim and Salim Research Institute.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Yoon, Hyunggeun, ed.&nbsp;2004. Salim’s Words. Mosim and Salim, Book 3. Seoul: Mosim and Salim Research Institute.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Hansalim. 2024. “Hansalim Federation 14th General Assembly Resource Book.” 14. Seoul, Korea: Hansalim Cooperative Federation.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../intro.html" class="pagination-link" aria-label="Introduction">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Introduction</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/02_fromwhence.html" class="pagination-link" aria-label="Beginnings">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Beginnings</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2024 Jonathan Dolley</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/JonathanDolley/book.livingtogether.xyz">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>